### ISSUE TITLE
Microcenter in stock detection is broken

### ISSUE THREAD

**Issue by likwidsage** [jef/nvidia-snatcher#105]
### Description

The lookup function is using all else cases as a positive results, which not the case for all. In this case, Microcenter is being falsely identified as in stock. 

### Possible solution

Modify the models to add an "availableLabel" (possibly as a regex string). Use regex string to detect "add to cart" or such to allow for actual positive results.

**Comment by jef** [comment]
Just noticed this. Thanks for the issue!

**Comment by geman220** [comment]
I believe this was fixed already, are you still having trouble @likwidsage ?

**Comment by likwidsage** [comment]
> I believe this was fixed already, are you still having trouble @likwidsage ?

It is fixed.
