### ISSUE TITLE
error :: Protocol error (Target.createTarget): Target closed.

### ISSUE THREAD

**Issue by kfquach** [jef/nvidia-snatcher#109]
Running into the error below. Any clues?

bash$ npm run start

> nvidia-snatcher@1.4.0 start /Users/kevinquach/Documents/nvidia-snatcher
> npm run build && node build/index.js

> nvidia-snatcher@1.4.0 build /Users/kevinquach/Documents/nvidia-snatcher
> rimraf ./build && tsc

[12:04:25 PM] info :: ✖ [nvidia] still out of stock: nvidia founders edition
[12:04:26 PM] error :: Protocol error (Target.createTarget): Target closed.

**Comment by jef** [comment]
Should be fixed in latest now if you'd like to confirm.

**Comment by kfquach** [comment]
thank you! resolved
