### ISSUE TITLE
Suggestion only use chromium/chrome for opening browser window

### ISSUE THREAD

**Issue by zerocarbthirty** [jef/nvidia-snatcher#113]
### Description

When using nvidia-snatcher from SSH, when headless is enabled and open browser is disabled it seems to still want to use chromium/chrome to do the checks.

### Possible solution

Use curl or another way of checking the URLs, or perhaps create a list of all of the libraries needed to get chromium to run in SSH

**Comment by jef** [comment]
This project's backbone (as of now) is puppeteer, which is based off using the Chromium browser. Curl-like requests would suffice but would need to mock the browser's agent and other headers that query websites to ensure we don't trigger catchpas and other related problems.

Not sure if I'm willing to take on this work as of now, but definitely should look into this in the future as it would be great to use for all the various notifications. As well as integration with Docker.

**Comment by zerocarbthirty** [comment]
It turns out it doesn't really matter because you can install chrome manually from SSH and that works, but the real problem is that most retailers have blocked all IP addresses from the major clouds anyway and as such the project is really only useful from behind residential networks.

**Comment by jef** [comment]
Ah, so you're trying to proxy from a cloud provider to your home network via SSH?

Now this is an interesting request!

**Comment by zerocarbthirty** [comment]
No, I was just running the project directly from a VM in GCE rather than my
PC but a whole lot of the sites it checks block GCE :)

**Comment by jef** [comment]
Wow... Okay cool. This is good information. Thanks for the issue. Maybe we can come up with a solution. I'll put this in todo and go from there.

Thanks!

**Comment by zerocarbthirty** [comment]
One other suggestion, you might want to see if you can filter amazon
results by seller as a zotac just popped up for $1500.

**Comment by matthewLee711** [comment]
Dang my AWS EC2 instance was blocked after 5 hours of runtime. 10 second interval is a little too quick. I think 30-60 seconds would be the way to do it.

**Comment by jef** [comment]
> One other suggestion, you might want to see if you can filter amazon results by seller as a zotac just popped up for $1500.

Done in https://github.com/jef/nvidia-snatcher/pull/126

**Comment by zerocarbthirty** [comment]
Yea man they are probably blocking known cloud providers.

**Comment by jef** [comment]
I'm gonna close this out in favor of https://github.com/jef/nvidia-snatcher/pull/352. I think you'll be able to direct all your traffic from any sort of cloud provider through this proxy.

Let me know otherwise and I can reopen.
