### ISSUE TITLE
Issue when testing new notification system

### ISSUE THREAD

**Issue by jdkennedy45** [jef/nvidia-snatcher#115]
### Description
Stdout of failure:

> $ npm run test:notification
> 
> nvidia-snatcher@1.4.0 test:notification C:\Users\Jake\Documents\nvidia-snatcher
> npm run build && node build/__test__/*.js
> 
> 
> nvidia-snatcher@1.4.0 build C:\Users\Jake\Documents\nvidia-snatcher
> rimraf ./build && tsc
> 
> internal/modules/cjs/loader.js:968
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Users\Jake\Documents\nvidia-snatcher\build\__test__\*.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/*.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nvidia-snatcher@1.4.0 test:notification script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Jake\AppData\Roaming\npm-cache\_logs\2020-09-20T17_30_20_350Z-debug.log
> 

Debug Log:

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'test:notification'
> 1 verbose cli ]
> 2 info using npm@6.14.6
> 3 info using node@v12.18.4
> 4 verbose run-script [
> 4 verbose run-script   'pretest:notification',
> 4 verbose run-script   'test:notification',
> 4 verbose run-script   'posttest:notification'
> 4 verbose run-script ]
> 5 info lifecycle nvidia-snatcher@1.4.0~pretest:notification: nvidia-snatcher@1.4.0
> 6 info lifecycle nvidia-snatcher@1.4.0~test:notification: nvidia-snatcher@1.4.0
> 7 verbose lifecycle nvidia-snatcher@1.4.0~test:notification: unsafe-perm in lifecycle true
> 8 verbose lifecycle nvidia-snatcher@1.4.0~test:notification: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Jake\Documents\nvidia-snatcher\node_modules\.bin;C:\Users\Jake\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Jake\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Users\Jake\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\Jake\AppData\Local\Programs\Python\Python38;C:\Users\Jake\AppData\Local\Microsoft\WindowsApps;C:\Users\Jake\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
> 9 verbose lifecycle nvidia-snatcher@1.4.0~test:notification: CWD: C:\Users\Jake\Documents\nvidia-snatcher
> 10 silly lifecycle nvidia-snatcher@1.4.0~test:notification: Args: [ '/d /s /c', 'npm run build && node build/__test__/*.js' ]
> 11 silly lifecycle nvidia-snatcher@1.4.0~test:notification: Returned: code: 1  signal: null
> 12 info lifecycle nvidia-snatcher@1.4.0~test:notification: Failed to exec test:notification script
> 13 verbose stack Error: nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/*.js`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:315:20)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:315:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 14 verbose pkgid nvidia-snatcher@1.4.0
> 15 verbose cwd C:\Users\Jake\Documents\nvidia-snatcher
> 16 verbose Windows_NT 10.0.19041
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:notification"
> 18 verbose node v12.18.4
> 19 verbose npm  v6.14.6
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/*.js`
> 22 error Exit status 1
> 23 error Failed at the nvidia-snatcher@1.4.0 test:notification script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
> 

### Possible solution

Not sure if it's on my end. But it worked before when I just did it through .env file.

**Comment by jef** [comment]
Try an `npm install` and then `npm run test:notification`

**Comment by jdkennedy45** [comment]
I did that again but no luck.

Is this an issue that would impact that?

> npm WARN eslint-import-resolver-webpack@0.12.2 requires a peer of webpack@>=1.11.0 but none is installed. You must install peer dependencies yourself.

**Comment by jef** [comment]
That should've been resolved by using `npm install`. Do you mind deleting the `node_modules` folder and retry the above commands?

**Comment by jdkennedy45** [comment]
Did the install and test again after deleting the folder. But I still get the >MODULE_NOT_FOUND< error.

> Jake@JAKE-PC MINGW64 ~/Documents/nvidia-snatcher (main)
> $ npm install
> 
> > puppeteer@5.3.0 install C:\Users\Jake\Documents\nvidia-snatcher\node_modules\puppeteer
> > node install.js
> 
> 
> Chromium (800071) downloaded to C:\Users\Jake\Documents\nvidia-snatcher\node_modules\puppeteer\.local-chromium\win64-800071
> 
> > nodemailer@6.4.11 postinstall C:\Users\Jake\Documents\nvidia-snatcher\node_modules\nodemailer
> > node -e "try{require('./postinstall')}catch(e){}"
> 
>                            === Nodemailer 6.4.11 ===
> 
> Thank you for using Nodemailer for your email sending needs! While Nodemailer
> itself is mostly meant to be a SMTP client there are other related projects in
> the Nodemailer project as well.
> 
> > IMAP API (  https://imapapi.com  ) is a server application to easily access
>   IMAP accounts via REST API
> > ImapFlow (  https://imapflow.com/  ) is an async IMAP client library for
>   Node.js
> > NodemailerApp (  https://nodemailer.com/app/  ) is a cross platform GUI app to
>   debug emails
> > Project Pending (  https://projectpending.com/  ) allows you to host DNS of
>   your project domains
> > Pending DNS (  https://pendingdns.com/  ) is the DNS server used that powers
>   Project Pending
> > Ethereal Email (  https://ethereal.email/  ) is an email testing service that
>   accepts all your test emails
> 
>                             Don't like this message?
>                   There's a Github Sponsors goal to remove it
>                        https://github.com/sponsors/andris9
> 
> ........
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> added 933 packages from 513 contributors and audited 941 packages in 19.549s
> 
> 64 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> 
> Jake@JAKE-PC MINGW64 ~/Documents/nvidia-snatcher (main)
> $ npm run test:notification
> 
> > nvidia-snatcher@1.4.0 test:notification C:\Users\Jake\Documents\nvidia-snatcher
> > npm run build && node build/__test__/*.js
> 
> 
> > nvidia-snatcher@1.4.0 build C:\Users\Jake\Documents\nvidia-snatcher
> > rimraf ./build && tsc
> 
> internal/modules/cjs/loader.js:968
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Users\Jake\Documents\nvidia-snatcher\build\__test__\*.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/*.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nvidia-snatcher@1.4.0 test:notification script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Jake\AppData\Roaming\npm-cache\_logs\2020-09-20T18_24_33_636Z-debug.log
>

**Comment by jef** [comment]
Looks like Windows doesn't like the wildcard I think...

Can you go into `package.json` and change this line:

```json
    "test:notification": "npm run build && node build/__test__/*.js"
```

to this line:

```json
    "test:notification": "npm run build && node build/__test__/notification-test.js"
```

**Comment by jdkennedy45** [comment]
Yep, worked instantly after changing that.

**Comment by jef** [comment]
Great. I just pushed the change. Should be working in latest now.

Thanks!
