### ISSUE TITLE
Sound player issue

### ISSUE THREAD

**Issue by jdkennedy45** [jef/nvidia-snatcher#116]
> $ npm start
> 
> nvidia-snatcher@1.4.0 start C:\Users\Jake\Documents\nvidia-snatcher
> npm run build && node build/index.js
> 
> 
>  nvidia-snatcher@1.4.0 build C:\Users\Jake\Documents\nvidia-snatcher
>  rimraf ./build && tsc
> 
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> [2:06:40 PM] info :: ✖ [amazon] still out of stock: pny xlr8
> [2:06:41 PM] info :: ✖ [newegg] still out of stock: asus tuf
> ....

Hi I'm just confused on what this means. It prints it out every time I start the program. But the program seems to operate normally after..?

**Comment by jef** [comment]
Not sure what's going on here. Can you post your `.env`?

**Comment by m1se** [comment]
Maybe its related to the naming of the .env file?

**Comment by jdkennedy45** [comment]
> DISCORD_NOTIFY_GROUP="@here"
> DISCORD_WEB_HOOK="XXXXXXXXXXXXX"
> EMAIL_USERNAME="XXXXXXXXXXXXXXXXXX"
> EMAIL_PASSWORD="XXXXXXXXXXXXXXX"
> HEADLESS="true"
> LOG_LEVEL="info"
> OPEN_BROWSER="true"
> PAGE_TIMEOUT="30000"
> PHONE_NUMBER="XXXXXXXXXXXXXXX"
> PHONE_CARRIER="sprint"
> PLAY_SOUND="C:\Users\Jake\Downloads\swiftly.mp3"
> PUSHOVER_TOKEN="XXXXXXXXXXXXXX"
> PUSHOVER_USER="XXXXXXXXXXXXXXX"
> RATE_LIMIT_TIMEOUT="5000"
> SHOW_ONLY_BRANDS="evga,zotac,aorus,asus,msi,gigabyte,pny"
> SLACK_CHANNEL="SlackChannelName"
> SLACK_TOKEN="slack-token"
> STORES="bestbuy,bandh,nvidia,amazon,asus,evga,newegg"
> SCREENSHOT="true"
> TELEGRAM_ACCESS_TOKEN=""
> TELEGRAM_CHAT_ID="1234"
> 

Here is a pic of my folder structure with the .env
[https://puu.sh/GuEME/66b0d5787f.png]

**Comment by jef** [comment]
I don't think so. I removed my `.env` and also changed the name, no problems there.

**Comment by jef** [comment]
`C:\Users\Jake\Downloads\swiftly.mp3` is more than likely you're problem. I would put that `swiftly.mp3` file into the root of the `nvidia-snatcher` and change that variable to `PLAY_SOUND=switfly.mp3`.

**Comment by jdkennedy45** [comment]
Changed that but didn't help anything.
I noticed on npm install I get a warning. Is this impacting it?

> npm WARN eslint-import-resolver-webpack@0.12.2 requires a peer of webpack@>=1.11.0 but none is installed. You must install peer dependencies yourself.

**Comment by CrazyGiant** [comment]
I just tried to set it up today, getting the same issue. It does start to check stores after the INFO lines, but it only checks for evga cards?

**Comment by m1se** [comment]
> I just tried to set it up today, getting the same issue. It does start to check stores after the INFO lines, but it only checks for evga cards?

You need to edit the .env variable SHOW_ONLY_BRANDS, to include other brands, i.e msi, asus,evga

**Comment by jdkennedy45** [comment]
My program seems to operate normally after the PATTERN INFO pop-ups. But I was just worried I configured something wrong.

**Comment by chuakc92** [comment]
I'm getting the same. But it is still checking for stock after the fact.

**Comment by jef** [comment]
> https://imgur.com/a/iMxezEh

@chuakc92 based off your screenshot, I would remove the SLACK and TELEGRAM related variables as setting those to junk values could throw errors.

**Comment by chuakc92** [comment]
Responding to kylekelso's question:
`the mplayer still in a zip file. Do you have it elsewhere?`

I didn't unzip it because I was unsure if it helps.

**Comment by kylekelso** [comment]
@chuakc92 - It's what is used to play the file. The sound file is played through the command line interface so needs something like mplayer to play the sound.

**Comment by chuakc92** [comment]
I removed Slack and Telegram variables and now I'm getting 
```playing sound
error playing sound: Error: Couldn't find a suitable audio player```

**Comment by chuakc92** [comment]
@kylekelso Okay, let me go ahead and install it

**Comment by vp-cshow** [comment]
Per the `play-sound` documentation: 

https://github.com/shime/play-sound

```
players – List of available audio players to check. Default:
mplayer
afplay
mpg123
mpg321
play
omxplayer
aplay
cmdmp3
```

Windows (at least 10) doesn't ship with any of these by default. If installing mplayer solves @chuakc92's issue, then looks like we'll need to find some sort of simpler solution for this.

**Comment by chuakc92** [comment]
I decided to give mpg123 a go instead of mplayer and placed all the files inside the root folder and it finally worked.

**Comment by chuakc92** [comment]
As an added note, after adding mpg123 to my root folder, my `INFO: Could not find files for the given pattern(s).` has decreased from 8 iterations to 2

**Comment by kylekelso** [comment]
@chuakc92 it's because mpg123 is 3rd on the list that @vp-cshow showed. The 2 that show errors are because mplayer and afplay don't exist for you and stops checking when mpg123 is found.

**Comment by vp-cshow** [comment]
@kylekelso 

Correct. The player has a setting to explicitly define what player to use, so if we distribute this with a player included, we can get rid of the log lines entirely.

It probably wasn't showing for jef because macOS ships mplayer, @jef can you confirm once you get a chance?

**Comment by jef** [comment]
I can try some testing when I get back on my macOS and see what we need to do.

**Comment by jef** [comment]
Nope, not problems on macOS... I just pulled latest.

**Comment by vp-cshow** [comment]
Any ideas then? First two ideas that I can think of are either redistribute a copy of one of the sound playing programs `play-sound` supports (probably not the cleanest idea...) or just open a youtube video instead (seems redundant since we're opening a page anyway).

**Comment by jef** [comment]
Well... Let me try on the windows computer and go from there.

**Comment by kevhardy** [comment]
If you add additional player options to the play-sound library you can customize it to open any program you want as long as it can open via the command line. VLC does work through the command line but will require to you add it to your PATH to make it work anywhere. [Here is a guide on how to add it to your path on Windows.](https://www.vlchelp.com/add-vlc-command-prompt-windows/)

Once it's in your PATH, it should work find when you pass in that player to your play-sound library when you initialize is like so:

`const player = playerLib({ player: 'vlc' });`

This has worked for me so far, however it's not a very elegant solution considering you have to manually add the program of your choice to your PATH. This should work with windows media player as well but I have not tried it.

**Comment by scyto** [comment]
put cmdmp3win.exe the root of the github structure - still getting the error

**Comment by scyto** [comment]
Ok, here is what i see - there is one `INFO: Could not find files for the given pattern(s).` for each player.
 
If one copies cmdmp3win.exe to the root of the folder AND renames to cmdmp3.exe then you will go from having 8 errors to 7 errors - i don't know if this means the sound will play!

Maybe feature request is to say what player is being looked for and if no player is installed say no player installed.  I have no idea how to code so cant contribute to doing that, sorry.

**Comment by scyto** [comment]
more info:

- lack of any player executable generates 8 of these messages
- if just an exe called mplayer.exe is present no errors are generated
- if just an exe called omxplayer.exe is present only 5 of these errors are generated
- if just an exe called cmdmp3.exe is present only 7 of these errors are generated

note the only one of these that is a real player was cmdmp3.exe - the rest were fake files.
i have no idea what this means, just more info as requested

**Comment by scyto** [comment]
ok possible fix

download mplayer from here and either add to your path variables or extract contents into the root of you project http://mplayerwin.sourceforge.net/downloads.html

this was from https://github.com/shime/play-sound/issues/39

no idea if it works, no idea how to force a test; i have both mplayer and cmdmp3 in root of my project now and all INFO messages have disappeared.

**Comment by Cturner44** [comment]
> I decided to give mpg123 a go instead of mplayer and placed all the files inside the root folder and it finally worked.

i did this and i'm still getting `error playing sound: Error: Couldn't find a suitable audio player`

unzipped and extracted the mpg123 folder to the root nvidia-snatcher folder.

**Comment by MGraefe** [comment]
> ok possible fix
> 
> download mplayer from here and either add to your path variables or extract contents into the root of you project http://mplayerwin.sourceforge.net/downloads.html

For me just pasting the single mplayer.exe file into the root folder of nvidia-snatcher was enough, no need to copy all contents of the mplayer zip file.

**Comment by c-sarmiento** [comment]
For all those who have issues with audio notification on Windows, follow the instructions found here: https://github.com/jef/streetmerchant/wiki/Installation:-Windows#audio-notifications
