### ISSUE TITLE
Unable to test notifications

### ISSUE THREAD

**Issue by chuakc92** [jef/nvidia-snatcher#118]
### Description

I changed the url for certain cards as suggested to test in stock alerts, for example:
```
    links: [
        {
            brand: 'evga',
            model: 'xc3 black',
            url: 'https://google.com',
            oosLabels: ['out of stock']
        },
```

But after running the program, this file is immediately replaced. Everything was working fine this morning before I took a pull. I'm currently on commit 5b91065

Also, not sure how to fix this, but I kept getting `Error: Couldn't find a suitable audio player` when I was able to successfully test this morning. How do I go about fixing this? What are compatible players or do I have to do something to set one up?

**Comment by jef** [comment]
You're probably editing the `*.js` file and not the `*.ts` file.

**Comment by jef** [comment]
I'd run a `npm install` to get any dependencies missing.

**Comment by jef** [comment]
Also take a look at `PLAY_SOUND` to make sure you're setting the right variable.

**Comment by chuakc92** [comment]
Hey Jeff, thank you for the swift response. You are right that I was setting the .js file instead. That is resolved.

I ran npm install and all I got was `npm WARN eslint-import-resolver-webpack@0.12.2 requires a peer of webpack@>=1.11.0 but none is installed. You must install dependencies yourself.`

Would this cause the sound error?

Also, I received a different error when I forgot to set my PLAY_SOUND. Now that I did, it's just throwing `Error: Couldn't find a suitable audio player`

**Comment by jef** [comment]
That's interesting because that's also related to #115. We aren't using webpack, but looks like some dependency is.

I've reinstalled everything from scratch, but still haven't seen this problem. Sort of strange.

Ensure you're using the correct file: `.env`. Removing `PLAY_SOUND` shouldn't run any of the sound code.

**Comment by chuakc92** [comment]
Hey Jeff,

There is only one .env file in my folder, so it's probably correct. I do intend to use PLAY_SOUND. Do you know of a way to fix this? What player are you using? Maybe I could try installing that

**Comment by jef** [comment]
I don't have any particular player. I think it comes with the module.

Can you take a screenshot of your output when you do `npm run start` and a screenshot of your directory of where nvidia-snatcher is?

**Comment by jdkennedy45** [comment]
Also getting the sound player issue.

> Jake@JAKE-PC MINGW64 ~/Documents/nvidia-snatcher (main)
> $ npm run test:notification
> 
> > nvidia-snatcher@1.4.0 test:notification C:\Users\Jake\Documents\nvidia-snatcher
> > npm run build && node build/__test__/notification-test.js
> 
> 
> > nvidia-snatcher@1.4.0 build C:\Users\Jake\Documents\nvidia-snatcher
> > rimraf ./build && tsc
> 
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> INFO: Could not find files for the given pattern(s).
> [2:35:37 PM] info :: ↗ playing sound
> [2:35:37 PM] error :: error playing sound: Error: Couldn't find a suitable audio player
> [2:35:38 PM] info :: ↗ discord message sent: http://example.com/
> [2:35:38 PM] info :: ↗ pushover notification sent: {"info":"no active devices to send to","status":1,"request":"25c9b631-4022-4507-92c0-e78f9d2b34dc"}
> [2:35:39 PM] info :: ↗ email sent: 250 2.0.0 OK  1600626937 o35sm7607200qte.23 - gsmtp
> [2:35:39 PM] info :: ↗ sms sent: 250 2.0.0 OK  1600626937 145sm7216001qkf.18 - gsmtp
>

**Comment by chuakc92** [comment]
Jeff,

Here you go:
[https://imgur.com/a/iMxezEh](url)

**Comment by kylekelso** [comment]
the mplayer still in a zip file. Do you have it elsewhere?

**Comment by jef** [comment]
I'm going to merge this issue with #116. Let's move discussion to there since it's the same issue.

Thanks!
