### ISSUE TITLE
show  all brands has stock on best buy

### ISSUE THREAD

**Issue by Gotischer** [jef/nvidia-snatcher#122]
The script open many tabs like if had stock of all cards on best buy

**Comment by vp-cshow** [comment]
I thought about this too. Do you have a suggestion on how we best handle this issue?

Maybe have it so that once one card is carted per store, it won't try to add cards from the same store anymore?

**Comment by Gotischer** [comment]
> I thought about this too. Do you have a suggestion on how we best handle this issue?
> 
> Maybe have it so that once one card is carted per store, it won't try to add cards from the same store anymore?

Filter by word "Sold Out"

**Comment by jef** [comment]
Not really sure what's being asked here. Sorry 😢

**Comment by Gotischer** [comment]
> Not really sure what's being asked here. Sorry 😢

If you run the program always send emails and open new tab from browser when check stock in best buy even if they don't have stock.

**Comment by vp-cshow** [comment]
Ah, I thought you were asking something else; I'll make a separate issue for what I thought I understood later.

In the `nvidia-snatcher` folder, there should be screenshots that look like `success-somenumber.png`. Do you mind posting one of them here?

**Comment by Gotischer** [comment]
![success-1600631227104](https://user-images.githubusercontent.com/6912517/93727209-c1427d80-fb7f-11ea-9a6e-bbe2c8f5f1a7.png)

**Comment by Gotischer** [comment]
> Ah, I thought you were asking something else; I'll make a separate issue for what I thought I understood later.
> 
> In the `nvidia-snatcher` folder, there should be screenshots that look like `success-somenumber.png`. Do you mind posting one of them here?

![success-1600631227104](https://user-images.githubusercontent.com/6912517/93727229-d4ede400-fb7f-11ea-9f57-02438c3a3d5b.png)

**Comment by vp-cshow** [comment]
The bot assumes that the page that it's looking at is the product page for each card. If it isn't, it won't behave as expected. This is known.

**Comment by geman220** [comment]
This is the same as #150 and should be resolved in #153

**Comment by geman220** [comment]
#153 Has been merged, closing this.
