### ISSUE TITLE
Newegg false positives (missing 'out of stock')

### ISSUE THREAD

**Issue by kjack9** [jef/nvidia-snatcher#125]
### Description

The Newegg store is giving false positives due to the removal of the 'out of stock' string for out of stock detection.

### Possible solution

Add 'out of stock' to the oosList label in the NewEgg store.

**Comment by Doridian** [comment]
Being fixed in https://github.com/jef/nvidia-snatcher/pull/124

**Comment by Doridian** [comment]
Should be fixed. Re-open if still an issue in latest version.

**Comment by kjack9** [comment]
Confirmed, fixed in the latest commit.
