### ISSUE TITLE
Add EU sites

### ISSUE THREAD

**Issue by odsdark** [jef/nvidia-snatcher#127]
is-it the same stock for french peolpe than the us or do i need to modify something?

**Comment by jef** [comment]
Probably need to modify all the URLs. I don't have anyone that is doing this right now, so feel free to contribute as I don't know any of those links :(

**Comment by geman220** [comment]
If you can provide links I can see if I can get other stores added.

**Comment by antoine-souesme-needone** [comment]
I'm willing to contribute, but how do you get to know those endpoints ?

**Comment by aagiulian** [comment]
Looking to modify the urls as well to match french / europe sellers, starting with nvidia I'm just wondering if the digitalriver url should be changed as well.
thank you for your work !

**Comment by HMellor** [comment]
I've implemented the GB nvidia store (#163), if you can find the DigitalRiver ID for other regions it should be extendable to EU.

**Comment by geman220** [comment]
This is being worked in #162

**Comment by HMellor** [comment]
Yeah I've just seen, I closed my #163
