### ISSUE TITLE
JavaScript Heap out of memory

### ISSUE THREAD

**Issue by venomdp** [jef/nvidia-snatcher#129]
### Description

First of all, thank you for this awesome tool! 

After about 1.5hrs of runtime, javascript ran out of memory. 
![image](https://user-images.githubusercontent.com/35393969/93721892-89740f80-fb58-11ea-9c16-e5b2a83708fe.png)

### Possible solution

Apologies if I'm being the big dumb, I don't have much experience with javascript or node js.

**Comment by jef** [comment]
Fixed in #139
