### ISSUE TITLE
feat: Send email with screenshot attachment

### ISSUE THREAD

**Issue by arickho** [jef/nvidia-snatcher#130]
### Description

I have this working on my local branch. Let me know if it's useful enough for the community to use. Helps me out with false/positives. 

![Capture](https://user-images.githubusercontent.com/17790061/93722201-14f29e00-fb63-11ea-9cac-623713ba1c77.PNG)

**Comment by jef** [comment]
Yeah! Why not.

**Comment by arickho** [comment]
Already implemented.
