### ISSUE TITLE
Program fails at 1-2 hours due to lack of memory

### ISSUE THREAD

**Issue by zhirzzh** [jef/nvidia-snatcher#138]
### Description

The program runs well for 1-2 hours, and then fails. The failure message mentions memory allocation, but I should have more than enough ram. Here is the error message:

<--- Last few GCs --->
t of marking 77 ms) (average mu = 0.226, current mu = 0.114) alloca[28112:000001B8ACB04470]  3894656 ms: Mark-sweep 2045.5 (2061.8) -> 2044.4 (2060.7) MB, 78.5 / 0.0 ms  (+ 0.0 ms in 1 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 78 ms) (average mu = 0.134, current mu = 0.019) finali[28112:000001B8ACB04470]  3894740 ms: Mark-sweep 2045.4 (2061.7) -> 2045.4 (2062.7) MB, 79.8 / 0.0 ms  (average mu = 0.093, current mu = 0.050) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF796CB106C]
Security context: 0x0195739c08d1 <JSObject>
    1: toString [00000365647B1AA1] [buffer.js:~774] [pc=00000044DD4D53F0](this=0x0331f5fc0b69 <Uint8Array map = 000002BF99525739>,0x0322e97c04b1 <undefined>,0x0322e97c04b1 <undefined>,0x0322e97c04b1 <undefined>)
    2: arguments adaptor frame: 0->3
    3: _write [00000072550F2241] [D:\downloads\3080 buyer\node_modules\ws\lib\receiver.js:~73] [pc=00000044DD...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF796115F0F napi_wrap+114095
 2: 00007FF7960C0B96 v8::base::CPU::has_sse+66998
 3: 00007FF7960C1996 v8::base::CPU::has_sse+70582
 4: 00007FF7968D6E9E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7968BEF71 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF79678B1DC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF796796410 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF796792F34 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF796788733 v8::internal::Heap::CollectGarbage+1283
10: 00007FF796786DA4 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF7967AEA2B v8::internal::Factory::NewRawOneByteString+91
12: 00007FF7967B1732 v8::internal::Factory::NewStringFromUtf8+130
13: 00007FF7968D376A v8::String::NewFromUtf8+298
14: 00007FF795FE7821 node::tracing::TraceEventHelper::SetAgent+40561
15: 00007FF7960D956D v8::internal::Malloced::operator delete+2829
16: 00007FF796CB106C v8::internal::SetupIsolateDelegate::SetupHeap+45852
17: 00000044DD4D53F0
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! nvidia-snatcher@1.4.0 start: `npm run build && node build/index.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the nvidia-snatcher@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zerocarbthirty** [comment]
Yeah it does this for me, I just use forever which you can get by doing npm -g install forever and then start the script with this:

forever start build/index.js 

then if you type forever logs and copy the log file name into a powershell window you can watch the log run

like:

C:\nvidia>forever logs
info:    Logs for running Forever processes
data:        script                   logfile
data:    [0] C:\nvidia\build\index.js C:\Users\aweav\.forever\autY.log

Get-Content  C:\nvidia\build\index.js C:\Users\aweav\.forever\autY.log –Wait

**Comment by jef** [comment]
I believe #139 fixes this.

Also @zerocarbthirty, nice work around!

**Comment by jef** [comment]
@Doridian, do you mind confirming? Looks like it's relevant to that issue.

**Comment by zhirzzh** [comment]
Thanks, that seems to have fixed the issue for me. I will report back in a few more hours to confirm.

**Comment by Doridian** [comment]
Yeah, #139 should have fixed this
