### ISSUE TITLE
False positives for bhphotovideo and newegg

### ISSUE THREAD

**Issue by aTimetochill** [jef/nvidia-snatcher#142]
### Description

Received several false positives for the following links

**bhphotovideo**
[https://www.bhphotovideo.com/c/product/1593649-REG/asus_tuf_rtx3080_10g_gaming_tuf_gaming_geforce_rtx.html](https://www.bhphotovideo.com/c/product/1593649-REG/asus_tuf_rtx3080_10g_gaming_tuf_gaming_geforce_rtx.html)
[https://www.bhphotovideo.com/c/product/1593650-REG/asus_tuf_rtx3080_o10g_gaming_tuf_gaming_geforce_rtx.html](https://www.bhphotovideo.com/c/product/1593650-REG/asus_tuf_rtx3080_o10g_gaming_tuf_gaming_geforce_rtx.html)
[https://www.bhphotovideo.com/c/product/1593333-REG/gigabyte_gv_n3080gaming_oc_10gd_geforce_rtx_3080_gaming.html](https://www.bhphotovideo.com/c/product/1593333-REG/gigabyte_gv_n3080gaming_oc_10gd_geforce_rtx_3080_gaming.html)
[https://www.bhphotovideo.com/c/product/1593650-REG/asus_tuf_rtx3080_o10g_gaming_tuf_gaming_geforce_rtx.html](https://www.bhphotovideo.com/c/product/1593650-REG/asus_tuf_rtx3080_o10g_gaming_tuf_gaming_geforce_rtx.html)

**newegg**
[https://www.newegg.com/asus-geforce-rtx-3080-tuf-rtx3080-10g-gaming/p/N82E16814126453](https://www.newegg.com/asus-geforce-rtx-3080-tuf-rtx3080-10g-gaming/p/N82E16814126453)
[https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3885-kr/p/N82E16814487520](https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3885-kr/p/N82E16814487520)

Sorry, I don't have screenshots.

**Comment by jef** [comment]
B&H will provide problems throughout the weekend since they observe the Sabbath.

**Comment by aTimetochill** [comment]
Thanks. I'm turning on screenshots and will add them if I run into more false positives.

**Comment by jef** [comment]
Thank you :)

**Comment by arickho** [comment]
@jef these were the false positives.

Newegg - 
![success-1600646869836](https://user-images.githubusercontent.com/17790061/93726031-ac66e980-fb81-11ea-8f33-9509d9bcd354.png)

B&H - 
![success-1600647404894](https://user-images.githubusercontent.com/17790061/93726036-b2f56100-fb81-11ea-9fed-13e68dde9f2c.png)

**Comment by serg06** [comment]
Here's another false positive I got for B&H:

![success-1600647018781](https://user-images.githubusercontent.com/1350889/93726250-f8665e00-fb82-11ea-9dfb-d6f120efffe1.png)

**Comment by sachinmu** [comment]
![success-1600674616432](https://user-images.githubusercontent.com/10097069/93743395-d7166980-fba4-11ea-963b-7ebfb0d2275f.png)
^ False positive for Newegg. Same as what @arickho encountered :)

**Comment by aTimetochill** [comment]
![success-1600673900329](https://user-images.githubusercontent.com/46465769/93757938-2ec8cb00-fbcd-11ea-84d7-082ce25adb74.png)

**Comment by g1forfun** [comment]
False positive I just got for Newegg
![success-1600720891397](https://user-images.githubusercontent.com/2007992/93819366-9f053a00-fc29-11ea-9c24-95fc2402f81e.png)

**Comment by g1forfun** [comment]
False positive from b&h, this is the screenshot it took: 
![success-1600720612314](https://user-images.githubusercontent.com/2007992/93819468-bfcd8f80-fc29-11ea-8df4-14bb3498e7e5.png)

**Comment by geman220** [comment]
These have been resolved except the latest B&H which will be resolved with #173

**Comment by aharris02** [comment]
Here's a unique newegg one I found. 
![success-1600727515436](https://user-images.githubusercontent.com/12698673/93828456-01ae0400-fc31-11ea-9c3f-07db5d209046.png)

Would it be easier to find the "in stock" text for each store and look for that, rather than looking for the "out of stock" text, which is complicated by site outages, captcha, etc?

**Comment by jef** [comment]
Yeah! There is a PR that should address this:

https://github.com/jef/nvidia-snatcher/pull/141
