### ISSUE TITLE
scripts throws some error, then freezes after timeout. 

### ISSUE THREAD

**Issue by drx19** [jef/nvidia-snatcher#146]
### Description
Hi, it is now 8:52pm the script is frozen and stuck since 8:45pm after timing out. 

I noticed some errors before that on "INFO: could not find files for giver pattern(s)" also "UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'links' of undefined"

![image](https://user-images.githubusercontent.com/71615615/93726327-7591d300-fb83-11ea-9053-84c410ed4c39.png)

**Comment by drx19** [comment]
I removed bandh thinking the timeout was causing the issue. the issue repeated even without the timeout. 
https://imgur.com/a/zOHXiq0

**Comment by jef** [comment]
More than likely an `.env` configuration problem.

Can you post your `.env`?

**Comment by geman220** [comment]
As @jef stated, this is a `.env` configuration problem, the application is still running as you can see the scans continuing.  If you need help with your `.env` check out https://github.com/jef/nvidia-snatcher#customization or #help in discord.
