### ISSUE TITLE
Please add "&intl=nosplash" to all BestBuy links for international users

### ISSUE THREAD

**Issue by brinew27** [jef/nvidia-snatcher#150]
I'm a US resident currently abroad trying to buy a card. When I go to the Best Buy website, it first drops me on a splash screen to choose my country, which breaks this tool and always gives alerts. I've discovered you can bypass this screen by putting "&intl=nosplash" at the end of every Best Buy url and it goes directly to the product page. Could you please add this to future versions as I have to add it manually each time I pull currently.

Thanks!

**Comment by geman220** [comment]
Submitted PR #153 to add this
