### ISSUE TITLE
Automatically add to cart and checkout

### ISSUE THREAD

**Issue by DakkJaniels** [jef/nvidia-snatcher#151]
### Description

Using the digital river API, it is possible to add the item to cart and check out using API calls only, as long as you have a session token that is authenticated. 

### Possible solution
**Note that this requires you to have already created an NVIDIA store account, and to have saved your address and payment information to the account.**

Getting an authenticated token, two methods:

1. Manual method:
- Add something to your cart, open up dev tools (F12), clear everything (to make it easier to find), then click the checkout button.
- The NVIDIA store will make the call for the token, you can find it right after SessionToken?...
![image](https://user-images.githubusercontent.com/6080734/93729542-fc9a7780-fb92-11ea-975c-f9a837580bf0.png)
- Log into the store using your account
- Your token is now authenticated! (you can verify here, replace {{accTok}} with your token: https://api.digitalriver.com/oauth20/access-tokens?token={{accTok}}&format=json}

2. Automatic method:
I'm not sure (I don't have much experience with this stuff), but I think this requires using puppeteer. You get a limited access token using your API key, add something to your cart using the API, request the web-checkout (https://api.digitalriver.com/v1/shoppers/me/carts/active/web-checkout), and then use puppeteer to log in.

Once you have an authenticated token, 3 calls are required to purchase an item (assuming your cart is empty and you know the item ID):

1. Add the item to your cart (replace 5056110800 with your item ID):
![image](https://user-images.githubusercontent.com/6080734/93729765-e0e3a100-fb93-11ea-8e1f-12f4bf3dacf3.png)

2. Apply shopper details (default addresses and payment info) to the cart:
![image](https://user-images.githubusercontent.com/6080734/93729791-f9ec5200-fb93-11ea-8749-137bc44b68a4.png)

3. Submit the cart:
![image](https://user-images.githubusercontent.com/6080734/93729821-14263000-fb94-11ea-8cf1-45611bcc6ec0.png)

**Comment by lukszi** [comment]
Since checkout isn't quite as easy as availability detection, and every shop seems to have a different system in place, I propose adding a addToCart method to the Store interface that returns either null in case of failure or plainly not being implemented, or a link to the cart if said functionality is implemented.
The signature would look like this: addToCart(browser: Browser): string | null;

**Comment by jef** [comment]
https://github.com/jef/nvidia-snatcher/pull/108 just got merged into `main`. Will do everything you're talking about except purchasing.

**Comment by aharris02** [comment]
@jef is that a philosophical preference for the library - automate everything up to purchase, but don't want to fully automate the purchase?

**Comment by jef** [comment]
I'm between the two. I don't have any problems with checking out, but I'd rather not get in the business of handling peoples' card information or processing payments, because it has risk involved.

But everything up to that point does not include those risks (from my understanding).

**Comment by jef** [comment]
Using a product 'AS-IS' helps, but doesn't completely negate this, as there is negligence from creator to consumer.

Not sure if I want to go down that route. But getting all the way to the cart is something we are going for.

**Comment by geman220** [comment]
Do we want to keep this open?  I think as of today the plans are to enhance all the way up to actually inputting your address/credit card/paypal the (final) process.  If that is the case, this is resolved for now and we could open an enhancement at another time for auto purchase if that is what is decided?

**Comment by aharris02** [comment]
> 
> 
> I'm between the two. I don't have any problems with checking out, but I'd rather not get in the business of handling peoples' card information or processing payments, because it has risk involved.
> 
> But everything up to that point does not include those risks (from my understanding).

Cool, good to know. I agree for a widely-accessible library that's probably the safest route.

**Comment by zerocarbthirty** [comment]
Is there a way to make it so that the links it sends in telegram or via whatever method are as deep into the process aa possible without needing an intermediate landing page? Im not sure what I am asking is possible but the system I run NS on isnt the one I mostly use. 

I guess it would depend on the site and whether you can add to cart directly or not.

**Comment by jef** [comment]
Closing for now. Feel free to discuss within.

**Comment by NSExceptional** [comment]
Broken, for Best Buy at least

**Comment by DakkJaniels** [comment]
This has nothing to do with Best Buy (it was a discussion about the nvidia store) and this is incredibly old!

**Comment by NSExceptional** [comment]
My bad, I just sorta skimmed the issue and assumed it would end up working for any store. Nothing tells you it only works for the Nvidia store.

Has it _ever_ worked for Best Buy or other stores?

**Comment by jef** [comment]
> Has it ever worked for Best Buy or other stores?

No, this was never implemented.

And all auto-add to cart has been removed.
