### ISSUE TITLE
Problem running nvidia-snatcher

### ISSUE THREAD

**Issue by djsupafly** [jef/nvidia-snatcher#152]
### I'm getting this error after following all the instructions.  I have downloaded all files into once location as catalina acts up.  
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:notification'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.11.0
4 verbose run-script [
4 verbose run-script   'pretest:notification',
4 verbose run-script   'test:notification',
4 verbose run-script   'posttest:notification'
4 verbose run-script ]
5 info lifecycle nvidia-snatcher@1.4.0~pretest:notification: nvidia-snatcher@1.4.0
6 info lifecycle nvidia-snatcher@1.4.0~test:notification: nvidia-snatcher@1.4.0
7 verbose lifecycle nvidia-snatcher@1.4.0~test:notification: unsafe-perm in lifecycle true
8 verbose lifecycle nvidia-snatcher@1.4.0~test:notification: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ivanavalos/Downloads/nvidia/nvidia-snatcher/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle nvidia-snatcher@1.4.0~test:notification: CWD: /Users/ivanavalos/Downloads/nvidia/nvidia-snatcher
10 silly lifecycle nvidia-snatcher@1.4.0~test:notification: Args: [ '-c', 'npm run build && node build/__test__/notification-test.js' ]
11 silly lifecycle nvidia-snatcher@1.4.0~test:notification: Returned: code: 1  signal: null
12 info lifecycle nvidia-snatcher@1.4.0~test:notification: Failed to exec test:notification script
13 verbose stack Error: nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/notification-test.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid nvidia-snatcher@1.4.0
15 verbose cwd /Users/ivanavalos/Downloads/nvidia/nvidia-snatcher
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:notification"
18 verbose node v14.11.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/notification-test.js`
22 error Exit status 1
23 error Failed at the nvidia-snatcher@1.4.0 test:notification script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by geman220** [comment]
Need more info.  What OS.  What steps did you take to install?

**Comment by djsupafly** [comment]
> Need more info. What OS. What steps did you take to install?

I did post the os version on top. Catalina.
I downloaded everything into my downloads folder vs having it in the root. I tried dosing everything in the root directory but kept getting errors.

**Comment by jef** [comment]
Did you run an `npm install`?

**Comment by djsupafly** [comment]
> Did you run an `npm install`?

Yes, I am able to run it via the new directory but whenever I run a test I get this:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:notification'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.11.0
4 verbose run-script [
4 verbose run-script   'pretest:notification',
4 verbose run-script   'test:notification',
4 verbose run-script   'posttest:notification'
4 verbose run-script ]
5 info lifecycle nvidia-snatcher@1.4.0~pretest:notification: nvidia-snatcher@1.4.0
6 info lifecycle nvidia-snatcher@1.4.0~test:notification: nvidia-snatcher@1.4.0
7 verbose lifecycle nvidia-snatcher@1.4.0~test:notification: unsafe-perm in lifecycle true
8 verbose lifecycle nvidia-snatcher@1.4.0~test:notification: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ivanavalos/.Trash/nvidia-snatcher 8.23.15 AM/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle nvidia-snatcher@1.4.0~test:notification: CWD: /Users/ivanavalos/.Trash/nvidia-snatcher 8.23.15 AM
10 silly lifecycle nvidia-snatcher@1.4.0~test:notification: Args: [ '-c', 'npm run build && node build/__test__/notification-test.js' ]
11 silly lifecycle nvidia-snatcher@1.4.0~test:notification: Returned: code: 1  signal: null
12 info lifecycle nvidia-snatcher@1.4.0~test:notification: Failed to exec test:notification script
13 verbose stack Error: nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/notification-test.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid nvidia-snatcher@1.4.0
15 verbose cwd /Users/ivanavalos/.Trash/nvidia-snatcher 8.23.15 AM
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:notification"
18 verbose node v14.11.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/notification-test.js`
22 error Exit status 1
23 error Failed at the nvidia-snatcher@1.4.0 test:notification script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


Also, last night there was a stock message and got this at the end

[8:08:46 AM] info :: 🚀🚀🚀 [newegg] asus tuf IN STOCK 🚀🚀🚀
[8:08:46 AM] info :: https://www.newegg.com/asus-geforce-rtx-3080-tuf-rtx3080-10g-gaming/p/N82E16814126453
[8:08:46 AM] info :: ✖ [nvidia] still out of stock: nvidia founders edition
[8:08:46 AM] error :: Error sending webhook: 404 status code. Response: {"message": "Unknown Webhook", "code": 10015}
[8:08:46 AM] error :: An API error occurred: invalid_auth
/Users/userrrrrs/Downloads/nvidia/nvidia-snatcher/node_modules/pushover-notifications/lib/pushover.js:146
      throw new Error(d.errors[0], res)
      ^

Error: application token is invalid
    at Pushover.errors (/Users/userrrrrs/Downloads/nvidia/nvidia-snatcher/node_modules/pushover-notifications/lib/pushover.js:146:13)
    at IncomingMessage.<anonymous> (/Users/userrrrrs/Downloads/nvidia/nvidia-snatcher/node_modules/pushover-notifications/lib/pushover.js:250:12)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nvidia-snatcher@1.4.0 start: `npm run build && node build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nvidia-snatcher@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/userrrrrs/.npm/_logs/2020-09-21T13_08_47_330Z-debug.log

**Comment by jef** [comment]
Can you post your `.env`?

**Comment by djsupafly** [comment]
> Can you post your `.env`?

DISCORD_NOTIFY_GROUP="@here"
DISCORD_WEB_HOOK="https://discordapp.com/api/webhooks/23123123123/5dfsdfh3h2j5hdfhsdfsdhj55jf"
EMAIL_USERNAME="********@gmail.com"
EMAIL_PASSWORD="*********"
HEADLESS="true"
LOG_LEVEL="info"
OPEN_BROWSER="true"
PAGE_TIMEOUT="30000"
PHONE_NUMBER="5***********"
PHONE_CARRIER="google"
PLAY_SOUND="/Users/userrrrrs/Music/lovingly.mp3"
PUSHOVER_TOKEN="************************"
PUSHOVER_USER="**********@pomail.net"
PAGE_SLEEP_MIN="3000"
PAGE_SLEEP_MAX="6000"
SHOW_ONLY_BRANDS="nvidia,msi,asus,gigabyte"
SHOW_ONLY_SERIES="3080"
SLACK_CHANNEL="SlackChannelName"
SLACK_TOKEN="slack-token"
STORES="nvidia,bestbuy"
SCREENSHOT="true"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID="1234"
USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"

**Comment by jef** [comment]
I'd remove

```
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID="1234"
SLACK_CHANNEL="SlackChannelName"
SLACK_TOKEN="slack-token"
```

since you're not using. Seems like that's the issue with some of the notification auths. I'd also confirm your pushover token and username is correct.

**Comment by geman220** [comment]
Were you able to resolve your problem?

**Comment by djsupafly** [comment]
> I'd remove
> 
> ```
> TELEGRAM_ACCESS_TOKEN=""
> TELEGRAM_CHAT_ID="1234"
> SLACK_CHANNEL="SlackChannelName"
> SLACK_TOKEN="slack-token"
> ```
> 
> since you're not using. Seems like that's the issue with some of the notification auths. I'd also confirm your pushover token and username is correct.

Yeah I was getting an error from pushover. I was able to fix that.  I get the text now however there is one error still:

$ npm run test:notification

> nvidia-snatcher@1.4.0 test:notification /Users/userrrrrs/Downloads/nvidia/nvidia-snatcher
> npm run build && node build/__test__/notification-test.js


> nvidia-snatcher@1.4.0 build /Users/userrrrrs/Downloads/nvidia/nvidia-snatcher
> rimraf ./build && tsc

[3:43:03 PM] error :: Error sending webhook: 404 status code. Response: {"message": "Unknown Webhook", "code": 10015}
[3:43:04 PM] info :: ↗ pushover notification sent: {"status":1,"request":"e074862c-64dc-492d-a1f9-4d9104937b88"}
[3:43:05 PM] info :: ↗ email sent: 250 2.0.0 OK  1600720985 b11sm12643559pfd.33 - gsmtp
[3:43:06 PM] info :: ↗ sms sent: 250 2.0.0 OK  1600720985 j26sm13180943pfa.160 - gsmtp
[3:44:11 PM] info :: ↗ playing sound

**Comment by geman220** [comment]
Remove 

```
DISCORD_NOTIFY_GROUP="@here"
DISCORD_WEB_HOOK=""
```

Remove (or comment out with `#`) everything in `.env` you are not using.  If you didn't change it from the defaults or you don't know what it does, remove it or comment it out.

**Comment by djsupafly** [comment]
> Remove
> 
> ```
> DISCORD_NOTIFY_GROUP="@here"
> DISCORD_WEB_HOOK=""
> ```
> 
> Remove (or comment out with `#`) everything in `.env` you are not using. If you didn't change it from the defaults or you don't know what it does, remove it or comment it out.

I added the webhook on discord so I can get a notification out to my people.  Everything is working out perfect!  Thank you.  
I see you guys update the code a lot.  What is the easiest way to update it via terminal?  Just keep using git clone https://github.com/jef/nvidia-snatcher.git ?

**Comment by jef** [comment]
Run the following commands:

```
git pull origin main
npm install
npm run start
```

If you changed the code at all, this will most likely fail. You can clear out your changes by doing:

```
git checkout .
git pull origin main
npm install
npm run start
```

You can also to git-stash, but I won't talk about this here. You can look that one up on Google.

Glad everything is working!
