### ISSUE TITLE
Newegg.ca

### ISSUE THREAD

**Issue by xdMatthewbx** [jef/nvidia-snatcher#159]
Add newegg.ca to websites as it appears to have separate stock (correct me if I'm wrong).

**Comment by ultimateguy** [comment]
Seconded. I would add bestbuy.ca as well.

**Comment by geman220** [comment]
We are working on locale's now starting with Nvidia and then rolling to other sites after that.  Currently, we would have to create a new store .ts for every single locale (so newegg.com.ts newegg.ca.ts etc).  Locales will make it possible to define in `.env` and then have a single newegg.ts that modifies the URLS searched based on locale (as well as language for non-English stores).  This enhancement may not get addressed until that is implemented (but is in work now).  Not sure what @jef thinks about it though.

**Comment by geman220** [comment]
I just noticed you have PR #160 in so that could work as a stop-gap until locales are implemented
