### ISSUE TITLE
INFO: Could not find files for the given pattern(s).

### ISSUE THREAD

**Issue by scyto** [jef/nvidia-snatcher#166]
### Description
At startup i see  several of these info messages.

`INFO: Could not find files for the given pattern(s).`

Can these be ignored?
This is windows10, i used `winget install nodejs` to install.
I set my custom .env file.

### Possible solution

no idea :-) hopefully not relevant message

**Comment by g1forfun** [comment]
From what I have seen others saying, this has to do with the audio notification sound. Sorry I can't be more helpful.

**Comment by scyto** [comment]
thanks, good suggestion, i just set that in my env file to a real mp3 file - no change, so i guess more complex than just setting the mp3.  

I know a mac user who has this and doesn't see the issue.

**Comment by g1forfun** [comment]
> 
> 
> thanks, good suggestion, i just set that in my env file to a real mp3 file - no change, so i guess more complex than just setting the mp3.
> 
> I know a mac user who has this and doesn't see the issue.

Found the info.

Per the play-sound documentation:

https://github.com/shime/play-sound

players – List of available audio players to check. Default:
mplayer
afplay
mpg123
mpg321
play
omxplayer
aplay
cmdmp3

Windows (at least 10) doesn't ship with any of these by default. If installing mplayer solves @chuakc92's issue, then looks like we'll need to find some sort of simpler solution for this.

**Comment by scyto** [comment]
closing as dupe of https://github.com/jef/nvidia-snatcher/issues/116 (folks should consider renaming that issue)

**Comment by scyto** [comment]
@g1forfun i think i may have found a solution, but not sure https://github.com/jef/nvidia-snatcher/issues/116#issuecomment-696259379 

it only removed one of the 8 error lines, but I am hoping that means it found the player and will use it.

**Comment by scyto** [comment]
https://github.com/jef/nvidia-snatcher/issues/116#issuecomment-696288561 - better fix
