### ISSUE TITLE
Notification for Captcha warning

### ISSUE THREAD

**Issue by soomld** [jef/nvidia-snatcher#170]
![image](https://user-images.githubusercontent.com/45433974/93807437-7a946800-fbff-11ea-848a-ce2213e70e0b.png)

I realised from my logs that newegg was prompting for captcha around 4am, does that mean there was stock? Is it possible to have a notification for captcha warning too. 

Thanks!

**Comment by geman220** [comment]
The warning you see is the warning that there was a CAPTCHA.  It doesn't mean there was stock, it means when you made a request newegg predicted you were a bot (which you were) and presented you with a CAPTCHA.
