### ISSUE TITLE
feat-last in stock

### ISSUE THREAD

**Issue by aitaDev** [jef/nvidia-snatcher#175]
### Description
Tracking when items were last in stock or logging every time we see an item in stock. This will allow us to get a feel for how often stores refill after being sold out. Although this would not work for multi seller stores like amazon it will definitely help with every other store. 

### Possible solution

Send data to a log file locally or submit data to a db or your choice.

**Comment by aitaDev** [comment]
little more to this^ although right now it may not seem useful, collecting this data will help once supply stabilizes a bit.

**Comment by geman220** [comment]
I believe this functional already exists.  There are several alert methods all of which have timestamps of when a successful detection is made (email, text, pushover, slack, discord, etc).  Even if we output to a text file specifically, you would still have to merge that data into a database anyway.

**Comment by geman220** [comment]
Closing this feel free to ask for help in the #help channel in discord.
