### ISSUE TITLE
Did not receive bestbuy notifications

### ISSUE THREAD

**Issue by chuakc92** [jef/nvidia-snatcher#190]
So I found out that apparently, best buy restocked a few times today. Is there a reason why I did not receive any notifications?

All I received today were the EVGA restock and false positives from banh.

```
EMAIL_USERNAME="email@email.com"
EMAIL_PASSWORD="password"
HEADLESS="true"
LOG_LEVEL="info"
NOTIFICATION_TEST="false"
OPEN_BROWSER="true"
PAGE_TIMEOUT="30000"
PHONE_NUMBER="##########"
PHONE_CARRIER="verizon"
PLAY_SOUND="notification.mp3"
PUSHOVER_TOKEN="token"
PUSHOVER_USER="user"
RATE_LIMIT_TIMEOUT="5000"
SHOW_ONLY_BRANDS=""
STORES="evga,nvidia,newegg,bandh,asus,amazon,bestbuy,adorama,officedepot"
SCREENSHOT="true"
```

**Comment by jef** [comment]
Probably didn't see them due to so many people going to them. We'll find that being the case quite often as we are still within a week of launch and cards not stocked regularly.
