### ISSUE TITLE
catch on page timeout error to auto restart app

### ISSUE THREAD

**Issue by IonCaza** [jef/nvidia-snatcher#20]
### Description

On page timeouts, the application crashes with an unhandled exception for the promise that doesn't get resolved because the page times out. Need to catch this so the app doesn't crash.

### Possible solution

I'm not the brains, you are :D

**Comment by masseyboy1990** [comment]
I have noticed the same error. It appears to happen when refreshing bestbuy, though that may be a coincidence. I removed bandh and bestbuy from .env and haven't encountered the error so far.

info ::  [nvidia] nvidia founders edition is still out of stock
info ::  [nvidia] nvidia founders edition is still out of stock
info ::  [bandh] gigabyte black is still out of stock
info ::  [bestbuy] nvidia founder edition is still out of stock
info ::  [bestbuy] gigabyte black is still out of stock
info :: — trying stores again
info ::  [nvidia] nvidia founders edition is still out of stock
info ::  [bandh] gigabyte black is still out of stock
info ::  [nvidia] nvidia founders edition is still out of stock
info ::  [bestbuy] nvidia founder edition is still out of stock
info ::  [bestbuy] gigabyte black is still out of stock
info :: — trying stores again
info ::  [nvidia] nvidia founders edition is still out of stock
info ::  [nvidia] nvidia founders edition is still out of stock
info ::  [bandh] gigabyte black is still out of stock
(node:2108) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\Users\username\nvidia-snatcher\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:106:111
(node:2108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jef** [comment]
Yep... Getting this too. I will fix.

**Comment by coopermor** [comment]
Still getting this on commit feed4ed
````bash
info :: ↗ trying stores again
(node:27732) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r800071 is guaranteed to work.
    at Timeout.onTimeout (/home/cooper/nvidia-snatcher/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:204:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by jef** [comment]
Damn. Okay, I'll go through again and see what's happening. I haven't had any problems since https://github.com/jef/nvidia-snatcher/commit/00a0687d3eba6a8fca871161b447529be00c8896. I'll look into it.

Granted it should be a lot better of exception handling.

**Comment by jef** [comment]
Should be fixed now. Closing.
