### ISSUE TITLE
B&H False Positive

### ISSUE THREAD

**Issue by g1forfun** [jef/nvidia-snatcher#200]
### Description

Got notified three times and then stopped the script. This was for stock at B&H for this link https://www.bhphotovideo.com/c/product/1593649-REG/asus_tuf_rtx3080_10g_gaming_tuf_gaming_geforce_rtx.html
![success-1600777418836](https://user-images.githubusercontent.com/2007992/93881703-41b2cc80-fcad-11ea-910f-6a7100274442.png)
![success-1600777432300](https://user-images.githubusercontent.com/2007992/93881705-424b6300-fcad-11ea-976a-2c60f5872ed4.png)
![success-1600777458387](https://user-images.githubusercontent.com/2007992/93881707-437c9000-fcad-11ea-8a85-4ea9d1ce5d47.png)

**Comment by jef** [comment]
They're trolling us.

**Comment by bmalaski** [comment]
pr #201 should address this

**Comment by likwidsage** [comment]
Wouldn't it be better to detect "The page you longer..." text and skip over it incase they bring it back and manually editing the files?

**Comment by bmalaski** [comment]
it sends a redirect, so in theory the better path may be to fail on redirects

**Comment by likwidsage** [comment]
> it sends a redirect, so in theory the better path may be to fail on redirects

I'm not fully aware of the capabilities of puppeteer. If capable, definitely the best way to go about it.
