### ISSUE TITLE
Please add handling for newegg error page

### ISSUE THREAD

**Issue by freejack** [jef/nvidia-snatcher#208]
![success-1600790629161](https://user-images.githubusercontent.com/982085/93907968-0bd11080-fccc-11ea-89cf-ad7da948af00.png)

**Comment by freejack** [comment]
Added matching strings to
`outOfStock: ['auto notify', 'item is currently out of stock', 'We are truly sorry']`
but it still flags as in stock.  Any idea?

**Comment by freejack** [comment]
Newegg's been loading erroring out frequently and is causing an inordinate amount of false positives.  Hopefully this can be addressed soon.  Thanks.

**Comment by geman220** [comment]
#207 has a fix for this

**Comment by jef** [comment]
Closed in latest commits 136ccf3593b358229ea43c68da482ab66500a5cc 9d666835283510a5a0c0972627c5c6d180a854b3. Sorry @geman220, didn't see you had that there as well.
