### ISSUE TITLE
Store/cart login is not working for sub-region items (SKU)

### ISSUE THREAD

**Issue by Coldi7** [jef/nvidia-snatcher#217]
SKU:s that are related to certain sub-regions are not working properly. For example Finland/Denmark SKU is under en-gb, but cant be purchased from en-gb shop. Shopping cart is differently set up and separated for FI & DN. 

FI "Store" to add cart: https://www.nvidia.com/fi-fi/geforce/graphics-cards/30-series/rtx-3080/#wtb

Cant login here when registered via sub-region site:
https://store.nvidia.com/store?Action=DisplayPage&Env=BASE&Locale=en_GB&SiteID=nvidia&id=QuickBuyCartPage

This kind of shop storefront not available in sub regions:
https://www.nvidia.com/en-gb/shop/geforce/?page=1&limit=9&locale=en-gb

I would assume that the generated link when in stock will lead to incorrect web page. I believe this same applies on all of those sub-region countries, where the distribution center located in other country.

Any thoughts?

**Comment by jef** [comment]
Closing as `bestbuy` is now the retailer for `nvidia`.
