### ISSUE TITLE
Can not get gmail to work, thus breaking notifications

### ISSUE THREAD

**Issue by shinfo44** [jef/nvidia-snatcher#219]
### Description

Hello,

I apologize because I am not very code-savvy.

I am entering my gmail password and email correctly, but Google keeps blocking the bot from having access to my email. I approved the log-in, but it still does not work correctly.

I keep getting the following error when testing:

```
[5:40:35 PM] error :: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 17sm950114oth.70 - gsmtp
[5:40:35 PM] error :: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials w12sm8423824oow.22 - gsmtp
```

I do not have MAP turned on.

Any advice would be great.

**Comment by geman220** [comment]
Are you using 2FA on your gmail account?

**Comment by shinfo44** [comment]
> 
> 
> Are you using 2FA on your gmail account?

Nope/

**Comment by geman220** [comment]
Are you positive your email and password are right?

```
EMAIL_USERNAME="myemail@gmail.com"
EMAIL_PASSWORD="mypassword"
```

Both of them are in quotes?  This functionality works, so it's on your end.

**Comment by shinfo44** [comment]
> 
> 
> Are you positive your email and password are right?
> 
> ```
> EMAIL_USERNAME="myemail@gmail.com"
> EMAIL_PASSWORD="mypassword"
> ```
> 
> Both of them are in quotes? This functionality works, so it's on your end.

Extremely positive.

**Comment by shinfo44** [comment]
> 
> 
> Are you positive your email and password are right?
> 
> ```
> EMAIL_USERNAME="myemail@gmail.com"
> EMAIL_PASSWORD="mypassword"
> ```
> 
> Both of them are in quotes? This functionality works, so it's on your end.

Believe me, I wouldn't be posting if it was that simple. I am just at a loss. Like I said, Google was blocking it, but once I whitelisted it, nothing happened still.

**Comment by geman220** [comment]
Try making a throwaway Gmail.  The problem isn't within the Gmail function.  If Google blocked it at some point I would check to make sure it's not automatically blocking attempts or something.

**Comment by shinfo44** [comment]
> 
> 
> Try making a throwaway Gmail. The problem isn't within the Gmail function. If Google blocked it at some point I would check to make sure it's not automatically blocking attempts or something.

Tried that too.

**Comment by shinfo44** [comment]
> 
> 
> Try making a throwaway Gmail. The problem isn't within the Gmail function. If Google blocked it at some point I would check to make sure it's not automatically blocking attempts or something.

Clearly there is something I am missing at some point, but I have whitelisted it both on my main and throwaway account. Still nothing.

**Comment by jef** [comment]
Definitely something on your end then.

Whats your OS and can you take a screenshot of your directory with all the files in it?

**Comment by shinfo44** [comment]
> 
> 
> Definitely something on your end then.
> 
> Whats your OS and can you take a screenshot of your directory with all the files in it?

Windows 10 NT 10.0

![GitHub](https://user-images.githubusercontent.com/71736136/93946535-22448f80-fcff-11ea-91b4-17d2bc0e8c97.JPG)

**Comment by shinfo44** [comment]
Here is this as well, just to prove I am not going crazy... I think...

![Capture](https://user-images.githubusercontent.com/71736136/93946992-4654a080-fd00-11ea-8e84-a8e3edd5f6d5.JPG)

**Comment by shinfo44** [comment]
Sorry, just one more:

![Capture 2](https://user-images.githubusercontent.com/71736136/93947374-25407f80-fd01-11ea-85c7-bdce533af6c2.JPG)

**Comment by geman220** [comment]
Can you paste your `.env` minus your private information

**Comment by shinfo44** [comment]
> 
> 
> Can you paste your `.env` minus your private information

`#DISCORD_NOTIFY_GROUP="@here"
#DISCORD_WEB_HOOK="https://discordapp.com/api/webhooks/23123123123/5dfsdfh3h2j5hdfhsdfsdhj55jf"
EMAIL_USERNAME="XXXXXXXXXXX@gmail.com"
EMAIL_PASSWORD="XXXXXXXXXXXXXX"
HEADLESS="true"
IN_STOCK_WAIT_TIME="30"
LOG_LEVEL="info"
OPEN_BROWSER="true"
PAGE_TIMEOUT="30000"
PHONE_NUMBER="15134035152"
PHONE_CARRIER="verizon"
#PLAY_SOUND="false.mp3"
#PUSHOVER_TOKEN="123pushover-token456"
#PUSHOVER_USER="123pushover-user-key"
PAGE_SLEEP_MIN="5000"
PAGE_SLEEP_MAX="10000"
SHOW_ONLY_BRANDS="evga"
SHOW_ONLY_SERIES="3080"
#SLACK_CHANNEL="SlackChannelName"
#SLACK_TOKEN="slack-token"
STORES="amazon,bestbuy,bandh,nvidia,evga,microcenter,newegg"
COUNTRY="usa"
SCREENSHOT="true"
#TELEGRAM_ACCESS_TOKEN=""
#TELEGRAM_CHAT_ID="1234"
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"`

**Comment by shinfo44** [comment]
The only other thing I can think of is that I have 2 PiHoles running off of my Unraid server. But that wouldn't have anything to do with it, would it?

**Comment by geman220** [comment]
I think PiHole is inbound isn't it?  You could try using the PiHole admin page to disable temporarily and see if that resolves it.  I'm also assuming you aren't running headless so you can disable `HEADLESS="true"` as well.

**Comment by jef** [comment]
I mean you're not lacking the information here... I also don't know if commenting works in `.env` files. Could be very wrong. Shouldn't have to do anything with it though.

As for the PiHole, that's out of my scope. I wouldn't imagine it being a problem though.

**Comment by jjeitler** [comment]
I was having the same problem until I found the actual setting to allow less secure apps.  Try this:

https://www.google.com/settings/security/lesssecureapps

**Comment by shinfo44** [comment]
> 
> 
> I was having the same problem until I found the actual setting to allow less secure apps. Try this:
> 
> https://www.google.com/settings/security/lesssecureapps

BOOM! Nailed it. You the man!

**Comment by shinfo44** [comment]
Solved!

**Comment by Sharpfish-zz** [comment]
> I was having the same problem until I found the actual setting to allow less secure apps. Try this:
> 
> https://www.google.com/settings/security/lesssecureapps

Thanks, I had same problem and this fixed it.

**Comment by jef** [comment]
Do not set your account to less secure. Use the app password.
