### ISSUE TITLE
error after card is found and notification is sent

### ISSUE THREAD

**Issue by gahmee** [jef/nvidia-snatcher#222]
![Image 9-22-20 at 4 40 PM](https://user-images.githubusercontent.com/69001161/93949694-87e44c00-fcfe-11ea-9f75-6cebb310d0a5.JPG)

after a card is found and a notification is sent i get an error and stops the scanner

**Comment by geman220** [comment]
Are you using pushover notifications?

**Comment by gahmee** [comment]
> 
> 
> Are you using pushover notifications?

i am not

**Comment by geman220** [comment]
can you post your `.env`?

**Comment by gahmee** [comment]
> can you post your `.env`?

DISCORD_NOTIFY_GROUP="@Gahmee"
DISCORD_WEB_HOOK="https://discordapp.com/api/webhooks/757752257440776343/-fZf0l0yHq6RvKj_xkRtpwqmDLmM4xgsKL7LzZwpqsG1uQpTPBEhmhD2bQcFgWTlzGB7"
EMAIL_USERNAME="0"
EMAIL_PASSWORD=""
HEADLESS="true"
IN_STOCK_WAIT_TIME="0"
LOG_LEVEL="info"
OPEN_BROWSER="false"
PAGE_TIMEOUT="30000"
PHONE_NUMBER="1234567890"
PHONE_CARRIER="tmobile"
PLAY_SOUND=""
PUSHOVER_TOKEN="123pushover-token456"
PUSHOVER_USER="123pushover-user-key"
PAGE_SLEEP_MIN="5000"
PAGE_SLEEP_MAX="10000"
SHOW_ONLY_BRANDS="evga,asus,nvidia,msi,gigabyte"
SHOW_ONLY_SERIES="3080"
SLACK_CHANNEL="SlackChannelName"
SLACK_TOKEN="slack-token"
STORES="bestbuy,nvidia,newegg,amazon,"
SCREENSHOT="true"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID="1234"
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

**Comment by gahmee** [comment]
I have solved the problem by changing PUSHOVER_TOKEN and PUSHOVER_USER to blank. ("")

**Comment by geman220** [comment]
great
