### ISSUE TITLE
inventory found, but does not open browser

### ISSUE THREAD

**Issue by Toiletduck34** [jef/nvidia-snatcher#223]
I am getting hits on some "available" cards. Positive or not it is not opening a browser to that item to check out. I am also getting an error for the Notification but this is on my 3rd monitor so i can always see it running. 

HEADLESS="true"
IN_STOCK_WAIT_TIME="15"
LOG_LEVEL="info"
OPEN_BROWSER="true"
PAGE_TIMEOUT="30000"
PHONE_NUMBER=""
PHONE_CARRIER=""
PLAY_SOUND="notification.mp3"
PUSHOVER_TOKEN="123pushover-token456"
PUSHOVER_USER="123pushover-user-key"
PAGE_SLEEP_MIN="5000"
PAGE_SLEEP_MAX="10000"
SHOW_ONLY_BRANDS="evga,nvidia,msi"
SHOW_ONLY_SERIES="3080"
SLACK_CHANNEL="SlackChannelName"
SLACK_TOKEN="slack-token"
STORES="evga,bestbuy,newegg"
COUNTRY="usa"
SCREENSHOT="true"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID="1234"
USER_AGENT="Chrome/78.0.3904.10"

**Comment by geman220** [comment]
Remove the line `HEADLESS="true"` since I'm asuming you aren't running this headless.

**Comment by Toiletduck34** [comment]
I would like to keep it headless for at least it searching. but open once item is found.

**Comment by geman220** [comment]
Sorry I was confusing something else.  The default is true anyway.  Jumping between several things.  What OS?

**Comment by Toiletduck34** [comment]
Windows 10, running chrome

**Comment by jef** [comment]
`USER_AGENT="Chrome/78.0.3904.10"` Not sure if this is gonna goof something up, but I doubt this is your user agent.

https://www.google.com/search?q=whats+my+user+agent&oq=whats+my+user+agent&aqs=chrome..69i57j0l7.1709j0j7&sourceid=chrome&ie=UTF-8

**Comment by Toiletduck34** [comment]
Thanks, I did remove stuff thinking that could be effecting it, I will add.

**Comment by geman220** [comment]
I would start with the most limited amount of variables in your `.env` and work up from there.

**Comment by geman220** [comment]
Were you able to resolve?

**Comment by geman220** [comment]
closing, reopen or ask for #help in discord if you still need help
