### ISSUE TITLE
Add CDW as a site to check

### ISSUE THREAD

**Issue by dyndragon** [jef/nvidia-snatcher#225]
### Description

CDW has 3080s available, but on backorder. However, when they have stock, their status does update to "ships to 0-2 days".
https://www.cdw.com/search/?key=rtx+3080

### Possible solution

Add a store script to parse CDW sites.

**Comment by jef** [comment]
These are back ordered and won't be fulfilled anytime soon. The bot is specific for non pre-orders.

Thanks for the report though!
