### ISSUE TITLE
Newegg can load without an Add to Cart button, resulting in a false positive

### ISSUE THREAD

**Issue by IllinoisBois** [jef/nvidia-snatcher#227]
### Description

Newegg loads all the time without an Add to Cart button, but nothing indicating that it's out of stock. This results in a false positive.

### Possible solution

Check the website for an add to cart button.

**Comment by geman220** [comment]
Can you post the positive detection image

**Comment by IllinoisBois** [comment]
https://i.imgur.com/eoNjkjO.png

You shouldn't need the image. There's nothing here I can filter out. We need an inverse filter that checks to see if 'add to cart' is on the page.

Again, the current filter will not work for this issue.

**Comment by liuqiaoyi** [comment]
![Screenshot 2020-09-22 194039](https://user-images.githubusercontent.com/28788133/93958528-8b320480-fd0b-11ea-8891-ddcc1711e290.png)

**Comment by liuqiaoyi** [comment]
also getting false positive

**Comment by geman220** [comment]
I have a ton of new awesome false positive detections in my PR.

**Comment by IllinoisBois** [comment]
I ran your PR and it did not fix the issue

**Comment by jef** [comment]
> We need an inverse filter that checks to see if 'add to cart' is on the page.

This is on latest `main` now.

**Comment by jef** [comment]
Pull that down and run. Let me know if its still and issue. Feel free to close otherwise.

Thanks!

**Comment by IllinoisBois** [comment]
looks like it has been fixed
