### ISSUE TITLE
Newegg error with evga xc3 ultra

### ISSUE THREAD

**Issue by benhwebster** [jef/nvidia-snatcher#230]
### Description

```
[11:02:31 PM] info :: ��� [newegg] evga xc3 ultra 3080 IN STOCK ���
[11:02:31 PM] info :: https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3885-kr/p/N82E16814487520
```
seems to be an error, don't know if this will be temporary or if we should get a filter made for it, perhaps the product page is moving?

https://i.imgur.com/prQ8EVL.png
### Possible solution

add new out of stock label

`'sorry, we can\'t find this item. please check your item#'`

**Comment by ethanspitz** [comment]
Funny you mention this, I got this: 
![image](https://user-images.githubusercontent.com/3741092/93962989-e1ee0d00-fd10-11ea-9806-5271402eba87.png)

**Comment by geman220** [comment]
#207 has more logic for newegg

**Comment by ethanspitz** [comment]
@geman220 I don't think that will fix the issue above where it gets added to cart for $0

**Comment by benhwebster** [comment]
@ethanspitz Yeah thats what shows on the add to cart page opened by the bot, but the screenshot is the image taken by the bot, I added that label to my local copy and its suppressed the false positives for now.

@geman220 Yeah I think you'll need another label for this error, the one I added in this issue solved it for me.

**Comment by benhwebster** [comment]
Ah wait, I think that PR should cover it with the `perhaps we can get you started in one of these areas`.

**Comment by ethanspitz** [comment]
Actually, I take it back, the screenshot taken is this: 
![image](https://user-images.githubusercontent.com/3741092/93963830-00550800-fd13-11ea-80af-a894133db3ef.png)
And I think that's covered by @geman220

**Comment by qazikm** [comment]
> Actually, I take it back, the screenshot taken is this:
> ![image](https://user-images.githubusercontent.com/3741092/93963830-00550800-fd13-11ea-80af-a894133db3ef.png)
> And I think that's covered by @geman220

I am getting the screenshot of your first post still.

**Comment by ethanspitz** [comment]
> > Actually, I take it back, the screenshot taken is this:
> > ![image](https://user-images.githubusercontent.com/3741092/93963830-00550800-fd13-11ea-80af-a894133db3ef.png)
> > And I think that's covered by @geman220
> 
> I am getting the screenshot of your first post still.

My first post shows what you get when you click on the link that it sends. The screenshot here shows the screenshot the bot took to "prove" the card was "in stock"

**Comment by geman220** [comment]
Invert logic was implemented should stop these

**Comment by ethanspitz** [comment]
> Invert logic was implemented should stop these

Confirmed
