### ISSUE TITLE
Adorama False Positives

### ISSUE THREAD

**Issue by ScottyYDG** [jef/nvidia-snatcher#235]
### Description
In the long standing tradition of constantly updating EVGA, Newegg, and Amazon to ensure we don't get spammed with False Positives, an error message on Adorama.com is triggering something similar. Below will by a gyazo screenshot of the error, and it can be easily added to the list of blacklisted text in the filer. 

https://gyazo.com/685290a5c08de225c2cb3396772dde3f

**Comment by admon84** [comment]
False positives should be solved by https://github.com/jef/nvidia-snatcher/pull/141, are you up-to-date with the latest changes?
