### ISSUE TITLE
Newegg false positive

### ISSUE THREAD

**Issue by gahmee** [jef/nvidia-snatcher#238]
![Image 9-23-20 at 6 13 AM](https://user-images.githubusercontent.com/69001161/94011053-06bfa000-fd64-11ea-8238-7e22c47cb53d.JPG)

every few minutes nvidia snatcher is giving out false positives for the 10g-p5-3885-kr model
mac os

**Comment by SethWoody** [comment]
![success-1600864651359](https://user-images.githubusercontent.com/16491577/94013456-1943d480-fd78-11ea-9141-af9fc490e1f7.png)

Same false positive here. This is the screenshot that is saved.

**Comment by Pacoboyd** [comment]
Same issue, product url doesn't exist, I just removed it from my newegg.js for the time being.

**Comment by smithers54** [comment]
I removed it from newegg.js, but it get's auto added back. How do I keep that from happening?

**Comment by SethWoody** [comment]
Remove from newegg.ts
src > store > model >newegg.ts

**Comment by jcp3alex** [comment]
FYI- They moved the product page to https://www.newegg.com/evga-geforce-rtx-3090-24g-p5-3975-kr/p/N82E16814487524?Description=xc3%20ultra&cm_re=xc3_ultra-_-14-487-524-_-Product

**Comment by admon84** [comment]
False positives should be solved by https://github.com/jef/nvidia-snatcher/pull/141, are you up-to-date with the latest changes?

**Comment by gahmee** [comment]
> False positives should be solved by https://github.com/jef/nvidia-snatcher/pull/141, are you up-to-date with the latest changes?

I've updated and it seems to be working so far. Thanks!

**Comment by geman220** [comment]
Closing as resolved.
