### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by zerocarbthirty** [jef/nvidia-snatcher#240]
### Description
Reduce CPU usage of chrome processes

### Possible solution

Not exactly sure, I just noticed on a 24 core system Chrome uses a ton of CPU when being used by nvidia-snatcher:

%Cpu0  : 33.4 us,  2.4 sy,  0.0 ni, 63.5 id,  0.0 wa,  0.0 hi,  0.3 si,  0.3 st
%Cpu1  : 79.4 us,  2.6 sy,  0.0 ni, 15.7 id,  0.0 wa,  0.0 hi,  0.0 si,  2.3 st
%Cpu2  : 17.8 us,  8.4 sy,  0.0 ni, 72.7 id,  0.0 wa,  0.0 hi,  0.0 si,  1.0 st
%Cpu3  : 22.3 us,  2.7 sy,  0.0 ni, 74.0 id,  0.0 wa,  0.0 hi,  0.0 si,  1.0 st
%Cpu4  : 18.1 us,  3.7 sy,  0.3 ni, 77.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.7 st
%Cpu5  : 14.9 us,  4.3 sy,  0.0 ni, 80.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.7 st
%Cpu6  : 24.9 us, 10.0 sy,  0.0 ni, 63.5 id,  0.3 wa,  0.0 hi,  0.3 si,  1.0 st
%Cpu7  : 68.4 us, 19.2 sy,  0.0 ni,  4.3 id,  0.0 wa,  0.0 hi,  0.0 si,  8.0 st
%Cpu8  : 14.2 us,  5.3 sy,  0.7 ni, 78.5 id,  0.0 wa,  0.0 hi,  0.0 si,  1.3 st
%Cpu9  : 24.4 us,  4.7 sy,  0.3 ni, 67.9 id,  0.0 wa,  0.0 hi,  1.0 si,  1.7 st
%Cpu10 : 24.7 us,  9.1 sy,  0.0 ni, 62.7 id,  0.0 wa,  0.0 hi,  0.6 si,  2.9 st
%Cpu11 : 39.9 us, 11.1 sy,  0.0 ni, 47.7 id,  0.0 wa,  0.0 hi,  0.0 si,  1.3 st
%Cpu12 : 40.2 us,  5.2 sy,  0.3 ni, 52.9 id,  0.0 wa,  0.0 hi,  0.0 si,  1.3 st
%Cpu13 : 17.4 us,  5.6 sy,  0.0 ni, 75.3 id,  0.0 wa,  0.0 hi,  0.7 si,  1.0 st
%Cpu14 : 51.7 us,  9.4 sy,  0.0 ni, 37.9 id,  0.0 wa,  0.0 hi,  0.0 si,  1.0 st
%Cpu15 : 28.8 us,  5.0 sy,  0.0 ni, 63.9 id,  0.0 wa,  0.0 hi,  0.7 si,  1.7 st
%Cpu16 :  6.6 us,  2.0 sy,  0.0 ni, 91.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.3 st
%Cpu17 : 27.2 us,  3.4 sy,  0.0 ni, 68.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.7 st
%Cpu18 : 17.8 us,  6.1 sy,  0.0 ni, 74.4 id,  0.0 wa,  0.0 hi,  0.7 si,  1.0 st
%Cpu19 : 32.8 us, 10.9 sy,  0.0 ni, 54.3 id,  0.0 wa,  0.0 hi,  0.3 si,  1.7 st
%Cpu20 : 16.3 us, 16.9 sy,  0.0 ni, 65.4 id,  0.3 wa,  0.0 hi,  0.0 si,  1.0 st
%Cpu21 : 27.5 us,  3.0 sy,  0.0 ni, 67.2 id,  0.3 wa,  0.0 hi,  1.7 si,  0.3 st
%Cpu22 : 24.5 us,  6.0 sy,  0.0 ni, 68.5 id,  0.0 wa,  0.0 hi,  0.0 si,  1.0 st
%Cpu23 : 12.8 us,  3.0 sy,  0.0 ni, 82.8 id,  0.0 wa,  0.0 hi,  0.3 si,  1.0 st
MiB Mem :   3931.6 total,    267.1 free,   1143.4 used,   2521.2 buff/cache
MiB Swap:   8192.0 total,   8191.0 free,      1.0 used.   2523.4 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                   
  31097 user      20   0  568936 152216  85408 R 279.2   3.8  14:35.12 chrome                                                                                                                                    
  39222 user      20   0 8941868 161068  82924 S  95.7   4.0   0:15.12 chrome                                                                                                                                    
  39458 user      20   0 4771272 221936 121572 S  74.6   5.5   0:07.37 chrome                                                                                                                                    
  39402 user      20   0 4744240 208996 103296 R  63.7   5.2   0:08.44 chrome                                                                                                                                    
  39553 user      20   0 4652708 140484  96116 S  62.4   3.5   0:02.01 chrome                                                                                                                                    
  39577 user      20   0 8840324 125924  88396 R  57.1   3.1   0:01.73 chrome                                                                                                                                    
  39598 user      20   0 4620768 135472  95396 R  46.2   3.4   0:01.40 chrome                                                                                                                                    
  39516 user      20   0 4727828 183772 108712 S  42.9   4.6   0:04.00 chrome                                                                                                                                    
  31119 user      20   0  788860 220316  78116 S  28.7   5.5   1:38.47 chrome                                                                                                                                    
           
If this is known/intentional that's cool but I just wanted to ask.

**Comment by jef** [comment]
I think this would be hard to change as Chromium is a huge resource hog... We'd have to move away from utilizing Chromium (even headless).

**Comment by geman220** [comment]
Unless we decide to totally move out of Chromium I don't see this as being fixed.  It does use a decent amount of CPU but it's also making a lot of requests very often.  It should still be stable and functional for use though and shouldn't completely peg a relatively recent CPU.

**Comment by jef** [comment]
This could help now: https://github.com/jef/nvidia-snatcher/pull/294
