### ISSUE TITLE
EVGA site false positives

### ISSUE THREAD

**Issue by mizled** [jef/nvidia-snatcher#243]
I get a lot of false positives on the EVGA site when the page fails to load. Its either "Oops! Something broke." or "Error reaching the EVGA website". Is there a way you can add exceptions for these?

![success-1600881557790](https://user-images.githubusercontent.com/3859982/94047345-f9c0a200-fd9f-11ea-93f3-a07e11f154b1.png)

![success-1600825296201](https://user-images.githubusercontent.com/3859982/94047584-4906d280-fda0-11ea-823b-7d3639abecef.png)

**Comment by jef** [comment]
Latest fixes this.
