### ISSUE TITLE
Ignoring 3rd party sellers on Amazon and Newegg

### ISSUE THREAD

**Issue by serg06** [jef/nvidia-snatcher#244]
### Description

Occasionally Amazon and Newegg have 3rd party sellers selling their products at exorbitant prices. For example, the [Asus TUF 3080 on Amazon.ca](https://www.amazon.ca/dp/B08HHDP9DW) is going for $1,900 CAD. You can tell it's a 3rd party because it says "Ships from Canada and sold by **Deals2You**." instead of "Fulfilled by amazon" or w/e.

I don't want Snatcher to alert me when it's a 3rd-party seller.

### Possible solution

Amazon and Amazon.ca: Change inStock labels to search for "sold and fulfilled by amazon"?

Newegg and Newegg.ca: Similar solution?

**Comment by jef** [comment]
We solved this before we inverted the logic, so we should definitely get this figured out!

**Comment by wedge22** [comment]
I was going to ask for the same enhancement as I have received alerts for both amazon-ca and newegg-ca this morning and they were both from resellers. Is it possible to add a variable for the price of the units, therefore ignoring any above a certain price which should eliminate the resellers/scalpers?

**Comment by MrRobot245** [comment]
+1 to this, Newegg and Amazon CA both have "in stocker" reseller cards going for $2000+ right now. A price filter would be a good feature too.

**Comment by chineeboy** [comment]
I opened a separate issue/enhancement request right here concerning price ranges: https://github.com/jef/nvidia-snatcher/issues/310#issue-709059976

**Comment by xninjax** [comment]
For newegg-ca, I have been able to filter only "Sold By Newegg" cards by add the following:
                    
`container: ".shipped-by-newegg",
			text: ["Shipped by Newegg"]`

My coding is too much of a hack right now (threw it together on the side while doing my actual day job) to do a pull... but hopefully this helps get us in the right direction...

**Comment by geman220** [comment]
`bannedSeller` has been added see #270

**Comment by zkghost** [comment]
it'd be nice if this could still be a flag to flip, i don't want to go and find all the 3rd party sellers names to add their banned labels. whereas I know I just want the official sellers "amazon/newegg"

**Comment by Stlotmachinemaster** [comment]
I paid $271.90 for a defective product from (Deals2You) on Amazon and immediately ask for a RMA the seller (Deals2You) won't pay for return shipping WTH, Now I pay extra FOR returning and (Deals2You) doesn't care. I got refunded $267.82 total and it cost me about $300. I will never purchase from (Deals2You) again and I strongly suggest YOU don't either. I guess Amazon doesn't care who sells on their site. I haven't even gotten started writing reviews on this (Bad Service from Deals2You) STAY AWAY
