### ISSUE TITLE
Problem setting up env

### ISSUE THREAD

**Issue by nolongerhuman4544** [jef/nvidia-snatcher#247]
### Description

i am not very savvy but it seems to only be checking Bestbuy over and over again and i do not understand how to customize the .env to search through more stores. Im such noob

**Comment by jef** [comment]
https://github.com/jef/nvidia-snatcher/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+env

Maybe ask from folks on `#help` in [![discord](https://img.shields.io/discord/756303724095471617.svg?label=&logo=discord&logoColor=ffffff&color=7389D8&labelColor=6A7EC2)](https://discord.gg/Cyc7nrz)
