### ISSUE TITLE
"Login" link doesn't do anything

### ISSUE THREAD

**Issue by tsumeone** [jef/nvidia-snatcher#250]
### Description

When starting the script, it opens a plain looking nVidia store page in my default browser with a "Login" link.  The console prints:  "info :: ℹ opening browser for user to login".  However, the "Login" link on the opened page doesn't actually do anything.  I've tried in a couple different browsers now.  Are the instructions unclear, or is there some problem on my end?  Country is "usa"

**Comment by karlito1978** [comment]
Hi, firstly thank you for the hard work on this project (my first post). Just want to add, I'm having same issue here in the UK.. According to a closed post. It seems you need to log in for the bot to obtain your detsils, or did I read that incorrectly?

**Comment by geman220** [comment]
I don't understand what you mean by the "Login" link doesn't do anything.

Are you talking about [this page?](https://i.imgur.com/QZJe6YD.png)

You need an nvidia store account **not a geforce now account** they are two completely different accounts.

**Comment by tsumeone** [comment]
When the script says this:  https://i.imgur.com/nK8YiGd.png

It opens this page:  https://i.imgur.com/XlKMWKg.png

The "Login" button there does nothing.  I've tried in Firefox and Chrome.  I'm not sure if the instructions are unclear (does it mean I should open a separate tab, navigate to the nvidia store, and login there?) or if there is some kind of issue on my end.

**Comment by karlito1978** [comment]
For me, when it loads the nvidia shopping cart and then I click on the login icon, at the rtop ight conner, then type in my email address and password, my emai is not recognisedl. If was log into the shop, from main nvidia website, then there's no problem. I hope that helps

**Comment by tsumeone** [comment]
I figured it out (my issue anyway).  Privacy settings on both browsers were messing it up.

For karlito I'm pretty sure you have to place an order in order to create an account.

**Comment by karlito1978** [comment]
A little confused, as I already got an account, am able to log in from the normal shop page. At geman220, I ust noticed yes its that page for me..

**Comment by tsumeone** [comment]
karltio can you add a screenshot of the "normal shop page" you're referring to including the URL?

If the URL is not **store**.nvidia.com then it's not actually the DR shop page even if it's the page where you can add stuff to your cart.  It's confusing.

**Comment by karlito1978** [comment]
Mind you it's been two years, since I purchased a shield, under my nvidia shop account.. 🤔

**Comment by karlito1978** [comment]
I dont know if is being worked on at mo, thou now it not open the cart page

**Comment by karlito1978** [comment]
[22:37:09] error :: ✖ [nvidia] cannot generate cart/session token, continuing without; auto "add to cart" may not work Unexpected token < in JSON at position 10

**Comment by tsumeone** [comment]
That's a different issue that just started (likely #254 )

**Comment by karlito1978** [comment]
Yeah i didn't get before, i was able to launch the cart page

**Comment by karlito1978** [comment]
yeah your probably right

**Comment by karlito1978** [comment]
Even thou now its not opening the page, I've taken from history and manged to show the issue I originally had.. https://imgur.com/6mEX5sn

**Comment by geman220** [comment]
It's sot of irrelevant at the moment because nvidia isn't going to work until the logic is resolved in `nvidia.ts`

**Comment by karlito1978** [comment]
For sure, thx

**Comment by tsumeone** [comment]
That means it's not a valid nvidia **store** account.  You keep saying you're successfully able to sign in to the main nvidia store page.  Does the sign in page look like this?  https://i.imgur.com/saHHJmV.png  If it does, then that is not the actual nvidia **store** page and you are signing into a GeForce experience account (not an nvidia **store** account).

I put some instructions in an above comment on how you can create an nvidia store account.  Also make sure you have the right region set in your config, it may be that the accounts are done by region.

**Comment by karlito1978** [comment]
Well the following url.. https://www.nvidia.com/en-gb/shop/ is where I can login successfully and add items to purchase. Possibly, it is the region? I had entered COUNTRY="great_britain" I don't see where else to select region..?
This is the url it opens 'well used too' lol
https://store.nvidia.com/store?Action=DisplayPage&Env=BASE&Locale=en_GB&SiteID=nvidia&id=QuickBuyCartPage

**Comment by geman220** [comment]
Again, `nvidia` doesn't work on the bot currently as they changed their API.  See #254

**Comment by jef** [comment]
That log will be more relevant again when `nvidia` works again. Sorry for the confusion. Thanks for the help @geman220!
