### ISSUE TITLE
Won’t search other than bestbuy still

### ISSUE THREAD

**Issue by nolongerhuman4544** [jef/nvidia-snatcher#251]
I searched around but idk what’s wrong I tried to manually change the store by customizing the .env but don’t see any changes.

**Comment by tsumeone** [comment]
Is the file named just ".env"?

It should have a line like this:
STORES="bestbuy,bandh,evga,newegg,amazon,asus,nvidia"

**Comment by geman220** [comment]
Can you post your `.env`

**Comment by geekx1369** [comment]
When this happened to move I removed bandh to fix it.

**Comment by nolongerhuman4544** [comment]
So should it be .env.stores=bestbuy,new egg etc.

**Comment by geekx1369** [comment]
Yes, STORES="bestbuy,nvidia,evga,newegg,amazon,adorama"

**Comment by jef** [comment]
:shrug: `bandh` works for me

**Comment by nolongerhuman4544** [comment]
What is bandh

Sent from my iPhone

On Sep 23, 2020, at 8:57 PM, Jef LeCompte <notifications@github.com> wrote:

﻿

🤷 bandh works for me

**Comment by jef** [comment]
B&H.

Going to close this out.
