### ISSUE TITLE
nvidia reports stock but the success screenshot is just an empty page

### ISSUE THREAD

**Issue by DarkeleEXE** [jef/nvidia-snatcher#253]
![success-1600895957200](https://user-images.githubusercontent.com/44530257/94070897-484b5c00-fdf3-11ea-8484-80c57159089a.png)

I think they changed some things around suddenly the site is really slow and it always returns a success for stock, when there is none

**Comment by lucaspbastos** [comment]
Same on the US side

**Comment by DarkeleEXE** [comment]
> Same on the US side

according to this i changed the title @lucaspbastos

**Comment by SirSpankey69** [comment]
Same for me
![success-1600895567689](https://user-images.githubusercontent.com/71614371/94071170-1d441680-fdb9-11ea-9c86-61d398f9a9c6.png)
![Capture1](https://user-images.githubusercontent.com/71614371/94071233-351b9a80-fdb9-11ea-9aaa-ad889ffc124d.PNG)

**Comment by Cturner44** [comment]
I'm getting alerts for nvidia as well. saying page not found.

![image](https://user-images.githubusercontent.com/45461742/94071271-41075c80-fdb9-11ea-8ec8-bdf1121c90a4.png)

**Comment by DarkeleEXE** [comment]
@Cturner44 this is the page that opens in your browser when navigating to "directly to cart" right? All my success screenshots are just blank like in the first entry.

**Comment by Cturner44** [comment]
> @Cturner44 this is the page that opens in your browser when navigating via the "directly to cart" right? All my success screenshots are just blank like in the first entry.

Yes, it is.

**Comment by brybry77104** [comment]
I think what is happening here is that Nvidia changed the api key for the backend api (where the bot is checking for inventory and creating the link to the cart). This is causing all of the calls to fail and most likely is resulting in this.

**Comment by Cturner44** [comment]
> I think what is happening here is that Nvidia changed the api key for the backend api (where the bot is checking for inventory and creating the link to the cart). This is causing all of the calls to fail and most likely is resulting in this.

That's what I feel happened. Wonder if that is any indication they are going to be in stock on Nvidia website soon.

**Comment by geman220** [comment]
Known issue #254
