### ISSUE TITLE
NVIDIA changed their API token for digital river.

### ISSUE THREAD

**Issue by brybry77104** [jef/nvidia-snatcher#254]
### Description
when attempting to contact the digital river API's you now get 403 forbidden responses. It seems like the most likely scenario is that Nvidia changed their api key.

This means that not only will the call for inventory status not work but the calls to get a session token and therefor the add to cart will not work. unless we can somehow find the new api key.

**Comment by mocmocamoc** [comment]
It's worse than that unfortunately, they've completely changed how it works and it now requires a reCAPTCHA to get past the "checkout" button. I think they've successfully killed off bots.

**Comment by geman220** [comment]
> It's worse than that unfortunately, they've completely changed how it works and it now requires a reCAPTCHA to get past the "checkout" button. I think they've successfully killed off bots.

They have killed off auto purchasing.  And I wouldn't even say "killed off" because I'm sure it could be circumvented given enough effort.  Either way, nvidia is working again from our side.  Just no auto add to cart.  Going to mark this stale and potentially close tomorrow if it doesn't seem like autocart will be a plan going forward.

**Comment by gcolorado** [comment]
do you think if the bot could check this instead https://store.nvidia.com/store?Action=AddItemToRequisition&SiteID=nvidia&Locale=en_US&productID=5438481700&quantity=1  ? this will try to add it to the cart if it fails you will get an error message

**Comment by geman220** [comment]
`nvidia` and `nvidia-api` have been implemented.  Essentially working the way it used to work (no auto add to cart)
