### ISSUE TITLE
Error - Page Navigation stops script

### ISSUE THREAD

**Issue by RiddlezTheGod** [jef/nvidia-snatcher#255]
When a webpage exceeds he time out in the PAGE_TIMEOUT variable, the script stops until you hit enter. Usually immediately after hitting enter, there are multiple warnings, and the script continues on it's way until it times out again on a webpage

Windows 10 x64, newest install of GIT and Node.JS

**Comment by geman220** [comment]
Post a screenshot, this doesn't happen on my end and I haven't heard of this happening to anyone else.

**Comment by RiddlezTheGod** [comment]
![image](https://user-images.githubusercontent.com/71776373/94073600-ff74b280-fdb4-11ea-8705-3be7b50ee2cd.png)
Waits until I hit enter to do anything
You can see the almost 5 minute time out

**Comment by geman220** [comment]
Turn on debug logging in your `.env` and post results when it times out

**Comment by jef** [comment]
Never seen this problem. Update to latest and report back.

**Comment by RiddlezTheGod** [comment]
seems update to newest has fixed this :) Thank you!
