### ISSUE TITLE
It's Not Working Anymore [Nvidia]

### ISSUE THREAD

**Issue by SirSpankey69** [jef/nvidia-snatcher#256]
I start it and then the first scan comes back positive (has happened over 5 times) and every time I restart it and it does the same thing
has been happening since 4:12:47 and every scan after is positive.
![InkedCapture1_LI](https://user-images.githubusercontent.com/71614371/94077021-6b5e1780-fdc3-11ea-80b9-97358d5067a6.jpg)

**Comment by geman220** [comment]
Disable `nvidia` for now since it is not working, they updated their API. #254

**Comment by cyandura** [comment]
I'm running a similar script that hits the same digital river API and mine is down as well. Sucks because they just made a bunch of cards available at the same time.

**Comment by ultimateguy** [comment]
@geman220 How do I disable nvidia? I removed it from stores in my .env file but the script still throws the same error when it runs.

**Comment by jef** [comment]
https://github.com/jef/nvidia-snatcher/issues/182
