### ISSUE TITLE
false positive on same item at new egg

### ISSUE THREAD

**Issue by Toiletduck34** [jef/nvidia-snatcher#257]
Cannot search new egg anymore as it constantly finds this item below and stops the script.

https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3885-kr/p/N82E16814487520

https://imgur.com/a/6k6xxBb

**Comment by jef** [comment]
Fixed https://github.com/jef/nvidia-snatcher/commit/4cb52d31d57e5e28675771a0885bf8f07b3ce442

Thanks!
