### ISSUE TITLE
Error TS6059 after pulling v1.5 and installing

### ISSUE THREAD

**Issue by vic18t** [jef/nvidia-snatcher#266]
### Description

![2020-09-23_21-53-38](https://user-images.githubusercontent.com/70051955/94102786-ce61a580-fde7-11ea-8992-941dbaf61043.png)

**Comment by jordanfitelive** [comment]
I also had this issue for MacOS.

**Comment by geman220** [comment]
What steps did you do to update?  You can try this: 

- Backup your `.env` 
- Delete `C:\nvidia-snatcher\` 
- Open Windows Comand Prompt
- Type `CD C:\` to change directory to the root `C:` drive
- Type `git clone https://github.com/jef/nvidia-snatcher.git`
- Type `CD nvidia-snatcher`
- Type `npm install`
- Move your backed up `.env` into `C:\nvidia-snatcher\`
- In Windows Command Prompt type `npm run start` from the `C:\nvidia-snatcher\` directory

**Comment by geman220** [comment]
Closing no response.
