### ISSUE TITLE
SHOW_ONLY_MODELS ignores the first and last entry because of the quotation marks.

### ISSUE THREAD

**Issue by DrMaple** [jef/nvidia-snatcher#269]
Using
`SHOW_ONLY_MODELS="ftw3,ftw3 ultra,xc3,xc3 ultra,founders edition"`

The script does not search for the first and last models. Removing the quotation marks
`SHOW_ONLY_MODELS=ftw3,ftw3 ultra,xc3,xc3 ultra,founders edition`

The script searches for those models again.

**Comment by ththiem** [comment]
How do you know it's not searching for them? Tested and it is working fine.

**Comment by DrMaple** [comment]
It wasn't showing the notifications in the console. It would show the three in the middle as OOS but had no notification for the two on the ends.

**Comment by DrMaple** [comment]
Well, it was working how I described it, but I just tried again because you said it was working for you and it's working for me now. I don't know what's changed. Before in the console it was even showing the "" marks around the models which is how I figured out to removed them. I'll just close this since I can't reproduce now.
