### ISSUE TITLE
No matter what I do, I cannot get sound notifications to work.

### ISSUE THREAD

**Issue by shadow9d9** [jef/nvidia-snatcher#275]
I'm a 64 bit windows 10 user.  I've tried keeping the file in the nvidia-snatch directory.  I'
ve tried installing mplayer, installing mplayer directly into nvidia-snatch, putting mpg321 directly into the directory.  The wiki links to cmdmp3 binaries, but the link sends you to empty discord.  Please help.

Edit:  I also tried searching for the cmdmp3 and I found it on github.  It is just 4 files.  cmdmp3.c, cmdmp3win.c, license, and readme.  I tried putting them in the nvidia-snatcher directory as well, without success.

**Comment by tylertylerday** [comment]
Same for me!

**Comment by geman220** [comment]
[cmdmp3](http://www.mailsend-online.com/wp/cmdmp3new.zip) place in `/nvidia-snatcher/` directory
