### ISSUE TITLE
Add some Microcenter storeIDs to front Code page or wiki.

### ISSUE THREAD

**Issue by datbird** [jef/nvidia-snatcher#276]
### Description

Difficult to find Microcenter storeID's, could make it easier to list them somewhere in this project?

### Possible solution

Put list of ID's in environment variable section of code page of this project or add a wiki entry. This is a list I found but I do not believe it contains all MC's so would likely need to be further expanded upon:

CO - Denver?storeID=181
GA - Duluth?storeID=065
GA - Marietta?storeID=041
IL - Chicago?storeID=151
IL - Westmont?storeID=025
KS - Overland Park?storeID=191
MA - Cambridge?storeID=121
MD - Parkville?storeID=125
MD - Rockville?storeID=085
MI - Madison Heights?storeID=055
MN - St. Louis Park?storeID=045
MO - Brentwood?storeID=095
NJ - North Jersey/ Paterson?storeID=075
NY - Brooklyn?storeID=115
NY - Flushing?storeID=145
NY - Westbury?storeID=171
NY - Yonkers?storeID=105
OH - Mayfield Heights?storeID=051
OH - Columbus?storeID=141
OH - Sharonville?storeID=071
PA - St. Davids?storeID=061
TX - Dallas?storeID=131
TX - Houston?storeID=155
VA - Fairfax?storeID=081

**Comment by geman220** [comment]
Added IDs here: https://github.com/jef/nvidia-snatcher/wiki/Microcenter-StoreIDs
