### ISSUE TITLE
Please add max notification limit

### ISSUE THREAD

**Issue by BaeByte** [jef/nvidia-snatcher#277]
I know some sites like Best Buy will keep going off long after they're out of stock could we add a function to limit the amount of notifications before blacklisting for a certain amount of time?

The website's add to cart button is super slow to change to out of stock and some users are reporting notifications as long as 30 mins after the item goes out of stock.

**Comment by geman220** [comment]
This function already exists `IN_STOCK_WAIT_TIME="30"` Time to wait between requests to the same store if it has cards in stock in seconds.

https://github.com/jef/nvidia-snatcher#customization

**Comment by merkury187** [comment]
With the tabs that keep opening on my computer I can assure you that that IN_STOCK_WAIT_TIME="30" is not doing any good. 3 tabs opened in like 5-10 seconds apart all for the same card.

**Comment by geman220** [comment]
Dupe of #281 the problem appears to be on Best Buys website and the way it loads.
