### ISSUE TITLE
Amazon NL support

### ISSUE THREAD

**Issue by beantje** [jef/nvidia-snatcher#278]
could you add amazon NL ? 
that would be amazing as there had some stock today and i missed it :(

**Comment by geman220** [comment]
Can you provide links to the products on Amazon NL?  Can you also provide the CAPTCHA and in-stock localized language?  For example, the captcha for English Amazon is `enter the characters you see below` and positive stock is `add to cart`.

```
	labels: {
		captcha: {
			container: 'body',
			text: ['enter the characters you see below']
		},
		inStock: {
			container: '#desktop_buybox',
			text: ['add to cart']
		}
	},
```

**Comment by beantje** [comment]
<input id="add-to-cart-button" name="submit.add-to-cart" title="In winkelwagen plaatsen" 

so text: ['In winkelwagen plaatsen']

but i don't get any captcha on amazon nl ?

**Comment by geman220** [comment]
There is a captcha for certain, F5 the page a ton and eventually, a captcha will come up.  What are the URLs to all of the products?

**Comment by beantje** [comment]
https://www.amazon.nl/3080-VENTUS-3X-10G-OC/dp/B08HM4M621

**Comment by geman220** [comment]
I mean I can put in a PR but you are almost certainly going to get CATPCHA false positives.  Can you translate `enter the characters you see below`, that at least gives us a chance.

**Comment by beantje** [comment]
"voer de karakters in die u hieronder ziet"+


btw still no captha mmm

**Comment by geman220** [comment]
@beantje It will come up with the bot almost certainly unless you are searching a lot of sites.  Maybe it's over a longer period but it will happen.  I can throw together a store file for you though.
