### ISSUE TITLE
Running headless on ubuntu-server; error on startup

### ISSUE THREAD

**Issue by Onslivion** [jef/nvidia-snatcher#282]
Title. I tried everything, currently using node.js 14.12. Using the most recent version of nvidia-snatcher (1.15.0)

This is what occurs when I run it:

<img width="1437" alt="Screen Shot 2020-09-24 at 13 16 22" src="https://user-images.githubusercontent.com/25300749/94183513-25a75a80-fe68-11ea-968a-d119ce2b927e.png">

**Comment by andrewmackrodt** [comment]
It looks like puppeteer is looking fore Firefox >= 80.0 which isn't available on your system. While not related to your issue, try not to use `sudo`, it shouldn't be needed in this context. If you have no browsers installed, the following should work:

```sh
sudo apt install chromium-browser
export CHROME_BIN=/usr/bin/chromium-browser
export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
npm install
npm run start
```

**Comment by Onslivion** [comment]
It actually won't run unless I sudo.
could be a permissions thing

**Comment by jef** [comment]
Did you try and run with `PUPPETEER_PRODUCT="firefox" npm install`?

**Comment by Onslivion** [comment]
After reinstalling without any usage of sudo, it seems to have resolved. Looking through the logs, it seemed that;
`export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true`
is what helped with the error.

Thanks a bunch.
