### ISSUE TITLE
Add Neweggbusiness store

### ISSUE THREAD

**Issue by merkury187** [jef/nvidia-snatcher#285]
Can we have both Newegg.com and Neweggbusiness.com as stores to search? I don't think you actually need to be a business in order to check out on neweggbusiness

**Comment by geman220** [comment]
You do need a business.  See: https://www.neweggbusiness.com/promotions/nepro/19-0081/index.html#:~:text=The%20goal%20of%20NeweggBusiness%20is,an%20EIN%20during%20account%20registration.&text=No%2C%20you%20will%20need%20to,a%20NeweggBusiness.com%20specific%20account.

```
What information do I need to provide to create a NeweggBusiness account?
To create a NeweggBusiness account, you will need to provide the following:

Valid email address (this will also act as your NeweggBusiness ID)
Select an account password
Primary contact information
Company information including a Federal Tax ID # (EIN) for non-governmental agencies
```
