### ISSUE TITLE
Lots of bandwidth being consumed

### ISSUE THREAD

**Issue by merkury187** [jef/nvidia-snatcher#288]
I am running nvidia-snatcher today with latest code and I am seeing the network adapter receiving  60-95 Mbps of traffic: https://prnt.sc/unbo2s

I tried running this on a computer in a different location and it is no where even near this high. How c an I fix this as it is consuming the entire pipe. I tried removing 3090 series but it is still consuming the same amount of bandwidth.

My config file:
EMAIL_USERNAME="XXXXX@gmail.com"
EMAIL_PASSWORD="XXXX"
HEADLESS="true"
IN_STOCK_WAIT_TIME="130"
LOG_LEVEL="info"
OPEN_BROWSER="true"
PAGE_TIMEOUT="30000"
PAGE_SLEEP_MIN="5000"
PAGE_SLEEP_MAX="10000"
SHOW_ONLY_BRANDS="nvidia,asus,evga,msi,gigabyte"
SHOW_ONLY_SERIES="3080,3090"
STORES="bestbuy,nvidia,evga,newegg,asus,amazon,adorama"
COUNTRY="usa"
SCREENSHOT="true"
TELEGRAM_ACCESS_TOKEN="XXXXX"
TELEGRAM_CHAT_ID="-XXXXX"
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

**Comment by geman220** [comment]
There are too many variables to be able to assist you.  There is a multitude of reasons why one computer would have more or less inbound traffic.  Right now the bot easily can pull 30Mbps - 100Mbp down and that's before you factor in literally anything else going on with the computer.  The fact that it consumes less on another computer would serve to show that the bot doesn't have some bug where it's randomly using more or less data.

**Comment by geman220** [comment]
Low bandwidth `.env` variable in #294
