### ISSUE TITLE
Add low bandwidth mode

### ISSUE THREAD

**Issue by joshuahiggins** [jef/nvidia-snatcher#290]
### Description

By blocking images and fonts, the snatcher can load pages a little faster and reduce the overall traffic the script downloads. This will not impact the ability of the snatcher to review the page for updates. 

However, this feature can't be enabled currently as the `puppeteer-extra-plugin-adblocker` package already intercepts all requests in order to block those. A relevant discussion about multiple request interceptions via `puppeteer-extra` can be found here: https://github.com/berstend/puppeteer-extra/issues/91

### Possible solution

Users could be provided flags for the adblocker and/or low bandwidth modes and informed that low bandwidth mode requires the adblocker to be disabled. Blocking images and fonts should improve speed and reduce traffic more than the adblocking, but I'm not certain if adblocking was enabled for other reasons.

**Comment by joshuahiggins** [comment]
I have already tested this locally and it runs solid, but I couldn't find a solid workaround to the dual request interception issue. Happy to toss a PR of this proposed solution. Just figured I'd open it up to discussion first since I wasn't certain of the reasons behind the adblocking.

**Comment by merkury187** [comment]
This low bandwidth mode is exactly what i need

**Comment by geman220** [comment]
> I have already tested this locally and it runs solid, but I couldn't find a solid workaround to the dual request interception issue. Happy to toss a PR of this proposed solution. Just figured I'd open it up to discussion first since I wasn't certain of the reasons behind the adblocking.

The best bet is to submit a PR and then we can get more eyes on it and figure out what we can do =)

**Comment by joshuahiggins** [comment]
Good call. Just opened a PR.

**Comment by geman220** [comment]
> Good call. Just opened a PR.

Great thanks for contributing!
