### ISSUE TITLE
Add PNY.com webstore

### ISSUE THREAD

**Issue by di3selbrah** [jef/nvidia-snatcher#291]
### Description
Can you please add the PNY website store? They carry both the RTX 3080 and 3090 so far.

**Comment by geman220** [comment]
Can you provide links to the products?

**Comment by di3selbrah** [comment]
Main sales page, Add to Cart button currently greyed out for the RTX 3080's, 3090's and upcoming 3070.
Link: https://www.pny.com/consumer/view-all-products/geforce-graphics

Link: https://www.pny.com/geforce-rtx-3080-xlr8-gaming-epic-x-rgb-triple-fan-m
PNY GeForce RTX 3080 10GB XLR8 Gaming EPIC-X RGB Triple Fan Edition
PNY GeForce RTX™ 3080 10GB XLR8 Gaming EPIC-X RGB™ Triple Fan Edition
SKU: VCG308010TFXMPB

Link: https://www.pny.com/geforce-rtx-3080-xlr8-gaming-epic-x-rgb-triple-fan-p
PNY GeForce RTX 3080 10GB XLR8 Gaming EPIC-X RGB Triple Fan Edition
PNY GeForce RTX™ 3080 10GB XLR8 Gaming EPIC-X RGB™ Triple Fan Edition
SKU: VCG308010TFXPPB

Link: https://www.pny.com/geforce-rtx-3090-xlr8-gaming-epic-x-rgb-triple-fan-p
PNY GeForce RTX 3090 24GB XLR8 Gaming EPIC-X RGB Triple Fan Edition
PNY GeForce RTX™ 3090 24GB XLR8 Gaming EPIC-X RGB™ Triple Fan Edition
SKU: VCG309024TFXPPB

Link: https://www.pny.com/geforce-rtx-3090-xlr8-gaming-epic-x-rgb-triple-fan-m
PNY GeForce RTX 3090 24GB XLR8 Gaming EPIC-X RGB Triple Fan Edition
PNY GeForce RTX™ 3090 24GB XLR8 Gaming EPIC-X RGB™ Triple Fan Edition
SKU: VCG309024TFXMPB

Link: https://www.pny.com/geforce-rtx-3070-xlr8-gaming-epic-x-rgb-triple-fan
PNY GeForce RTX 3070 8GB XLR8 Gaming EPIC-X RGB Triple Fan Edition
PNY GeForce RTX™ 3070 8GB XLR8 Gaming EPIC-X RGB™ Triple Fan Edition
SKU: VCG30708TFXPPB

**Comment by geman220** [comment]
This would be risky to implement currently.  The way to bot searches it reads the plaintext of the site, we can tell it to search a certain `div container` so for example `.sm-12 lg-6` but that is very dependant on those classes never moving.  That's not a big deal with a product page like https://www.bestbuy.com/site/gigabyte-geforce-rtx-3080-10g-gddr6x-pci-express-4-0-graphics-card-black/6430620.p?acampID=0&cmp=RMX&loc=Hatch&ref=198&skuId=6430620&intl=nosplash where we can safely assume the `Add to Cart` `div class` will never incorrectly point to another item.  But on a list that is non-specific column containers, there is decent risk things are moved around and case a ton of false positives.  It might be better to implement this once the product pages have purchase links.

**Comment by geman220** [comment]
Nevermind, #295
