### ISSUE TITLE
getting an error when running npm install on mac

### ISSUE THREAD

**Issue by frankiemarino5** [jef/nvidia-snatcher#292]
frankie@Frankies-MacBook-Air ~ % npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/frankie/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/frankie/package.json'
npm WARN frankie No description
npm WARN frankie No repository field.
npm WARN frankie No README data
npm WARN frankie No license field.

up to date in 0.368s
found 0 vulnerabilities

frankie@Frankies-MacBook-Air ~ %

**Comment by geman220** [comment]
You need to run `npm install` from the root directory of `nvidia-snatcher`

**Comment by frankiemarino5** [comment]
> You need to run `npm install` from the root directory of `nvidia-snatcher`

I did that but i dont have a .env.envelope file in the nvidia-snatcher folder??

**Comment by geman220** [comment]
I don't know what you mean by `.env.envelope` that isn't a file that is in the repo

**Comment by frankiemarino5** [comment]
> I don't know what you mean by `.env.envelope` that isn't a file that is in the repo

Got it up and running. is there a way to test notifications?

**Comment by geman220** [comment]
Please see https://github.com/jef/nvidia-snatcher#customization for all configuration and testing instructions.

The command you want is `npm run test:notification`
