### ISSUE TITLE
Turning off debug flags

### ISSUE THREAD

**Issue by matt0428** [jef/nvidia-snatcher#297]
Tried looking online for a way to toggle debug flags but leave the info flags enabled, but I couldn't find anything. Would you happen to know how to do that?

**Comment by geman220** [comment]
I don't understand your question.  If you change `LOG_LEVEL=` to `debug` it will show the normal output in terminal, as well as the debug output in terminal.

**Comment by geman220** [comment]
Someone had this issue in discord so I actually know what you are talking about.  Remove the line `LOG_LEVEL=""` from your `.env`

**Comment by matt0428** [comment]
Sorry for the confusion. Removing the LOG_LEVEL line worked like a charm. Thank you!
