### ISSUE TITLE
Requests slow over time

### ISSUE THREAD

**Issue by Excalibur1224** [jef/nvidia-snatcher#299]
### Description
Hi! I first of all want to say that I really appreciate you for making this code and letting us use it. I am running on windows and am having a problem however, the lookups start at a frequent pace but after about 20 or so they start to slow down dramatically, eventually taking 30 seconds to a minute for every search, and repeats when the program is terminated and started again. When I was manually refreshing the site on launch day after about 15 minutes it kicked me off and I had to restart my browser. That could be something similar to what's happening.
### Possible solution

Forgive me for being naïve, but would it be possible to make another instance after too much lag, or is this a setting I can change? Again I want to thank you again for making this, and I completely understand that this is your free time.

**Comment by geman220** [comment]
What is in your `STORES=` in your `.env`?

**Comment by Excalibur1224** [comment]
it is currently not set, it only searches the nvidia store by default I assumed. Will changing this fix the issue?

**Comment by geman220** [comment]
Nvidia site is being very slow.  If you only want to search Nvidia I'd change to `nvidia-api` until the website stops being so non-responsive/slow.

**Comment by Excalibur1224** [comment]
Thank you! I'll give it a try

**Comment by HiramIII** [comment]
> Nvidia site is being very slow.  If you only want to search Nvidia **only** I'd change to `nvidia-api` until the website stops being so non-responsive/slow.

Will using the Nvidia-api still have the auto add to cart feature or just open the browser and take you to page?
