### ISSUE TITLE
Filter card brand and model

### ISSUE THREAD

**Issue by jef** [jef/nvidia-snatcher#30]
### Description

It would be nice to filter by brand and model across all sites.

### Possible solution

Create global keys for brands and models and make a filter function.

**Comment by jef** [comment]
Half of this is completed by https://github.com/jef/nvidia-snatcher/pull/120.

Wouldn't be much to add a filter for models.

**Comment by geman220** [comment]
Believe we now have this right?

```
SHOW_ONLY_SERIES
SHOW_ONLY_BRANDS
```

Unless you are also looking for filters like `TUF`

**Comment by aharris02** [comment]
Offering a filter for the specific model makes sense. Ex: user is specifically looking for either evga ftw3 ultra or asus rog strix.
