### ISSUE TITLE
Is correct country used?

### ISSUE THREAD

**Issue by niagi** [jef/nvidia-snatcher#302]
Hi,

I am using script with sweden selected for country, however I get an error sometimes with the following message:

nvidia founders edition - net::ERR_CONNECTION_CLOSED at https://www.nvidia.com/en-us/shop/geforce/gpu/?page=1&limit=9&locale=en-us&gpu=RTX%203080&category=GPU&manufacturer=NVIDIA&gpu_filter=RTX%203090~1,RTX%203080~1,RTX%203070~0,TITAN%20RTX~0,RTX%202080%20Ti~0,RTX%202070%20SUPER~0,RTX%202060%20SUPER~0,RTX%202060~0,GTX%201660%20Ti~0,GTX%201660%20SUPER~0,GTX%201660~0,GTX%201650%20SUPER~0,GTX%201650~0

I haven't checked the code properly, but from this it seems to be using the US site to check? or why am I getting this error message?

I have the 1.6.0 latest release (I think)
My env looks like this:

```
# ** All configuration variables are optional **
# Read https://github.com/jef/nvidia-snatcher#customization for help on customizing this file
#############################################################################################

BROWSER_TRUSTED=""
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK=""
EMAIL_USERNAME=""
EMAIL_PASSWORD=""
HEADLESS="true"
IN_STOCK_WAIT_TIME="30"
LOG_LEVEL="info"
MICROCENTER_LOCATION=""
OPEN_BROWSER="true"
PAGE_TIMEOUT="60000"
PHONE_NUMBER=""
PHONE_CARRIER=""
PLAY_SOUND=""
PUSHBULLET=""
PUSHOVER_TOKEN="<my token>"
PUSHOVER_USER="<my key>
PUSHOVER_PRIORITY="0"
PAGE_SLEEP_MIN="8000"
PAGE_SLEEP_MAX="20000"
SHOW_ONLY_BRANDS=""
SHOW_ONLY_MODELS="founders edition"
SHOW_ONLY_SERIES="3080"
SLACK_CHANNEL=""
SLACK_TOKEN=""
STORES="nvidia"
COUNTRY="sweden"
SCREENSHOT="true"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID="1234"
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"


```

**Comment by geman220** [comment]
`STORES="nvidia-api"` `nvidia` doesn't have localization support, only `nvidia-api`.

**Comment by niagi** [comment]
> `STORES="nvidia-api"` `nvidia` doesn't have localization support, only `nvidia-api`.

Ahh, I didn't see that there was a change from nvidia to nvidia-api.
