### ISSUE TITLE
Add EVGA 3080 FTW3 and FTW3 Ultra for Newegg 

### ISSUE THREAD

**Issue by armsteullion** [jef/nvidia-snatcher#303]
It seems earlier this morning Newegg had replaced the URLs for these with the 3090 and/or removed them altogether.  They've been readded now though and are visible.  

FTW3 Ultra: https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3897-kr/p/N82E16814487518
FTW3:  https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3895-kr/p/N82E16814487519

**Comment by geman220** [comment]
Added to #293
