### ISSUE TITLE
error:: couldn't send email self signed certificate in certificate chain

### ISSUE THREAD

**Issue by McDAlexander** [jef/nvidia-snatcher#311]
### Description

When trying to run a notification test, I receive the following error:

`error :: ✖ couldn't send email self signed certificate in certificate chain
`
I'm running this on a Windows 10 box.

Here is my setup (scrubbed of personal data)
```
EMAIL_USERNAME="My.Gmail.Address@gmail.com"
EMAIL_PASSWORD="myApppasswordFromGoogle"
DISCORD_NOTIFY_GROUP="@somerandomnumberthing"
DISCORD_WEB_HOOK="https://discordapp.com/api/webhooks/<secret>"
LOG_LEVEL="info"
OPEN_BROWSER="TRUE"
PHONE_NUMBER="us-phone-number"
PHONE_CARRIER="att"
SHOW_ONLY_BRANDS="nvidia"
SHOW_ONLY_MODELS="founders edition"
SHOW_ONLY_SERIES="3080"
STORES="bestbuy"
COUNTRY="usa"
SCREENSHOT="false"
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
```
I am not sure what to do here. I've tried going back into my Google account, deleting my app password and recreating it. Hoping someone else here has run into this and has a solution.

**Comment by geman220** [comment]
Disable your Anti-Virus and try again.  Check your time/date on your PC, is it accurate?

**Comment by cyandura** [comment]
i had the same issue, i turned off anti virus. I then got a failed login, so i turned on 'less secure apps' in the gmail security settings. Works great. Ive had to do this before with scan to email on my printer. Gmail's security in this regard is pretty conservative

**Comment by McDAlexander** [comment]
Thanks all. This fixed the issue. For anyone else looking for what exactly to turn off if you have Avast, turn off Mail Shield.
