### ISSUE TITLE
Only skip checking per IN_STOCK_WAIT_TIME for the item that is in stock

### ISSUE THREAD

**Issue by shaver** [jef/nvidia-snatcher#312]
### Description

Right now, if a store has any of its possible items in stock, all further checks for that store, for all items, are blocked for IN_STOCK_WAIT_TIME seconds. This means that I have to decide between
- getting a notification every 10 seconds for some scalper's $2500 3080 that I'm not going to touch
- not finding out for a while about any other stock that appears on amazon-ca

### Possible solution

It would be nice if the block applied only to the item that was actually found.

**Comment by jef** [comment]
Fixed in https://github.com/jef/nvidia-snatcher/commit/c7a716f981976a76afe61a4d985bd6fe4343595b and https://github.com/jef/nvidia-snatcher/pull/325

Related: https://github.com/jef/nvidia-snatcher/issues/312
