### ISSUE TITLE
IN_STOCK_WAIT_TIME not working as intended

### ISSUE THREAD

**Issue by cndman** [jef/nvidia-snatcher#315]
### Description

Set IN_STOCK_WAIT_TIME in .env file to several  different options including 3600 which should make it so the same link isn't notified more than once an hour but was still getting the same link notification once every 2 minutes.

![Screenshot_17](https://user-images.githubusercontent.com/68614562/94304522-aedc9100-ff3d-11ea-8ae9-0991590b3b8d.png)

**Comment by geman220** [comment]
Works for me, you don't see `[${store.name}] Has stock, waiting before trying to lookup again...` when stock is detected?

**Comment by serg06** [comment]
After pulling the latest code, it doesn't work for me either.

**Comment by geman220** [comment]
Are you getting positive stock alerts?  The message would only come up if you have a positive hit and it skips that hit again.

**Comment by Kommeh** [comment]
I get a positive hit and it never skips that item even when it should wait 3600 seconds for my settings. I also do not get that message since earlier code updates.

**Comment by cndman** [comment]
See here I'm getting back to back pings for the same link.

**Comment by dpgagnon** [comment]
I commented on where the issue is here:
https://github.com/jef/nvidia-snatcher/commit/c7a716f981976a76afe61a4d985bd6fe4343595b#r42727890
