### ISSUE TITLE
Not sure if issue or feature

### ISSUE THREAD

**Issue by SeanSeanySean** [jef/nvidia-snatcher#319]
I've been running this on my lower-end spare laptop so I can continue to actually get work done on my primary system. I've noticed that this utility easily consumes 100% of the CPU resources, which is fine, but it made me realize that the rate in which stores are being checked is bottlenecked by my quad-core mobile CPU. I also notice a LOT of what appears to be debug info flying through the window as the tool runs, and I'm not sure how much of that really needs to be displayed in the command window. 

This is helpful: "6:44:59 PM] info :: ✖ [bestbuy] [evga (3080)] xc3 ultra :: OUT OF STOCK"

Below is 99% of the output constantly flying by that isn't helpful. Is that by design? If so, is there any way to turn down the debug level so I only get the above info? I looked at the env file variables but it wasn't clear what changing the HEADLESS or LOG_LEVEL variables would do.

initializer.initializeComponent({"creatorNamespace":"pricing","componentId":"offer-list","contractVersion":"v1","componentVersion":"1.2039.11"}, "pricing-offer-list-96434aed-1387-4bde-9a47-c50607131f2f", "{\"app\":{\"features\":{\"legacyOfferPage\":false},\"configuration\":{\"prepackagedOffers\":true,\"offerDisplaySupportedTargets\":-1,\"features\":{\"legacyOfferPage\":false}},\"live-Config-card-members\":{\"rewardsOfferId\":\"pcmcat1475162123051\"},\"enableCardMemberOffers\":\"true\",\"instanceId\":\"pricing-offer-list-96434aed-1387-4bde-9a47-c50607131f2f\",\"skuId\":\"6432400\",\"blackListedOffers\":[\"362794\",\"373053\",\"380923\",\"338123\",\"195224\",\"222169\",\"216217\",\"217888\",\"387329\",\"390994\",\"390538\"],\"hotOfferOnly\":false,\"isModalOpen\":false},\"offerView\":{\"offerListOffers\":{\"allSpecialOffers\":[],\"financeOffersWithOfferIds\":[{\"sameSkuDiscountEligible\":false,\"lastChance\":false,\"hotOffer\":false,\"limitedTime\":false,\"hasServiceSku\":true,\"numberOfTargets\":0,\"offerType\":\"Financing\",\"easyUpgrade\":false,\"subscription\":false,\"quantity\":1,\"offerId\":\"384917\",\"multiParentGwp\":null,\"newOffer\":false,\"endingSoon\":false,\"openLink\":\"inModal\",\"skuPromotionalMessage\":\"18 Month Financing\",\"landingPageUrl\":\"\\u002Fsite\\u002Fmodals\\u002F18-month-financing-storewide-purchases-499-up\\u002Fpcmcat1586780522994.c?id=pcmcat1586780522994\",\"linkTo\":\"\\u002Fsite\\u002Fmodals\\u002F18-month-financing-storewide-purchases-499-up\\u002Fpcmcat1586780522994.c?id=pcmcat1586780522994\",\"offerLabel\":\"\",\"offerDisplayConditionalFlag\":false},{\"sameSkuDiscountEligible\":false,\"lastChance\":false,\"hotOffer\":false,\"limitedTime\":false,\"hasServiceSku\":true,\"numberOfTargets\":0,\"offerType\":\"Financing\",\"easyUpgrade\":false,\"subscription\":false,\"quantity\":1,\"offerId\":\"384913\",\"multiParentGwp\":null,\"newOffer\":false,\"endingSoon\":false,\"openLink\":\"inModal\",\"skuPromotionalMessage\":\"12 Month Financing\",\"landingPageUrl\":\"\\u002Fsite\\u002Fmodals\\u002F12-month-storewide\\u002Fpcmcat1479769227365.c?id=pcmcat1479769227365\",\"linkTo\":\"\\u002Fsite\\u002Fmodals\\u002F12-month-storewide\\u002Fpcmcat1479769227365.c?id=pcmcat1479769227365\",\"offerLabel\":\"\",\"offerDisplayConditionalFlag\":false}]}},\"metaLayer\":{\"env_assets\":\"https:\\u002F\\u002Fassets.bbystatic.com\",\"env_piscesUrl\":\"https:\\u002F\\u002Fpisces.bbystatic.com\"}}", "en-US");
                </script>
                </div></div></div></div></div></div>

**Comment by geman220** [comment]
Delete `LOG_LEVEL=` in your `.env`
