### ISSUE TITLE
.env file for macbook

### ISSUE THREAD

**Issue by karakemp1** [jef/nvidia-snatcher#320]
### Description

<img width="526" alt="pic env error" src="https://user-images.githubusercontent.com/27331658/94326393-9be3b400-ff71-11ea-8da4-908643ed1ed0.png">

**Comment by curtisgreene** [comment]
Using a text editor like atom or sublime would allow you to create the .env file without an issue. Also, in Finder on a mac, you can hit command+shift+dot to show hidden files

**Comment by geman220** [comment]
Please see @curtisgreene response

**Comment by karakemp1** [comment]
Hi everyone @curtisgreene and @geman220 yes I know about how to make the .env file appear, but despite the file being created on my text editor properly, the bot is not detecting it. I will try a different text editor like atom or sublime but I am not sure it will fix the issue.

**Comment by jef** [comment]
It will 100% fix the issue since it's a file type thing.
