### ISSUE TITLE
Error Thrown When Running

### ISSUE THREAD

**Issue by TheWildLeek** [jef/nvidia-snatcher#323]
![Capture](https://user-images.githubusercontent.com/22965236/94329845-8a5bd580-ff8c-11ea-8fac-e318ca4da547.PNG)

See error above. What am I doing wrong?

**Comment by karmanbadhesha** [comment]
Make sure you cd to the nvidia-snatcher folder before you run npm install

**Comment by TheWildLeek** [comment]
Oh my God. It's been a tough couple days and I didn't even see that I was in the wrong directory. Thanks man.
