### ISSUE TITLE
Sound player not found

### ISSUE THREAD

**Issue by xBigWillyStylex** [jef/nvidia-snatcher#324]
### Description

Cannot play a notification sound for some reason. Tried .wav and .mp3, get the sound player not found error when starting the bot

**Comment by geman220** [comment]
Please read the wiki https://github.com/jef/nvidia-snatcher/wiki/Installation:-Windows

**Comment by xBigWillyStylex** [comment]
I'm aware, I've followed all the instructions and have the sound file in the folder. I get a "sound player not found" error when running the script.
