### ISSUE TITLE
Nvidia continually timing out

### ISSUE THREAD

**Issue by xBigWillyStylex** [jef/nvidia-snatcher#328]
The Nvidia store will work for the first few pulls and then get a timeout error continually each time it tries to do a pull. I have tried several different user agent settings with no luck.

**Comment by matjam** [comment]
`PAGE_TIMEOUT=120000` is what I'm using (though it seems to be capped at 60 seconds) and that seems to work.

**Comment by daddysspecialboy** [comment]
I have the exact same issue. I tested the solution from @matjam by increasing the PAGE_TIMEOUT to 60 seconds, did not solve for me.

**Comment by Kieran813** [comment]
I had the same issue and `PAGE_TIMEOUT=120000` worked for me.

**Comment by itsandreramon** [comment]
same issue. works the first few times, then times out. comes back at some point in time though only to timeout again after a few times. also, setting the page timeout does not seem to change anything.
