### ISSUE TITLE
503/504 errors on Amazon

### ISSUE THREAD

**Issue by Skyw0rmJaems** [jef/nvidia-snatcher#329]
### Description

The issue seems to happen on amazon primarily, 
![Screenshot (1)](https://user-images.githubusercontent.com/71611857/94345803-882e6100-fff6-11ea-9368-0cba7d6ec9b8.png)

### Possible solution

 Well after speaking with andrew, we tried changing the user agent in env file, and it seems to fix the issue. He thought it might be useful to try a change-user plugin in puppeteer if thats possible. Thanks again for your help Andrew!

**Comment by andrewmackrodt** [comment]
#326 is potentially the same issue. Maybe we can try waiting for n amount of 503 errors, [clear site data](https://stackoverflow.com/a/55872001) and then cycle the user-agent.

**Comment by Skyw0rmJaems** [comment]
Update: after about 10-15 minutes the errors reappear until user agent is changed again.

**Comment by poly-mathic** [comment]
> #326 is potentially the same issue. Maybe we can try waiting for n amount of 503 errors, [clear site data](https://stackoverflow.com/a/55872001) and then cycle the user-agent.

where should the browser history be cleared? from the command line or within one of the files?

**Comment by jef** [comment]
> Well after speaking with andrew, we tried changing the user agent in env file, and it seems to fix the issue. He thought it might be useful to try a change-user plugin in puppeteer if thats possible. Thanks again for your help Andrew!

Closing for now. We can open up another issue to get incognito. I starting using `BrowserContext` everywhere, but didn't do much testing around it. Would like to see where that goes.
