### ISSUE TITLE
[3:10:09 PM] error :: ✖ [newegg-ca] msi gaming x trio - Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by Fedack** [jef/nvidia-snatcher#332]
newegg-ca keeps pulling errors like above. Unsure what it means, if either the card is in stock but it couldn't get a link or it just couldn't poll.

**Comment by serg06** [comment]
This happens to me once in a while, like once in every 100 requests maybe, I just ignore it and everything seems to work fine.
