### ISSUE TITLE
Help requested to add new site.

### ISSUE THREAD

**Issue by Alohaaaaaaa** [jef/nvidia-snatcher#335]
Hi guys,

I really enjoy the work done so far in this project, it's been very helpful.
As a Canadian I am trying to add various smaller local shops on my end - I have had no issue at all adding several of them ; CanadaComputers, KindInformatique, etc.

I have spent approximately 6 hours trying to get the right container information to work on Walmart.ca ; I just cannot get a result that works - on any product at all.

[https://www.walmart.ca/en/ip/GIGABYTE-NVIDIA-GeForce-RTX-2080-WINDFORCE-8G-GDDR6-HDMI-3DisplayPort-USB-Type-C-PCI-Express-Video-Card/PRD2CO3JDQMN33S](url)

If anyone is able to give some insight I would appreciate it !

Thank you again for your great work, much appreciated!

**Comment by andrewmackrodt** [comment]
`.eewy8oa4` seems to refer to a product container, you can target the add to cart button directly with `.cta button[data-automation="cta-button"]`.

**Comment by Alohaaaaaaa** [comment]
> `.eewy8oa4` seems to refer to a product container, you can target the add to cart button directly with `.cta button[data-automation="cta-button"]`.

`export const WalmartCa: Store = {
	labels: {
		inStock: {
			container: '.cta button[data-automation="cta-button"]',
			text: ['add to cart']
		}
	}`

For some reason, this is not working =(

**Comment by andrewmackrodt** [comment]
It is working for me:

**.env**
```env
IN_STOCK_WAIT_TIME=3600
LOW_BANDWIDTH=false
OPEN_BROWSER=false
SCREENSHOT=true
SHOW_ONLY_SERIES=test:series
STORES=walmart-ca
```

**walmart-ca.ts**
```ts
import {Store} from './store';

export const WalmartCa: Store = {
	labels: {
		inStock: {
			container: '.cta button[data-automation="cta-button"]',
			text: ['add to cart']
		}
	},
	links: [
		{
			brand: 'test:brand',
			model: 'test:model',
			series: 'test:series',
			url: 'https://www.walmart.ca/en/ip/GIGABYTE-NVIDIA-GeForce-RTX-2080-WINDFORCE-8G-GDDR6-HDMI-3DisplayPort-USB-Type-C-PCI-Express-Video-Card/PRD2CO3JDQMN33S'
		}
	],
	name: 'walmart-ca'
};

```

**Comment by Alohaaaaaaa** [comment]
I'm not sure what is wrong on my end, I'm doing the exact same thing as in your example - still says out of stock..

**Comment by Alohaaaaaaa** [comment]
Actually ..... it just worked .

I removed 	`waitUntil: 'domcontentloaded'` and it worked afterward..
