### ISSUE TITLE
Browser won't open with test notification

### ISSUE THREAD

**Issue by moggin20** [jef/nvidia-snatcher#336]
When I run the test notification command _**npm run test:notification**_
it just says **_discord message sent_** and nothing happens.

I'd like to just open a chrome window if I get a hit instead of getting an email or a text.
How could I make that happen?

Here is the contents of my **_.env_** file:

BROWSER_TRUSTED=""
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK=""
EMAIL_USERNAME=""
EMAIL_TO=""
EMAIL_PASSWORD=""
HEADLESS=""
IN_STOCK_WAIT_TIME=""
LOG_LEVEL=""
LOW_BANDWIDTH=""
MICROCENTER_LOCATION=""
OPEN_BROWSER="true"
PAGE_TIMEOUT=""
PHONE_NUMBER=""
PHONE_CARRIER=""
PLAY_SOUND=""
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN=""
PAGE_SLEEP_MAX=""
SHOW_ONLY_BRANDS=""
SHOW_ONLY_MODELS=""
SHOW_ONLY_SERIES="3080"
SLACK_CHANNEL=""
SLACK_TOKEN=""
STORES="amazon,bandh,bestbuy,asus,evga,newegg,nvidia"
COUNTRY="usa"
SCREENSHOT="false"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT=""

**Comment by jasontechpro** [comment]
Try doing a "Y" in "OPEN_BROWSER". Thats what I did and that is what happened when it located a card on Nvidias site. I was also successful in placing the order.

**Comment by rambosbff** [comment]
I'm having this problem too. Adding "y" didn't solve it. I did notice my user agent is different from default for the chrome value:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

However, when I try to add this value in to user agent it doesn't make a difference. Discord, works fine and so does the sound notification, but I can't get the open browser to work.

**Comment by jef** [comment]
`OPEN_BROWSER="true"`, but it's default to true in the code anyway, so you don't have to set. What OS are you running?

**Comment by moggin20** [comment]
> `OPEN_BROWSER="true"`, but it's default to true in the code anyway, so you don't have to set. ~What OS are you running?~
> 
> Nevermind, you're testing a notification. That won't open your browser. This test is only for notifications, not an "in stock simulation" I suppose. It may lead you on to believe this, but not the case.

Which browser does it open if it finds a card?
Also, do I need to add anything to my .env file I pasted above, or will what I have work?
Thanks!
