### ISSUE TITLE
[8:17:45 PM] warn :: ✖ [asus] [asus (3080)] tuf :: STATUS CODE ERROR 404

### ISSUE THREAD

**Issue by Fedack** [jef/nvidia-snatcher#338]
Error STATUS CODE ERROR 404 for Asus website.

**Comment by andrewmackrodt** [comment]
This is normal for the ASUS store as they take listings offline while there's no stock but a lot of users are enquiring about this on Discord so I'll make a PR tomorrow which ignores 404 statuses for the ASUS store.

**Comment by Fedack** [comment]
That's fair, I'd just set it as Out of Stock when it detect a 404 for Asus
store.
