### ISSUE TITLE
Please add a table for SHOW_ONLY_BRANDS and SHOW_ONLY_MODELS to the readme

### ISSUE THREAD

**Issue by SeanSeanySean** [jef/nvidia-snatcher#358]
### Description

There is no "Supported Brands" and "Supported Models" tables in readme, hard to know what values to put in the env file to limit scope to specific brands and models.

### Possible solution

Please create tables in the README.md for all supported brands and all supported models so we know what format to use in the .env file to better filter for the specific cards we want. Since some of us may have no interest in PNY or Zotac 3080 cards, and more specifically may only be interested in EVGA FTW3 but not other EVGA models, I'm sure the tool is wasting a ton of CPU and network cycles (and site hits/traffic) searching for cards that won't be purchased.

**Comment by pntless** [comment]
#354 Does this but hasn't been merged yet.

**Comment by pntless** [comment]
#351 does this but hasn't been merged yet.
