### ISSUE TITLE
FI/DK RTX 3090 FE API ID is incorrect, constant false positives

### ISSUE THREAD

**Issue by AssiveMass** [jef/nvidia-snatcher#360]
### Description

Using `STORES` `nvidia-api` , `COUNTRY` `finland` (supposedly `denmark` too) the snatcher is constantly making false positives. The API link directs to [this site](https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_gb/EUR/5438793500?_=1601299146168) which is for the FI/DK 3090 NVLink bridge. That product is in stock, thus the positive alerts.

### Possible solution

Change the ID to a correct one. Unfortunately I'm not a software engineer or developer, so I don't have the knowhow to find the ID myself. If someone knows how to find it, please help me out.

**Comment by andrewmackrodt** [comment]
Thanks for reporting this @AssiveMass, unfortunately I was not able to find an id for the 3090. I've created a pull request to remove the incorrect ids to remove the false positives in #361; if you come across the correct id please let us know!

**Comment by AssiveMass** [comment]
@andrewmackrodt Hi! Seems that Nvidia/Digital River added the 3090 FE to FI/DK api. Here's the [link](https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_gb/EUR/5438793200)
