### ISSUE TITLE
Prevent snatcher from adding multiple cards in cart when a website stocks it

### ISSUE THREAD

**Issue by feelsole** [jef/nvidia-snatcher#367]
### Description

Right now when a website gets cards in stock, my browser goes crazy and adds every single available listing into my cart. I'd love to just limit it to one so I don't accidentally purchase multiples.

**Comment by jef** [comment]
https://github.com/jef/nvidia-snatcher/commit/c7a716f981976a76afe61a4d985bd6fe4343595b
https://github.com/jef/nvidia-snatcher/commit/7ef9d935c6858749fee25d92d97c64e486d486b8
https://github.com/jef/nvidia-snatcher/pull/325
