### ISSUE TITLE
[nvidia-api] [nvidia (3080)] founders edition :: STATUS CODE ERROR 504

### ISSUE THREAD

**Issue by poly-mathic** [jef/nvidia-snatcher#373]
![image](https://user-images.githubusercontent.com/28655581/94496682-0b041700-01c3-11eb-98b6-0d57f2309357.png)

Status Code Error 504 for the past few hours. 
Tried adding this code to Lookup.ts 
it worked for about 5 minutes until it started throwing 502 errors instead. 

> if (response?.status() === 504) {
> 		const client = await page.target().createCDPSession();
> 		await client.send('Network.clearBrowserCookies');
> 		await client.send('Network.clearBrowserCache');
> 		return;

**Comment by tsumeone** [comment]
the api is down.  it was up for a few minutes (probably coincidentally when you made that change) and has been down again ever since

**Comment by BROKENMIND617** [comment]
@poly-mathic curious to how you are viewing the list in your post. Also do you know of a bot for pinging Bestbuy  & adding 3090 to cart?  Is it possible that Nvidia have changed API domain?

**Comment by BROKENMIND617** [comment]
Got it TY.

**Comment by jef** [comment]
Thanks @tsumeone!
