### ISSUE TITLE
EVGA and Nvidia stopped showing up on log

### ISSUE THREAD

**Issue by tdowski** [jef/nvidia-snatcher#379]
I ran it last night and all the sites showed up.  I woke up and those 2 sites just vanished from the run log.  I didn't change anything, did an update, stopped it and reran it.  they are both in the stores line.  They are just not coming up anymore.  Any possible solutions?

**Comment by BROKENMIND617** [comment]
search Issues. duplicate  This has been outlined before. API is down. Hopefully it will come back up. Its been down since last late night Est.

**Comment by tdowski** [comment]
I am aware that the api is down, but it still doesn't even show up in the run log.  Usually it still shows up with an error.  Also, that does not explain the EVGA portion missing

**Comment by veev-code** [comment]
I see this happen after running it for prolonged periods as well. Some stores will have their refresh threads seemingly die/vanish.

I'm not familiar with the implementation, but is it possible there's an uncaught exception killing a thread?

**Comment by tdowski** [comment]
Thank you.  I thought it was an error on the coding side.  Good to know its not unheard of.  It could be a sort of server bot protection implementation.  Thank you again.

**Comment by veev-code** [comment]
I think it might be an error on the coding side. I wouldn't resolve this unless there is a known duplicate somewhere else.
