### ISSUE TITLE
Nvidia Store add to Cart URL may no longer work

### ISSUE THREAD

**Issue by dadealus** [jef/nvidia-snatcher#38]
https://github.com/jef/nvidia-snatcher/blob/aa856c712107fadb34630aefd6578dc8950097c7/src/store/nvidia.ts#L4

about an hour ago the add to cart URL would give you the message could not add 3080 to cart as its out of stock... 

If you try the URL now takes you out of the cart and to a new page saying "Sorry, There was a Problem with your request."

Not sure this will still work once cards come in stock

**Comment by Hari-Nagarajan** [comment]
I have this working in my own repo (python): 

https://github.com/Hari-Nagarajan/nvidia-bot/blob/master/stores/nvidia.py

In short (from discord)
```
You use the access_token from https://store.nvidia.com/store/nvidia/SessionToken?format=json&callback=jQuery3510013225370692239835_1600463566842&locale=en_us&apiKey=9485fa7b159e42edb08a83bde0d83dia&currency=USD&_=1600463566843

to make this one: https://api.digitalriver.com/v1/shoppers/me/carts/active/line-items?callback=jQuery351024446555583743956_1600463465706&format=json&method=delete&token=0ac25d414f09b4dd1db4698972d82ce53d794652ff500cdd9a182a24101aebab64a37f11167f6436507a994ea9af4f98a9bd3156f155ab1025eac7ff1231bb0f92a32f9ec4ecf882e4d9d3854d423b08&_=1600463465708

that adds to a cart

then call this https://api.digitalriver.com/v1/shoppers/me/carts/active/web-checkout?token=0ac25d414f09b4dd1db4698972d82ce53d794652ff500cdd9a182a24101aebab64a37f11167f6436507a994ea9af4f98a9bd3156f155ab1025eac7ff1231bb0f92a32f9ec4ecf882e4d9d3854d423b08
and that redirects you to the nvidia page with the item in the cart

```

**Comment by brybry77104** [comment]
Does this token method still work? I'm seeing a cors error, I think they may have added some security to secure this endpoint.

**Comment by Ascendin81** [comment]
Use:

https://store.nvidia.com/store?Action=AddItemToRequisition&SiteID=nvidia&Locale=en_US&productID=5438481700&quantity=1
