### ISSUE TITLE
newegg reporting 503 after running for a while

### ISSUE THREAD

**Issue by pntless** [jef/nvidia-snatcher#380]
### Description

After running snatcher for a while, newegg begins firing off 503 errors. Killing snatcher and restarting it clears the error and allows snatcher to scrape newegg again for a while until the error returns. Rinse, repeat ad nauseum.

This is new behavior as of today. I have not previously had this issue with newegg.

I tried slowly backing off on the sleep times but so far that has been ineffective.

Several other people in discord chat have reported the same issue.

### Possible solution

Per Andrew's suggestion on the Discord, I have added the line from #340 to backoff on 503s from the zotac.ts to the newegg.ts but his assessment, and mine, is that this is unlikely to solve the issue.

I will update either way after running it with that line in newegg.ts for a while.

**Comment by pntless** [comment]
As expected, applying the backoff logic to newegg 503s does not clear them.

**Comment by gonkar193** [comment]
Same issue here. Starts almost immediately after starting snatcher. I am running on a VPN and have tried multiple different IPs and immediately get 503'd just for newegg.

**Comment by Hunter2205** [comment]
I can also confirm this issue with newegg.  seems to be working fine with best buy though.

**Comment by gonkar193** [comment]
> I can also confirm this issue with newegg. seems to be working fine with best buy though.

It's been working fine for me now for the last hour, I'm pretty sure newegg itself had an issue.

**Comment by pntless** [comment]
Yeah, this behavior has stopped for me as well. I haven't seen it in a few hours now after it went on for most of the day. If anyone else that was having the problem could chime in and confirm if their issues have resolved that'd be great and I'll close it. Otherwise, I'll leave it open for a bit and make sure I don't see any additional complaints her or on the discord before I close.

**Comment by Hunter2205** [comment]
still having the issue here.  restart snatcher and it works for a period of time.

**Comment by gonkar193** [comment]
> Yeah, this behavior has stopped for me as well. I haven't seen it in a few hours now after it went on for most of the day. If anyone else that was having the problem could chime in and confirm if their issues have resolved that'd be great and I'll close it. Otherwise, I'll leave it open for a bit and make sure I don't see any additional complaints here or on the discord before I close.

I spoke too soon. It was fine for an hour now it is doing it again.

**Comment by Hunter2205** [comment]
update: been running for about an hour now with no issues
