### ISSUE TITLE
bannedSellers Label not functioning?  Cannot filter 3rd party sellers

### ISSUE THREAD

**Issue by flatspotting** [jef/nvidia-snatcher#381]
Just trying to sort out how to use the bannedsellers or filter out the seller "deals2you" on amazon canada - as I get about 1000000 alerts a day on their overpriced scalper cards...

I was wondering how i use bannedSellers in the amazon-ca.js file 

Setting it up like below does not work for me:

> export const AmazonCa: Store = {
> 	labels: {
> 		captcha: {
> 			container: 'body',
> 			text: ['enter the characters you see below']
> 		},
> 		bannedSeller: {
> 			container: '#body',
> 			text: ['Deal2You']
> 		},
> 		inStock: {
> 			container: '#desktop_buybox',
> 			text: ['add to cart']
> 		}
> 	},

I have now also tried:

>import {Store} from './store';
>
> export const AmazonCa: Store = {
>     labels: {
>         bannedSeller: ['Deals2You','Stoneforged'],
>         captcha: {
>             container: 'body',
>             text: ['enter the characters you see below'],
>         },
>         inStock: {
>             container: '#desktop_buybox',
>             text: ['add to cart']
>         }
>     },

Or if that is not possible does this work?

Or... if it is possible, can we adjust the in stock label from:

> 			container: '#desktop_buybox',
> 			text: ['add to cart']

To:

> 			container: '#desktop_buybox',
> 			text: ['Fulfilled by Amazon','Ships from and sold by Amazon']

**Comment by nikoramiro** [comment]
Curious about this too, couldn't get it to work properly either and I haven't been able to find any documentation regarding this.

**Comment by dpgagnon** [comment]
The names need to be all lowercase, as the current implementation makes the HTML's text lowercase before comparison but does not to the same for the strings in the `bannedSeller` label.

The following works for me in `amazon-ca.ts`:

```		
bannedSeller: {
   container: '#desktop_buybox',
   text: ['stoneforged', 'greatestdeals', 'deals2you']
}
```

**Comment by flatspotting** [comment]
> The names need to be all lowercase, as the current implementation makes the HTML's text lowercase before comparison but does not do the same for the strings in the `bannedSeller` label.
> 
> The following works for me in `amazon-ca.ts`:
> 
> ```
> bannedSeller: {
>    container: '#desktop_buybox',
>    text: ['stoneforged', 'greatestdeals', 'deals2you']
> }
> ```
> 
> This took me a while to figure out as well.

Youre my hero

**Comment by nikoramiro** [comment]
Thanks a lot for the help @dpgagnon, I was going crazy getting a notification for goddamn Stoneforged every 2 minutes.
