### ISSUE TITLE
evga 3090 not pulling for bestbuy-ca, and newegg-ca

### ISSUE THREAD

**Issue by drunknfoo** [jef/nvidia-snatcher#388]
got around to getting this running and didn't pay much attention, just noticed that none of the 3090 evga cards are being scanned for the canadian websites

(sorry, maybe should have flagged as enhancement and not bug)

**Comment by jef** [comment]
> (sorry, maybe should have flagged as enhancement and not bug)

No worries! Sounds good. I'm sure someone will get around to adding links. If not, I will the future.

Thanks!

**Comment by karmanbadhesha** [comment]
is there links to bestbuy-ca 3090 evga cards? I could not find any @drunknfoo
