### ISSUE TITLE
Add method to filter out scalpers

### ISSUE THREAD

**Issue by ultimateguy** [jef/nvidia-snatcher#391]
I woke up to a ton of notifications of this same scalper selling on amazon.ca
https://www.amazon.ca/dp/B08HH5WF97

Is there a way to filter out these types of listings? Min/max price? Blacklist?

**Comment by g1forfun** [comment]
This is being worked on in the form of max price. See here: https://github.com/jef/nvidia-snatcher/pull/383

**Comment by karmanbadhesha** [comment]
`	labels: {
		captcha: {
			container: 'body',
			text: ['enter the characters you see below']
		},
		inStock: {
			container: '#desktop_buybox',
			text: ['add to cart']
		},
		bannedSeller: {
			container: '#desktop_buybox',
			text: ['stoneforged', 'greatestdeals', 'deals2you']
		}
	},`

add that to your /src/store/amazon-ca.ts

**Comment by ultimateguy** [comment]
@karmanbadhesha That seems to do the trick. Thanks! :)

**Comment by karmanbadhesha** [comment]
@ultimateguy I'd still keep an eye out for #383 because right now there is the possibility for a 3rd party to list their card at a reasonable price and we wouldn't see it, but this works for now.

**Comment by jef** [comment]
We added `MAX_PRICE` (https://github.com/jef/nvidia-snatcher/pull/383) and added the label `bannedSeller` (although not in use: https://github.com/jef/nvidia-snatcher/pull/173). This should help with clearing this up.

We can go ahead and close this out and create issues for sellers that continually pop up. As well as an issue for creating the `BANNED_SELLERS` variable.
