### ISSUE TITLE
No longer seeing indicator of running

### ISSUE THREAD

**Issue by anewlight90** [jef/nvidia-snatcher#393]
### Description

On older version of NVIDIA snatcher I was seeing the constant checks running against all the different vendors.  Now it shows me my current .env config but nothing else
![snatcher](https://user-images.githubusercontent.com/72107133/94712718-b5348980-02fe-11eb-9e08-3e601d66f3e6.PNG)

### Possible solution

A loading bar, or a list of sites/cards that are being checked and refreshing status.  As it stands I have no idea if it's running.

Thanks for all your hard work!

**Comment by andrewmackrodt** [comment]
It should already work as described, I think you have a problem with your `.env` file. The line `selected models: ""` seems to be limiting lookup to an empty set of models, try removing the line `SHOW_ONLY_MODELS=`.

**Comment by anewlight90** [comment]
That was it!  I actually somehow removed one of the " marks somehow in the SHOW_ONLY_MODELS=, adding the second mark fixed this issue.  Thank you!!
