### ISSUE TITLE
Pushbullet has a high-risk vulnerability

### ISSUE THREAD

**Issue by cameroncasanova** [jef/nvidia-snatcher#397]
### Description

After running "npm install" on the latest commit, there was a high risk vulnerability discovered. It has to do with the version of "node-forge" that is required by pushbullet. The npm audit log is as follows:

`  High            Prototype Pollution in node-forge

  Package         node-forge

  Patched in      >= 0.10.0

  Dependency of   pushbullet

  Path            pushbullet > node-forge

  More info       https://npmjs.com/advisories/1561

found 1 high severity vulnerability in 963 scanned packages
  1 vulnerability requires manual review. See the full report for details.`

### Possible solution

I modified the code to completely remove pushbullet for now. I can push that if needed, but I imagine that is not ideal.
Alternatively some tweaks could probably be made to ensure pushbullet requires a version of node-forge >= 0.10.0

**Comment by SeanSeanySean** [comment]
I also have this same problem. Should I roll back for now?

**Comment by cameroncasanova** [comment]
> I also have this same problem. Should I roll back for now?

I noticed that this version of pushbullet, which uses the high-risk version of node-forge has been in this repo for at least 7 days. The reason this was only detected now was because the vulnerability was not reported until today, 09/30. So rolling back won't help unless you go far enough back to before pushbullet was added. But at that point I'm sure other issues have been fixed and it probably wouldn't even be worth it.

**Comment by ringnex1** [comment]
yep have the same issue not sure what to do

**Comment by qazikm** [comment]
Also getting this, if someone could let me know what to do I would appreciate it.

**Comment by ringnex1** [comment]
ok guys i figured it out, that risk doesnt matter just ignore that completely and move to the next step watch the video carefully https://www.youtube.com/watch?v=bVgIpjBkRLY

**Comment by jef** [comment]
Updated in #406
