### ISSUE TITLE
Ping different roles on Discord depending on card

### ISSUE THREAD

**Issue by TheWizardofGauze** [jef/nvidia-snatcher#409]
I just finished setting up snatcher to ping people on my friend's Discord server when there's stock, and was wondering if it's possible to allow us to set it up so that depending on which card is in stock, different people get pinged since everyone wants different cards.

I don't know how easy or hard this would be to implement or how it would affect the usability in terms of configuring snatcher, but I figured it couldn't hurt to suggest.

**Comment by jef** [comment]
-- | -- | --
DISCORD_NOTIFY_GROUP | Discord group you would like to notify | Can be comma separated, use role ID, E.g.: <@2834729847239842>
DISCORD_WEB_HOOK | Discord Web Hook URL | Can be comma separated, use whole webhook URL
