### ISSUE TITLE
Can we have Asus Germany Featured Please?

### ISSUE THREAD

**Issue by LOX311** [jef/nvidia-snatcher#412]
That would be nice if its no too much work for you guys.
other than that thank you for the awsome bot!

[](https://webshop.asus.com/de/komponenten/grafikkarten/nvidia-serie/2829/asus-rog-strix-rtx3080-o10g-gaming)

**Comment by LOX311** [comment]
https://webshop.asus.com/de/komponenten/grafikkarten/nvidia-serie/2829/asus-rog-strix-rtx3080-o10g-gaming

**Comment by danmaxis** [comment]
@jef do you plan adding more stores from forked repos to the main repo?
Thx

**Comment by jef** [comment]
Only if people contribute. Don't have much time to go through forks and add. And contributing is fairly easy as well. If you have a list of sites though feel free to add here and I can add em in!
