### ISSUE TITLE
Google Number?

### ISSUE THREAD

**Issue by EchoJoker** [jef/nvidia-snatcher#413]
### Description

I know it might be a lower priority but most of the day I do not have my phone on me but I have access to google hangouts. Is there a way to add Google numbers to the carriers section?

### Possible solution

Adding Google number to Carriers so SMS can be received on Google numbers

**Comment by jstevenson72** [comment]
Can't you just setup Twilio and have it send an SMS to your Google phone #?  It's working for me on my CricketWireless

**Comment by EchoJoker** [comment]
Not sure if my work environment allows Twilio. Going off what I know.

**Comment by EchoJoker** [comment]
@jstevenson72 

Is there a guide to add a number on Twilio then link it to Snatcher? Would be useful for all the non-listed carriers if that si what you did.

**Comment by jstevenson72** [comment]
I just saw the fields in the .env file, and went to Twilio.com and signed
up for a free account.

It was only a few steps, verifying my email and phone number, then copied
the auth I'd and another item from the Dashboard.

You have to click Request Trial Number button on their website, and it will
assigned you a new number.

Then in the .env put that number in the From field and your real # in the
To field.

Save the .env and then run the npm test: notification to test it.

I'm going from memory here but that is about it I think.

**Comment by jeckerman** [comment]
> @jstevenson72
> 
> Is there a guide to add a number on Twilio then link it to Snatcher? Would be useful for all the non-listed carriers if that is what you did. Also, it would solve the additional number to Snatcher issue.

Go to Twilio and sign-up for a free trial account

- Go here: https://www.twilio.com/try-twilio
- Sign-up
- It'll ask you to reserve a number shown, accept that
- At your dashboard you'll see:
```
   TRIAL NUMBER:
   +18884443333

   ACCOUNT SID
   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

   AUTH TOKEN
   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

- Open the `.env` file in nvidia-snatcher
- Fill in the fields below:
```
TWILIO_ACCOUNT_SID="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TWILIO_AUTH_TOKEN="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TWILIO_FROM_NUMBER="18884443333"
TWILIO_TO_NUMBER="15551234321"
```
- `TWILIO_ACCOUNT_SID` - The `ACCOUNT SID` shown in the Twilio Dashboard
- `TWILIO_AUTH_TOKEN` - The `AUTH TOKEN` shown in the Twilio Dashboard
- `TWILIO_FROM_NUMBER` - The trial number Twilio gave you
- `TWILIO_TO_NUMBER` - Your google number

Then you should be good to go

**Comment by jef** [comment]
Closing, but feel free to discuss still. Thank you all!!!

**Comment by MRizkBV** [comment]
Is Twilio free? I wanted to use it but I saw they charge around 0.7 cents per text for the US, and a lot more for international ones.

**Comment by jstevenson72** [comment]
They gave me $15 free, so should cover my 3080 needs
