### ISSUE TITLE
Can't 'npm install' on Mac

### ISSUE THREAD

**Issue by Rhylen** [jef/nvidia-snatcher#414]
When I run npm install I get errors, I have already run npm install with any root directories
OS version 10.15.7

--Terminal--
rhylen@Rhylens-MBP ~ % node -v
v14.13.0
rhylen@Rhylens-MBP ~ % npm -v
6.14.8
rhylen@Rhylens-MBP ~ % git --version
git version 2.27.0
rhylen@Rhylens-MBP ~ % npm install ./documents/GitHub/nvidia-snatcher
npm WARN saveError ENOENT: no such file or directory, open '/Users/rhylen/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/rhylen/package.json'
npm WARN rhylen No description
npm WARN rhylen No repository field.
npm WARN rhylen No README data
npm WARN rhylen No license field.

+ nvidia-snatcher@1.5.0
updated 1 package and audited 452 packages in 1.903s

12 packages are looking for funding
  run `npm fund` for details

found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by andrewmackrodt** [comment]
You need to run `npm install` within the project directory, it does not take the project directory as an argument, i.e.

```sh
cd ~/documents/GitHub/nvidia-snatcher
npm install
```
