### ISSUE TITLE
ASUS site not being searched

### ISSUE THREAD

**Issue by dochodges** [jef/nvidia-snatcher#418]
### Description

ASUS site not showing in powershell search

Attached is my configuration. Seems correct based on readme but asus site not searched for stock. 

I am also seeing amazon ftw3 listed as connection timeout despite copying the link and pasting in chrome taking me directly to the correct site. 

3rd issue I am seeing is navigation timeout to nvidia

Sorry I realize this is likely user error but for the life of me I cant figure out what I did wrong here. 

I also welcome and configuration changes that may also be messed up. 

`# ** All configuration variables are optional **
# Read https://github.com/jef/nvidia-snatcher#customization for help on customizing this file
#############################################################################################
COUNTRY="usa"
EMAIL_USERNAME="myemail@gmail.com"
EMAIL_TO="myemail@gmail.com"
EMAIL_PASSWORD="mypassword"
HEADLESS=""
IN_STOCK_WAIT_TIME=""
LOG_LEVEL=""
LOW_BANDWIDTH=""
MICROCENTER_LOCATION=""
NVIDIA_ADD_TO_CART_ATTEMPTS=""
NVIDIA_SESSION_TTL=""
OPEN_BROWSER="true"
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN=""
PAGE_SLEEP_MAX=""
PAGE_TIMEOUT=""
PHONE_NUMBER="8675309"
PHONE_CARRIER="att"
PLAY_SOUND="promise.mp3"
SCREENSHOT="false"
SHOW_ONLY_BRANDS="evga,asus,nvidia,gigabyte"
SHOW_ONLY_MODELS="rog strix,rog strix oc,strix,ftw3,ftw3 ultra,aorus master,founders edition"
SHOW_ONLY_SERIES="3080"
STORES="nvidia,amazon,asus,bestbuy,evga,microcenter,newegg,nvidia-api"
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"`

**Comment by jef** [comment]
This is your `.env-example`.

https://github.com/jef/nvidia-snatcher#quick-overview

> - Copy `.env.example` to a new file `.env` and edit the `.env` file to your liking using your [favorite text editor](https://code.visualstudio.com/)
>    - More on this in [customization](#Customization)

**Comment by dochodges** [comment]
Jef I posted the .env According tot he overview it is correct but yet not working as defined which is why I posted it as a bug. Are you saying that the asus store and other issue ive posted are not happening with your configuration?

**Comment by jef** [comment]
You need to add `asus` to `STORES`

E.g., `STORES="asus,nvidia,amazon"`

It seems like you posted your `.env-example`, not `.env`. Sorry if I misunderstood.

I would also remove or comment (`#`) your `SHOW_ONLY_*` variables just to test. I would start with the most minimal config and work up from there just to ensure it's your environment.

**Comment by dochodges** [comment]
> You need to add `asus` to `STORES`
> 
> E.g., `STORES="asus,nvidia,amazon"`
> 
> It seems like you posted your `.env-example`, not `.env`. Sorry if I misunderstood.
> 
> I would also remove or comment (`#`) your `SHOW_ONLY_*` variables just to test. I would start with the most minimal config and work up from there just to ensure it's your environment.

@jef thanks for the reply.  I should have been more clear. The attached file is the .env not the example. I just left a few blank as default was fine. asus is included in the stores. Ive also removed the variables you said and still asus store is not being searched for me. Other stores are working fine.

**Comment by jef** [comment]
Awesome! Good to hear.

Also be careful of asus, I've already been IP banned from their store. Lol...

> Is there a way to speed the searching up as in increase the refresh rate of the stores?

Not on your end, except for some of the wait time environment variables. I've been thinking about making the page requests in parallel, as it may not effect timeouts/IP bans. I'll be posting that in a PR or Discord if we end up doing that.

Thanks!
