### ISSUE TITLE
Multiple errors thrown. No such file or directory

### ISSUE THREAD

**Issue by tempee** [jef/nvidia-snatcher#422]
### Description

Multiple errors are being thrown. Running on MacBook Pro on 10.15.7 Catalina
Figured an image would be easiest for you to see.

https://imgur.com/wyTuI1Z

**Comment by andrewmackrodt** [comment]
You've not followed the instructions correctly and have changed directory `cd` before cloning. Consequently, you should be in the directory `~Desktop/nv/nvidia-snatcher` before running `npm install` and `npm run start`.
