### ISSUE TITLE
Add Best Buy listings for FTW and FTW3 Ultra

### ISSUE THREAD

**Issue by armsteullion** [jef/nvidia-snatcher#423]
Best buy (US) added listings for FTW and FTW3 Ultra:

FTW3: 
https://www.bestbuy.com/site/evga-geforce-rtx-3080-10gb-gddr6x-pci-express-4-0-graphics-card/6436191.p?skuId=6436191

FTW3 Ultra:
https://www.bestbuy.com/site/evga-geforce-rtx-3080-10gb-gddr6x-pci-express-4-0-graphics-card/6436196.p?skuId=6436196

**Comment by pntless** [comment]
#421 but isn't merged yet.
