### ISSUE TITLE
psa: MAX_PRICE default in .env-example uses incorrect quotation marks

### ISSUE THREAD

**Issue by xninjax** [jef/nvidia-snatcher#428]
### Description

For those wanting to use MAX_PRICE feature [_commit  `feat: max price filtering` (#383)_]

The following line in .env-example uses the incorrect quotation marks (curly quotes)
> `MAX_PRICE=“”`

Please change this line to use normal quotes (straight quotes) around your supplied price  
>`MAX_PRICE=""`

eg. `MAX_PRICE="1200"`

### Solution
Pull #426 will fix this in the repository

**Comment by jef** [comment]
Fixed! Thanks @xninjax :heart:
