### ISSUE TITLE
Did default logging level get changed?

### ISSUE THREAD

**Issue by jmredmon** [jef/nvidia-snatcher#429]
### Description

I updated the to the newest code today, but was surprised when it appeared that the program wasn't functioning anymore due to not spitting out updates when it was searching each store. I changed logging level to "silly" to make sure the program was still working - it was. 

Was this an intentional change? I'm happy that it is working, just figured I'd let you all know.

**Comment by jef** [comment]
> I updated the to the newest code today, but was surprised when it appeared that the program wasn't functioning anymore due to not spitting out updates when it was searching each store

It should be displaying OOS or whatever else. Kind of strange that this is the case. I'm on latest right now and it's working.

Could be a bug in the version of main that you pulled. Mind trying a new version and seeing what happens? Leave `LOG_LEVEL=info`.

**Comment by jmredmon** [comment]
Fresh installation today works correctly, I did double-check and the version I got fresh yesterday definitely had the out-of-stock messages as "debug" instead of "info", however it appears to be fixed now.

**Comment by jef** [comment]
Strange... Glad it's resolved.
