### ISSUE TITLE
Search specific MicroCenter location for stock 

### ISSUE THREAD

**Issue by Hale2j** [jef/nvidia-snatcher#43]
### Description

Search specific MC locations and leverage their search page to view all local inventory. 
https://www.microcenter.com/search/search_results.aspx?N=&cat=&Ntt=3080

If possible, this would allow local residents to use this as notification to get to a store.

### Possible solution
?

**Comment by dadealus** [comment]
I'm not sure this is going to work out for you. most of the Microcenters around me update the site stock at the end of the day after the truck has delivered the items to the store.... and people are checking in daily for shipments... so the likely hood of a card being instock locally, showing in stock online, and still being in stock when you get there is pretty much 0

**Comment by lukechen526** [comment]
When I was working on my own bot I found out that you can set the store by passing “storeid=“ in the query to set the store.
