### ISSUE TITLE
Bypassing a Store?? [nvidia] nvidia founders edition - Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by Getyourcardnow** [jef/nvidia-snatcher#430]
Where can I modify the code to skip certain stores? I would like to get rid of the Nvidia store because it hits the navigation timeout and I can't see the code looking at other stores.

Thank you and great work!

**Comment by jstevenson72** [comment]
You don't need to "bypass" a store, simply exclude it from your configuration.  You define the list of stores to use in the .env file.  If you haven't, then it is using only the NVIDIA store by default.

https://github.com/jef/nvidia-snatcher#supported-stores

**Comment by Getyourcardnow** [comment]
> You don't need to "bypass" a store, simply exclude it from your configuration. You define the list of stores to use in the .env file. If you haven't, then it is using only the NVIDIA store by default.
> 
> https://github.com/jef/nvidia-snatcher#supported-stores

Wow my fiance' is right. I need glasses. Can't believe I didn't see that when looking through the wiki to edit the .env. Thank you!
