### ISSUE TITLE
Amazon Status Code Error 503?

### ISSUE THREAD

**Issue by iscmarkiemark** [jef/nvidia-snatcher#441]
Not sure if this is just me, or even an actual bug, but Amazon just keeps hitting me with Status code error 503?

**Comment by undaunt** [comment]
I'm assuming we're getting 503s due to spamming Amazon. If I run a new instance of the tool on my PC separate from my remote server, no issues, as we likely haven't been rate limited as of yet. Not sure if pinging amazon less or some other workaround is required.

**Comment by jef** [comment]
That's correct. Also, update your `USER_AGENT`. This will help with captcha.
