### ISSUE TITLE
Microcenter false alerts

### ISSUE THREAD

**Issue by Ghoddy** [jef/nvidia-snatcher#442]
### Description

 Microcenter keeps flagging the Asus TUF for being in stock even though it isnt. 

 It keeps taking me to this page of asus https://www.microcenter.com/product/628303/asus-geforce-rtx-3080-tuf-gaming-triple-fan-10gb-gddr6x-pcie-40-graphics-card/?storeid=029

Running Windows 10

**Comment by landonairey** [comment]
It's actually in stock in IL and MI if you select a store. Maybe this should be a feature request to search stock for specific store locations

**Comment by undaunt** [comment]
You may already choose a store for MC, I believe I have mine set to 'web' but I'm still getting these alerts.

**Comment by landonairey** [comment]
Good point, I see the MICROCENTER_LOCATION parameter now but where is the listed of supported places you can specify?

**Comment by undaunt** [comment]
There is a list in the docs right by country.

**Comment by landonairey** [comment]
That was a polite way of saying read the damn readme, I see it now!

**Comment by Ghoddy** [comment]
Is there a way to have it as online only? I don't have a microcenter near me to set the script to.

**Comment by undaunt** [comment]
@Ghoddy set it to web, though I believe there is currently a bug with it reporting specific stores even when on web as noted above.

**Comment by Ghoddy** [comment]
@undaunt In the script i have it set to web, but am still getting a lot of flags for in stock.

**Comment by undaunt** [comment]
Yes, that is the issue at hand. I've temporarily disabled searching Microcenter as I woke up to 800 new emails.

**Comment by Ghoddy** [comment]
Thanks for the quick response! Will wait for a fix

**Comment by jef** [comment]
Closing this because Micro Center will not be selling 3000 series cards online for _months_. They will only be available in store. I would suggest that you not look for them through `web` until down the road.

**Comment by theboomr** [comment]
So uh, should I assume that the "devin" store name is a typo? I'm assuming it's meant to be "denver" since that's not in the list.

**Comment by jef** [comment]
I thought this was fixed. I'll make sure it's update. Thanks @theboomr.

**Comment by hifihedgehog** [comment]
Now, I am not getting alerts for ANY products. Ruh roh...

https://github.com/jef/streetmerchant/issues/1753
