### ISSUE TITLE
nvidia-api status code error 504

### ISSUE THREAD

**Issue by landonairey** [jef/nvidia-snatcher#443]
The nvidia-api keeps returning error 504:

`[9:48:24 AM] warn :: [] [nvidia-api] [nvidia (3080)] founders edition :: STATUS CODE ERROR 504`

Modified parameters are:

```
IN_STOCK_WAIT_TIME="10"
PAGE_TIMEOUT="0"
SHOW_ONLY_MODELS="founders edition"
SHOW_ONLY_SERIES="3080"
STORES="nvidia,nvidia-api"
```

**Comment by welcometopwn** [comment]
I think Nvidia takes the API down since there is no stock anyways, it will work when the API is up again.
