### ISSUE TITLE
Errors on browser argument type

### ISSUE THREAD

**Issue by PotLid** [jef/nvidia-snatcher#445]
### Description

`src/index.ts:57:22 - error TS2345: Argument of type 'import("MY PATH I HIDE IT CUZ ITS PERSONAL"/rtx/nvidia-snatcher/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").Browser' is not assignable to parameter of type 'import("MY PATH I HIDE IT CUZ ITS PERSONAL"/rtx/nvidia-snatcher/node_modules/@types/puppeteer/index").Browser'.`

```
src/index.ts:61:36 - error TS2345: Argument of type 'import("MY PATH I HIDE IT CUZ ITS PERSONAL"/rtx/nvidia-snatcher/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").Browser' is not assignable to parameter of type 'import("MY PATH I HIDE IT CUZ ITS PERSONAL"/rtx/nvidia-snatcher/node_modules/@types/puppeteer/index").Browser'.

61  		promises.push(fetchLinks(store, browser));
```

Seems like TypeScript browser variable has wrong typing

macOS

**Comment by jef** [comment]
Make sure you don't have any changes that could affect this. I'd also do a `npm ci` then a `npm run start`.

**Comment by PotLid** [comment]
I even didn't touch the code itself. I just kinda did some getting around trick that, change index.ts to index.js so I ts doesn't do type checking, only that I have to remove array type for args variable.

**Comment by PotLid** [comment]
Well I just tried npm instead yarn. Now it works.
