### ISSUE TITLE
ERROR 503 ON NEWEGG

### ISSUE THREAD

**Issue by kaoztheory** [jef/nvidia-snatcher#456]

**Comment by zerocarbthirty** [comment]
Just fyi, nowinstock.net notified me at 2:06PM EST that the EVGA FTW3 ultra gaming was in stock at Newegg and as far as I can tell snatcher completely missed it. I reported this in another bug report and it was closed.

**Comment by kaoztheory** [comment]
> Just fyi, nowinstock.net notified me at 2:06PM EST that the EVGA FTW3 ultra gaming was in stock at Newegg and as far as I can tell snatcher completely missed it. I reported this in another bug report and it was closed.

Saw that too!

**Comment by ThisIsPita** [comment]
> 
> 
> Just fyi, nowinstock.net notified me at 2:06PM EST that the EVGA FTW3 ultra gaming was in stock at Newegg and as far as I can tell snatcher completely missed it. I reported this in another bug report and it was closed.

This is a known bug with Newegg where it glitches out and confuses some bots. There wasn't actually any stock.

**Comment by zerocarbthirty** [comment]
I havent had a single newegg hit in a week. I guess I cant really say that
its missing them I just assume there have been > 0 is there an
authoritative list of drops somewhere? lol

**Comment by ThisIsPita** [comment]
I believe there was an issue that was supposedly fixed with [#433  ](https://github.com/jef/nvidia-snatcher/pull/433#issue-497219790)

**Comment by zerocarbthirty** [comment]
Is that part of what you pull down when you pull the source? Ive been
refreshing the code every 4 hours or so because I noticed you guys updated
the code between releases.

**Comment by ThisIsPita** [comment]
I haven't actually contributed to the project just trying to help you out. You should be getting all the updates when you pull the latest source, yes.
