### ISSUE TITLE
ASUS returning error code 403

### ISSUE THREAD

**Issue by millionhari** [jef/nvidia-snatcher#463]
### Description

ASUS is returning a 403 when scraping their site.

![Screen Shot 2020-10-06 at 4 41 01 PM](https://user-images.githubusercontent.com/5927440/95271502-e297a080-07f2-11eb-9d75-0acf106f5a2e.png)

Mac OS Mojave 10.14.6

**Comment by jef** [comment]
You probably got banned. Go look at one of the URLs.

**Comment by michaelv2** [comment]
I'm getting 403 errors from Asus as well on the very first request after launching the script for the first time. I'm able to navigate to their graphics card URLs through a browser from the same IP.

**Comment by jef** [comment]
Update your `USER_AGENT`

**Comment by jxjftw** [comment]
This isn't a bug, those pages aren't being served from asus currently - they got tired of people scraping all day.

**Comment by jef** [comment]
Thanks for the help @jxjftw. I can't test too well since I'm banned 😅
