### ISSUE TITLE
Scraping for upcoming EVGA models: HYBRID, KINGPIN, K|NGP|N, HYDRO COPPER

### ISSUE THREAD

**Issue by TunaErtemalp** [jef/nvidia-snatcher#478]
These models from EVGA will be out mid- to late November, per a tweet by https://twitter.com/EVGA_JacobF (https://twitter.com/EVGA_JacobF/status/1313673778145030145). It would be nice to allow the addition of "HYBRID, KINGPIN, K|NGP|N, HYDRO COPPER" to SHOW_ONLY_MODELS environment variable right now so that the script would be catching the first availabilities on stores...

Tuna

**Comment by jxjftw** [comment]
> These models from EVGA will be out mid- to late November, per a tweet by https://twitter.com/EVGA_JacobF (https://twitter.com/EVGA_JacobF/status/1313673778145030145). It would be nice to allow the addition of "HYBRID, KINGPIN, K|NGP|N, HYDRO COPPER" to SHOW_ONLY_MODELS environment variable right now so that the script would be catching the first availabilities on stores...
> 
> Tuna

Unfotunately, that's not how the scraper works. Those show only model values are linked to actual model names in the store.ts files. The scraper will only search exact url's on store pages.

For instance, these are pulled from the newegg.ts src file -

{
			brand: 'evga',
			cartUrl: 'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814487518',
			model: 'ftw3 ultra',
			series: '3080',
			url: 'https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3897-kr/p/N82E16814487518'
		},
		{
			brand: 'evga',
			cartUrl: 'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814487519',
			model: 'ftw3',
			series: '3080',
			url: 'https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3895-kr/p/N82E16814487519'
		},

You see the models listed here, which is what you define you want to search for in your .env file. To scrape for kingpin, hydrocopper, etc. we will need the actual store URL's to hit to look for stock.

**Comment by TunaErtemalp** [comment]
Thank you! Now I know.
