### ISSUE TITLE
Perhaps issue a disclaimer within README.md about nvidia-snatcher's data usage

### ISSUE THREAD

**Issue by naterobbified** [jef/nvidia-snatcher#479]
### Description

So this may not be an issue for all, but I have Cox as my ISP in Arizona which implemented data caps about a year ago. I'm currently limited to 1.75 TB of data per month before I have to start paying overage fees. Not understanding how the bot functions on the back end, I ran it all week to find all models of 3090 when they become available. I received an email earlier that was at 75% of my data usage. I checked my router and apparently I've used 1.5TB of data this week! I ran nvidia-snatcher and opened Task manager to look at disk usage and it peaks at 40MB/sec while its running, which obviously can add up.

### Possible solution

Perhaps mention in the README.md that this app can be a data hog so others don't run into the same issue.

**Comment by fatmoo5** [comment]
Definitely would not recommend running on home connection unless connected to a vpn to begin with. Sites tend to block ip addresses for botting.

**Comment by jef** [comment]
I'd recommend using `LOW_BANDWIDTH="true"`, that should help. But I also agree there should be this disclaimer.
