### ISSUE TITLE
enhancement: 

### ISSUE THREAD

**Issue by lmcke169** [jef/nvidia-snatcher#49]
Could the program have an option to list the time the line was created on each line. I keep having the software stop working and just sitting there and a time would definitely help make sure its still doing its thing at a glance.

**Comment by jeffreyflynt** [comment]
Just add a `console.log(new Date())` to the script

**Comment by lmcke169** [comment]
I attempted to add into the index.js but something is regenerating it every launch. Where exactly would that be added?

**Comment by admon84** [comment]
This is being worked on in https://github.com/jef/nvidia-snatcher/pull/48

**Comment by jef** [comment]
Fixed in #48
