### ISSUE TITLE
Test Notification

### ISSUE THREAD

**Issue by Polysable** [jef/nvidia-snatcher#505]
What's supposed to show when I run test:notification?   I don't get any errors. It just shows the green "nvidia-snatcher" logo but after that nothing happens. Does that mean the test is successful?

**Comment by ThatGirlll** [comment]
When I type npm start and so on into the command prompt, I get an instant window with text, but then it closes soon after without allowing me to read it and that's it. What's happening?

**Comment by AnolinMcGinnis** [comment]
> What's supposed to show when I run test:notification? I don't get any errors. It just shows the green "nvidia-snatcher" logo but after that nothing happens. Does that mean the test is successful?

If setup correctly, you'll get both an SMS and email notification on your gmail account and a text to your phone.

**Comment by Polysable** [comment]
> es

Weird. I don't get an email notification even though my email is listed in the .env  at "EMAIL_USERNAME" . 
"EMAIL_TO" and "EMAIL_PASSWORD" is blank but that's irrelevant to get an email if you do not have MFA, right?

So this should work...I don't know why it wouldn't send me an email. When I run the normal program, the store scanning works as intended. Shows me all the stores I have typed into the .env and lists them as "OUT OF STOCK".

**Comment by AnolinMcGinnis** [comment]
> > If setup correctly, you'll get both an SMS and email notification on your gmail account and a text to your phone.
> 
> Weird. I don't get an email notification even though my email is listed in the .env at "EMAIL_USERNAME" .
> "EMAIL_TO" and "EMAIL_PASSWORD" is blank but that's irrelevant to get an email if you do not have MFA, right?
> 
> So this should work...I don't know why it wouldn't send me an email. When I run the normal program, the store scanning works as intended. Shows me all the stores I have typed into the .env and lists them as "OUT OF STOCK".

Even without MFA, you should put your GMAIL password in there, otherwise it won't be able to authenticate.

**Comment by jef** [comment]
> Even without MFA, you should put your GMAIL password in there, otherwise it won't be able to authenticate.

That's correct. Email is sent to you, from you.

> What's supposed to show when I run test:notification

https://github.com/jef/nvidia-snatcher/blob/ed970fc397210eb6ff684c7e82c79eb685a5d0d9/src/notification/notification.ts#L14-L28

Everything in this block will be tested during `npm run test:notification`.

The reason why you didn't see anything, is because you don't have any notifications configured (missing email password).

---

Feel free to continue to talk, but I will close this ticket. Thanks!
