### ISSUE TITLE
MAX_PRICE_3080 not working 

### ISSUE THREAD

**Issue by MrRobot245** [jef/nvidia-snatcher#514]
### Description

For Amazon-Ca at least:
Got multiple notifications for a 1800 card when I set my limit to 1300, class selector looks like its still the correct one. Seems like a regression

**Comment by jef** [comment]
Interesting. I'll do some debugging when I get the chance. Thanks for the report.

**Comment by t-green** [comment]
+1 this happened to me 3 times today too, all Amazon.ca

**Comment by xninjax** [comment]
Issue found - 
In config.ts, series prices are looking for .env named "MAX_PRICE_3080"...
```
	maxPrice: {
		series: {
			3070: envOrNumber(process.env.MAX_PRICE_3070),
			3080: envOrNumber(process.env.MAX_PRICE_3080),
			3090: envOrNumber(process.env.MAX_PRICE_3090)........
```

But current .env the names are:

`MAX_PRICE_SERIES_3070=`
`MAX_PRICE_SERIES_3080=`
`MAX_PRICE_SERIES_3090=`

I changed the .env names to be `MAX_PRICE_3080`, and modified the test card to use the 3080 as its series.  This now works again 👍 

![image](https://user-images.githubusercontent.com/23090488/95914071-6f49dd80-0d62-11eb-96e1-7f8c9d51d9c4.png)


@jef  which convention to go with `MAX_PRICE_SERIES_xxxx=`  or  `MAX_PRICE_xxxx=`  ?

**Comment by t-green** [comment]
Good eye @xninjax I glossed right over that.

My 2cents: It's easier to update the config.ts variable names to MAX_PRICE_SERIES_XXXX so people can just do a pull, rather than having existing users edit their .env files manually.

**Comment by xninjax** [comment]
@t-green very much agree, I'll have a pull request queued and up shortly

**Comment by jef** [comment]
WHOOPS!
