### ISSUE TITLE
Twitch support?

### ISSUE THREAD

**Issue by fatmoo5** [jef/nvidia-snatcher#530]
add twitch support?

I was going to buy a dedicated server and figured I would stream it and it would be nice to post the link on twitch chat when something comes in stock

**Comment by jef** [comment]
Funny you ask... https://github.com/jef/nvidia-snatcher/pull/528

**Comment by fatmoo5** [comment]
tested out his script and says message sent but no message was actually sent.
https://i.imgur.com/J12ZFBC.png
