### ISSUE TITLE
adding Amazon.fr

### ISSUE THREAD

**Issue by random8748** [jef/nvidia-snatcher#535]
hello ,
i would like to ask you if you could add amazon.fr to nvidia snatcher plz?
here are the amazon asin list for amazon.fr :
**B08HBTJMLJ
B08HGYXP4C
B08HJ9XFNM
B08HGBYWQ6
B08HH1BMQQ
B08HGLN78Q
B08HBR7QBM
B08HM4M621
B08HN4DSTC
B08HHZVZ3N
B08HN7VVLJ
B08HN6KYS3
B08JCKYYL8
B08JCVWTQY
B08HLZXHZY
B08HN37VQK
B08HM4V2DH
B08HR1NPPQ
B08KH7RL89
B08KHLDS72
B08HJTH61J
B08HR6FMF3
B08HR4RJ3Q
B08HR55YB5
B08HR3DPGW
B08HR3Y5GQ
B08HR7SV3M
B08HR5SXPS
B0B08HH5WF
978HHDP9DW
B08HJNKT3P
** 
thanks for your work on this project

**Comment by CheesusTheOnly** [comment]
amazon is using the same ASIN for each of their sites (de, uk etc.)

Just edit the links in -> nvidia-snatcher\src\store\model\amazon-de.ts

.....".de" to ".fr" and you should be good to go

**Comment by random8748** [comment]
thanks for your help i just did what you said
