### ISSUE TITLE
Chromium memory leak?

### ISSUE THREAD

**Issue by SesioN** [jef/nvidia-snatcher#544]
### Description

I'm running your nvidia-snatcher together with https://github.com/jef/nvidia-snatcher/pull/534 and INCOGNITO=true.
I've noticed that the (main?) chrome process keeps constantly growing in memory usage. Yesterday there was a crash at some point but I sadly by mistake overwrote the logs files that contained details regarding that.

But I somehow doubt that the issue is within nvidia-snatcher or even puppeteer. 
I would assume that this is a chromium leak but I figured to ask for your opinion just to ensure that we can rule out nvidia-snatcher.

**OS:** Ubuntu 20.04 Linux unknown 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
**Chromium**: 86.0.4240.75 snap
![memoryLeak](https://user-images.githubusercontent.com/9612749/96447364-1373ce80-1212-11eb-87d4-24c874987205.jpg)

**Comment by Mad1723** [comment]
I have experienced the same. The script ends up loading my 32GB of memory fully after a day or 2 of running.

**Comment by jef** [comment]
Yep. Same within Docker. Probably a browser/tab not getting closed in a certain mode. Will look into soon.

**Comment by GRINSPANKER13** [comment]
I'm not sure if the issues is related to closing the incognito BrowserContext, but I forgot to include the following:

await context.close();

Seems to be an old problem, see [Here](https://github.com/puppeteer/puppeteer/issues/4684#issuecomment-516118097)

**Comment by SesioN** [comment]
@GRINSPANKER13 
It seems that it was indeed the missing context.close(), after adding that to the code the memory leak seems to be gone.

**Comment by jef** [comment]
Sweet! Thank you very much @GRINSPANKER13
