### ISSUE TITLE
Amazon UK not working

### ISSUE THREAD

**Issue by dmemedo** [jef/nvidia-snatcher#546]
### Description

When I try to monitor amazon Uk, I see warn :  [amazon-uk] [setup (3080)] :: NO STORE LINKS FOUND

Any idea why please?

**Comment by andrewmackrodt** [comment]
Your client is temporarily banned as it's been detected as a bot and made too many requests. Links are refreshed every 5 minutes, it should work eventually.

**Comment by dmemedo** [comment]
I got the error the first time I enabled amazon uk, I doubt the client is banned

**Comment by andrewmackrodt** [comment]
There's little else I can think of that would cause that message, on a "clean" IP address, this is the output I get:

```
[16:12:05] info :: ℹ selected stores: amazon-uk
[16:12:05] info :: ℹ selected series: 3080
[16:12:11] info :: ✖ [amazon-uk] [setup (3080)] :: FOUND 2 STORE LINKS
[16:12:12] info :: ✖ [amazon-uk] [setup (3080)] :: FOUND 23 STORE LINKS
[16:12:16] info :: ✖ [amazon-uk] [asus (3080)] rog strix oc :: OUT OF STOCK
```

If you were to run with `HEADLESS=false` it should be possible to see if the Amazon search page is able to load correctly. I imagine it's throwing up some kind of captcha / bot traffic page.

**Comment by dmemedo** [comment]
thank you, it's weird, it does work after a while
