### ISSUE TITLE
Add Asus (DE) store

### ISSUE THREAD

**Issue by Tomson124** [jef/nvidia-snatcher#551]
### Description

When the "Asus" store is selected it always uses the US store which doesn't really work for people outside the US in terms of delivery. Would be good if it would search the store based on the country someone lives. 
### Possible solution

Maybe we could use the language setting which is currently only used for Nvidia and "calculate" the correct link language abbreviation for the store like e.g. germany --> de

**Comment by jef** [comment]
This is more than just locale support, it's seperate store. You can see with other countries, they have completely different store setups, as they may or may not provide the same cards as well.

I'll keep this issue open in hopes that someone will add the Asus store for the specified countries.

Thanks!

**Comment by johnconnor2020** [comment]
> This is more than just locale support, it's seperate store. You can see with other countries, they have completely different store setups, as they may or may not provide the same cards as well.
> 
> I'll keep this issue open in hopes that someone will add the Asus store for the specified countries.
> 
> Thanks!

This person added the german asus store, but you need to approve it.
https://github.com/jef/nvidia-snatcher/pull/528

**Comment by jef** [comment]
Resolved with #528
