### ISSUE TITLE
Bug in PCComponentes store

### ISSUE THREAD

**Issue by alvarobasi** [jef/nvidia-snatcher#560]
### Description

When selecting `pccomponentes` as one of the stores to track, it doesn't appear in the logs.

I'm using the dockerized application in a Windows 10 machine.

### Possible solution

In the [pccomponentes.ts](https://github.com/jef/nvidia-snatcher/blob/main/src/store/model/pccomponentes.ts) file I chose the following labels for checking status:
```
labels: {
		inStock: {
			container: '#btnsWishAddBuy',
			text: ['Comprar']
		},
		outOfStock: {
			container: '#btnsWishAddBuy',
			text: ['Avísame']
		}
	},
```

However, testing this container selection in the Chrome Console gives the following output:
```
console.log($('#btnsWishAddBuy').text());

$Añadir a lista}¥Añadir al carrito
Comprar
]
```

How does the program filter using the `text: ['Comprar']` property? Is there a contains function or something similar? Maybe the breaklines are hurting the algorithm? Or may the error be in the `text: ['Avísame']` property with the accent in the i? In that case, leaving the `inStock` property alone would be the solution.

**Comment by xninjax** [comment]
> How does the program filter using the `text: ['Comprar']` property? 

The script is looking for a substring - and your selectors look fine, confirmed to be working against the test-card for me...
![image](https://user-images.githubusercontent.com/23090488/96768089-a770a200-139a-11eb-80e7-7318857f9c17.png)

I see in your PR you've made updates to the model names (to now match project convention).  Was this the issue for you?

PS- anyone looking for a zotac right now? 😄 
![image](https://user-images.githubusercontent.com/23090488/96768840-8bb9cb80-139b-11eb-8cef-ff57c19b513d.png)

**Comment by alvarobasi** [comment]
> 
> > How does the program filter using the `text: ['Comprar']` property? 
> 
> The script is looking for a substring - and your selectors look fine, confirmed to be working against the test-card for me...
> ![image](https://user-images.githubusercontent.com/23090488/96768089-a770a200-139a-11eb-80e7-7318857f9c17.png)
> 
> I see in your PR you've made updates to the model names (to now match project convention).  Was this the issue for you?
> 
> PS- anyone looking for a zotac right now? 😄 
> ![image](https://user-images.githubusercontent.com/23090488/96768840-8bb9cb80-139b-11eb-8cef-ff57c19b513d.png)
> 
> 
> 

Yep! Exactly. The issue was in the model filtering I was applying, as "tuf gaming" and "tuf oc gaming" doesn't match with the actual labels "tuf" and "tuf oc". With the latest PR this is fixed. My bad! 😅

**Comment by jef** [comment]
Thanks @xninjax!

**Comment by alvarobasi** [comment]
Hi @jef ! Remember to review and merge my PR #563 in order to match the model names with the project convention! Thanks!!

**Comment by jef** [comment]
Thank you very much @alvarobasi
