### ISSUE TITLE
cannot find module mqtt after latest git pull master origin

### ISSUE THREAD

**Issue by vivomancer** [jef/nvidia-snatcher#561]
On startup I receive the following error

npm start

> nvidia-snatcher@ start C:\Users\vivom\Git
> npm run build && node build/index.js

> nvidia-snatcher@ build C:\Users\vivom\Git
> rimraf ./build && tsc

src/notification/mqtt.ts:2:65 - error TS2307: Cannot find module 'mqtt' or its corresponding type declarations.

2 import MqttClient, {IClientOptions, IClientPublishOptions} from 'mqtt';

**Comment by Mad1723** [comment]
Same issue.

**Comment by v1ct0rv** [comment]
You need to do `npm install` first.

**Comment by Mad1723** [comment]
Derp. That fixed it! Thanks @v1ct0rv
