### ISSUE TITLE
Not receiving SMS notifications (EDIT: does not work on "npm run test:notifcation")

### ISSUE THREAD

**Issue by sesar88** [jef/nvidia-snatcher#564]
On the .env file, I did the test:brand, test:model stuff to see if the code was working fine. Turns out that it is not sending me an SMS.  However, when I run "npm run test:notification" it seems to be working just fine. Below is the .env file

BROWSER_TRUSTED=
COUNTRY=usa
DESKTOP_NOTIFICATIONS=true
DISCORD_NOTIFY_GROUP=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD="mypassword"
EMAIL_TO=
EMAIL_USERNAME="myemail"
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH="false"
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MICROCENTER_LOCATION=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=true
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=0
PHONE_CARRIER=sprint
PHONE_NUMBER=xxxxxxxxxx
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=true
SHOW_ONLY_BRANDS=nvidia
SHOW_ONLY_MODELS=founders edition
SHOW_ONLY_SERIES=3080
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=bestbuy
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
USER_AGENT="my user agent (idk if its ok to show it)"

edit: Also everything else seems to be working fine, I am still receiving emails and the desktop notifications are still working. It even says SMS sent but I have not received it.

edit 2: when I reinstalled Nvidia Snatcher, the SMS messages now don't work on "npm run test:notification"

**Comment by GRINSPANKER13** [comment]
I believe this issue is with gmail. Are you using a VPN by chance? Each time I connect to a different server, I have to sign out and sign back into gmail, for the sms to be sent.

**Comment by sesar88** [comment]
Yes, I am using a VPN, I'll try that right now to see if that fixes it.

**Comment by sesar88** [comment]
@GRINSPANKER13 I signed out and signed back in but I am still not receiving SMS messages. Email still works

**Comment by Tiffys** [comment]
You may not have unsecured devices or w/e turned on for your google account. If you don't it'll reject the attempt.

**Comment by jef** [comment]
I believe there are problems with VPN and email usage. Using an app password is recommended and I would not recommend enabled less secured devices.

**Comment by jef** [comment]
Duplicate, please move discussion to here: https://github.com/jef/nvidia-snatcher/issues/370
