### ISSUE TITLE
Speed up site checking

### ISSUE THREAD

**Issue by wuruochong** [jef/nvidia-snatcher#57]
### Description

Right now sites are being checked in sequence, which can result in a long gap between checks of the same site, especially if there are slow checks in the process.
For example, when I'm checking Nvidia, Bestbuy, and Newegg only, there is a ~2min gap between checks of the FE on Nvidia's store. Considering how fast the first round sold out and how low the FE stock is, this is definitely too slow.
This can probably be solved if some or all the checks can be made to run in parallel.

**Comment by jef** [comment]
They are running in parallel per store, but the process is slow due to getting some of the page content. 

I'm in the process of getting html tags and loading based on their results and that should speed up the process.

**Comment by arickho** [comment]
@jef It's `puppeteer.launch();` that takes longest in your script. If you invoke the browser only once you should be able to improve your lookup() speeds and substitute browser.close() -> page.close()

**Comment by arickho** [comment]
![Capture](https://user-images.githubusercontent.com/17790061/93670983-3c673f00-fa6d-11ea-9374-9fe76814af58.PNG)

**Comment by jef** [comment]
Good call. I'll do that. I'm working on some refactoring right now and some cart implementations, so I can pull that one in.

**Comment by arickho** [comment]
Nice. love your work!

**Comment by jef** [comment]
Thanks for the contribution! I would have you put this in if you'd like after I get this refactoring done and you can make your mark 😄

**Comment by jef** [comment]
Closed via #83
