### ISSUE TITLE
nvidia-api is now returning 400 bad request

### ISSUE THREAD

**Issue by nderen** [jef/nvidia-snatcher#572]
### Description

Seems like the nvidia shop has changed under the hood. The nvidia-api scraper is now returning an HTTP 400 Bad Request instead of a 504/200/etc. This seems different from the "they disabled their API" functionality we've been seeing for the last couple of weeks.

My env is mostly stock. Relevant bits:
```
SHOW_ONLY_BRANDS="nvidia,evga"
SHOW_ONLY_MODELS="founders edition,ftw3 ultra,ftw3"
SHOW_ONLY_SERIES="3080"
STORES="nvidia,nvidia-api,bestbuy,newegg,amazon"
```

**Comment by jfeliciano-dev** [comment]
Stop scraping nvidia they're no longer selling cards on their site.  All nvidia stock is going to bestbuy for US.
