### ISSUE TITLE
Missed stock alert for german 3080 FE cards 

### ISSUE THREAD

**Issue by BeefMediumRare** [jef/nvidia-snatcher#584]
### Description

Today (23.10.2020) there was stock from 12:08PM to 12:27PM (UTC).
The button on the nvidia store said `buy now` and in a pop up notebooksbilliger.de could be selected. However nvidia snatcher did not notice that there was stock available.

![image](https://user-images.githubusercontent.com/13456150/97004180-f35b4c80-153c-11eb-9e52-84a390178f81.png)

That's my config (running the nightly docker image):
![image](https://user-images.githubusercontent.com/13456150/97004787-d7a47600-153d-11eb-9692-039ce8e57528.png)

**Comment by thefirestrings666** [comment]
Hi,

Yes, you're right, I had the case, but I guess it's because nVidia don't sell the article from it own website. The distribution  moved to a third party. I guess notebooksbilliger is now an official retailer.

**Comment by jef** [comment]
Closing.

> I guess it's because nVidia don't sell the RTX 30xx anymore from their own website
