### ISSUE TITLE
Additional node.js running even after closing the open one.

### ISSUE THREAD

**Issue by Tiffys** [jef/nvidia-snatcher#591]
### Description

After CTRL+C ending the script in power shell then closing power shell there were still over a dozen chromium windows running in my task manager, which could not be closed. CPU usage was 100% - it even froze my PC for like a minute. Using Process Explorer I was able to kill the node.js entire tree.

I suspect at some point when I ended one instance it just kept running in the background instead of closing, so I had one process running up front and one hidden one running in the background.

Not really sure if there's anything in the script that could cause this, or just a freak accident. But if anyone else encounters massive CPU usage, then see chromium instances running even after closing the power shell process, you'll have to use process explorer or something to end the extra hidden node.js.

**Comment by TheTabKey** [comment]
This is a script, use powershell not cmd.

**Comment by Tiffys** [comment]
> This is a script, use powershell not cmd.

I said power shell several times...

**Comment by TheTabKey** [comment]
works perfectly in powershelld, asks to terminate everytime and you just type "y" and enter

**Comment by Tiffys** [comment]
> works perfectly in powershell, asks to terminate everytime and you just type "y" and enter

These responses aren't very helpful. Look, of course it says that in the powershell window. But at some point canceling and restarting them a bunch of times, it can bug out I guess and keep one open instead of terminating it, even with powershell closed entirely. The bug I am talking about you will not see in powershell. You'll just see the chromium processes in your task manager or process explorer.

**Comment by jef** [comment]
This is normal for most programs that get certain signal calls. Your best bet is to use <kbd>Ctrl</kbd> + <kbd>C</kbd> before closing the terminal. Otherwise, you will have to kill processes in your Task Manager (on Windows).
