### ISSUE TITLE
Discord mods shouldn't ban users for making suggestions.

### ISSUE THREAD

**Issue by Tiffys** [jef/nvidia-snatcher#592]
### Description

For a project like this it should be sought for users to make suggestions. But for my effort of making suggestions I was banned. The moderator that banned me, SalamUchiha#6239, was appointed as a moderator that day after having clearly been trolling me earlier that day himself (not exactly mod-worthy behavior). Then purposefully brings up a disruptive bad topic other mods had asked not to discuss (and flame baits), on purpose, then bans me.

You guys really need to get a handle on the chat in the nvidia snatcher discord, in general. It's extremely toxic.

Like total shitter memester troll stuff from the worst corners of the internet stuff, like constant.

It's hard to reign in a community once the culture becomes that toxic. But there are ways to go about it. You just gotta nip that behavior in the bud and focus on keeping it more professional and non-toxic so it's actually not a horrible experience for people to look at or try to participate in.

Just need some clear rules, then active mods, then set it up with muting or roles that are set to remove write permissions in certain channels, then utilize those as tools before stuff like kicks/bans come into place.

But people are easy to jump on bandwagons with bad behavior like leemurs. It's just... mob mentality. You just gotta cut the behavior off and stop it before it gets out of control every time and display that that kinda behavior just doesn't fly there.

It's just a show of authority, really. If people know they can get away with literally anything, some will act unruly. Just like in school when kids had a hardass teacher and were quiet as mice then get a sub they can walk all over then just go wild like a circus show.

If you want it to be a friendly community for everyone then you gotta work towards that. Toxicity isn't good for communities, imo. Scares off good people and nullifies the ability to have useful dialogue.

The most important thing is a clear set of rules, then enforcing them. Though I’d suggest detailing scenarios with your definitions of various things so there can be no confusion nor excuses. Just don’t be afraid to adjust them as necessary but announce changes and don’t harshly punish offenders of rules/aspects that didn’t previously exist.

A bot that makes you emoji to confirm you read the rules it states to get access to channels can be useful so nobody has an excuse for not reading them.

Though first and foremost you can't have powertripping trolls appointed as mods with free reign to do whatever they want on a whim, without even so much as a trial period.

To be clear, I don't have any interest in coming back to the discord in its current state even if I were unbanned. I don't need that kinda drama and childish nonsense in my life. I just want them to fix stuff and get their shit together for the good of the community. If you get banned for making suggestions and the chat itself is just a massive immature trollfest there's no point in it.

**Comment by BeardlessDuck** [comment]
lmao

**Comment by jef** [comment]
Hi @Tiffys. Sorry this happened. I don't own the Discord channel nor am I not really on the Discord channel that often. Whatever is done there is their prerogative and I don't have much authority.

**Comment by jef** [comment]
I would love to have any suggestion and please feel free to post suggestions here!

**Comment by jef** [comment]
I have since removed the Discord link from the `README`.

Thanks! https://github.com/jef/nvidia-snatcher/commit/0318f33234382e6eaf878d4772e0f6f4e821e613
