### ISSUE TITLE
Unable to `npm install` on Manjaro Linux ARM (Raspberry Pi 4)

### ISSUE THREAD

**Issue by MrM21632** [jef/nvidia-snatcher#596]
### Description

I'm currently unable to successfully run `npm install`. The following error is thrown during the Puppeteer install script:

```
> puppeteer@5.3.1 install /home/joshua/nvidia-snatcher/node_modules//puppeteer
> node install.js

The chromium library is not available for arm64:
If you are on Ubuntu, you can install with:

 apt-get install chromium-browser

/home/joshua/nvidia-snatcher/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112
            throw new Error();
            ^

Error
    at /home/joshua/nvidia-snatcher/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112:19
    at FSReqCallback.oncomplete (fs.js:181:21)
```

Seems like Puppeteer isn't able to find chromium on Manjaro ARM at the moment. This is especially concerning since I have chromium currently installed:

```
$ chromium --version
Chromium 86.0.4240.75 Arch Linux ARM
$ node -v
v14.13.1
$ npm -v
6.14.7
```

I'm currently running this on a Raspberry Pi 4B 8GB with Manjaro Linux ARM 20.10 Xfce.

### Possible solution

This is likely an issue with Puppeteer itself, or I may be missing a critical library somewhere. I'm not sure which library(ies) would be missing, though.

**Comment by MrM21632** [comment]
Issue submitted to the Puppeteer project as well: puppeteer/puppeteer#6546.

**Comment by andrewmackrodt** [comment]
```sh
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
export PUPPETEER_EXECUTABLE_PATH=$(which chromium)
npm run install
npm run start
```

**Comment by jef** [comment]
Interesting though, because I can build and run on Arch Linux.

**Comment by MrM21632** [comment]
Using @andrewmackrodt solution, as well as a suggestion from the puppeteer issue, I was able to resolve this problem. Thanks for the help, everyone!
