### ISSUE TITLE
Script stops randomly

### ISSUE THREAD

**Issue by lmcke169** [jef/nvidia-snatcher#60]
### Description

Script stops randomly and just sits there no error or log

### Possible solution

Have it record the last whatever number of steps taken before the script is stopped so we can trace it

**Comment by geman220** [comment]
This has been brought up by at least 3 people in discord, may be more widespread.

**Comment by jef** [comment]
Yeah this is hard to reproduce... I haven't had this problem and been running for about 24+ hours. Update this issue if it happens again and take a screenshot.

What OS are you running?

**Comment by Daykod** [comment]
I think I saw this happen too. When it happened, I tried closing powershell. It showed it timing out on one listing then resumed business as usual. I restarted it anyway.

**Comment by Daykod** [comment]
Saw this happen again.
I'm on commit ccc781b8ddd30fbdd5a3a8daae4303e6b6c15ae8.
Here's a recording that has the timestamps:
https://imgur.com/a/4cuqP1T

**Comment by jef** [comment]
Oh, so the problem has to do with what #73 is trying to accomplish? Doesn't look like it's crashing (closing the problem), but just restarting the loop?

**Comment by jef** [comment]
I think this was fixed with https://github.com/jef/nvidia-snatcher/pull/75. Let me know if you continue to have issues with latest.

**Comment by Daykod** [comment]
yup, I'll come back to this issue if I notice it getting stuck again, thanks

**Comment by Daykod** [comment]
It got stuck again after two hours. When I went to close it I caught a glimpse of an uncaught exception but powershell shut down too fast for me to get anything specific. Writing the log to disk might be a good idea?

**Comment by jef** [comment]
Yeah. Perhaps I should do that too. That's interesting though, not many have faced your problem. I'll be sure to add it in as a configuration.

**Comment by lmcke169** [comment]
Most recent update is no longer crashing for me.

**Comment by saltynut1** [comment]
I've had this as well, if i notice it and press ctrl + c it'll update and possibly continue on, or it might stay stuck until I stop it and start it up again.

**Comment by saltynut1** [comment]
So I updated to latest, and left it running all night and that did seem to fix the problem for me.

**Comment by jef** [comment]
Closing for now. Will open again if problem continues. Thanks all for the help.

**Comment by QuitoPR** [comment]
Was running into this, fixed it disabling quick edit in Powershell/Command prompt in Windows. 
https://stackoverflow.com/questions/27230255/cmd-prompt-freezes-until-i-hit-ctrlc-then-continues-as-normal
