### ISSUE TITLE
"STORES" environment variable doesnt work at start

### ISSUE THREAD

**Issue by TheTabKey** [jef/nvidia-snatcher#600]
Now goes through every store at the beginning, then after initial spam it will go back to the configured variables.

**Comment by Macaddict42** [comment]
Is this really fixed? I'm still experiencing this.

**Comment by jef** [comment]
Not sure, seems to work fine for me. I would make sure you have the latest code.

**Comment by Macaddict42** [comment]
![ns_log](https://user-images.githubusercontent.com/38168730/97332870-2e5cc900-1838-11eb-9d19-eebec2a67b64.PNG)
This is what it looks like for me. I'm on the latest source and have run npm install after a git pull. Is there a cache I should try clearing?

**Comment by jef** [comment]
Interesting. OK, what does your `.env` look like?

**Comment by Macaddict42** [comment]
# ** All configuration variables are optional **
# Read https://github.com/jef/nvidia-snatcher#customization for help on customizing this file
#############################################################################################

BROWSER_TRUSTED="false"
COUNTRY="usa"
DESKTOP_NOTIFICATIONS="false"
EMAIL_PASSWORD="redacted"
EMAIL_TO="redacted"
EMAIL_USERNAME="redacted"
HEADLESS="true"
IN_STOCK_WAIT_TIME="0"
LOG_LEVEL="info"
LOW_BANDWIDTH="false"
MAX_PRICE_SERIES_3070="600"
MAX_PRICE_SERIES_3080="900"
MAX_PRICE_SERIES_3090="1600"
MICROCENTER_LOCATION="web"
NVIDIA_ADD_TO_CART_ATTEMPTS="10"
NVIDIA_SESSION_TTL="60000"
OPEN_BROWSER="true"
PAGE_BACKOFF_MIN="10000"
PAGE_BACKOFF_MAX="3600000"
PAGE_SLEEP_MIN="5000"
PAGE_SLEEP_MAX="10000"
PAGE_TIMEOUT="30000"
PHONE_CARRIER="tmobile"
PHONE_NUMBER="5035503453"
PLAY_SOUND="alert.mp3"
PUSHOVER_TOKEN="redacted"
PUSHOVER_USER="redacted"
PUSHOVER_PRIORITY="1"
SCREENSHOT="true"
SHOW_ONLY_BRANDS="asus, nvidia"
SHOW_ONLY_MODELS="rog strix, rog strix oc, strix, tuf, tuf oc, founders edition"
SHOW_ONLY_SERIES="3080"
STORES="amazon, bestbuy, newegg"
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

**Comment by Macaddict42** [comment]
I did a fresh clone and pull, same results. Most likely something to do with my config or the base code.

**Comment by TheTabKey** [comment]
Nothing wrong, i closed this already but it was reopen for some reason.

**Comment by jef** [comment]
I think it's with the code, because I usually test with minimal setups. I just used the `STORE=amazon` and starting using all the stores.

Probably has something to do with this: https://github.com/jef/nvidia-snatcher/commit/503d76f3c7d01368fc978af4ab02924d3d036ac0, but still need to debug.

**Comment by jef** [comment]
Wow... Oops. This is not a problem.

![image](https://user-images.githubusercontent.com/12074633/97334773-7ccb9100-1853-11eb-9dbb-da032445723f.png)

If you notice, you get the other stores in the beginning, but the stores in search are the ones you've specified.

I don't believe this is an issue.

**Comment by Macaddict42** [comment]
I wouldn't say it's a bug in that it's a blocking issue. But I would say it's probably unintended behavior. It didn't used to do this, was a recent change.

**Comment by Macaddict42** [comment]
![ns_log2](https://user-images.githubusercontent.com/38168730/97335850-8c3ee000-183b-11eb-817f-e87d6149fa9a.PNG)
It also does this where it will randomly interject 1 or 2 searches at stores that I've not configured.

**Comment by TheTabKey** [comment]
Doesnt effect functionality at all. I had closed this but it was reopened for some reason.
https://i.imgur.com/X4Vx5Xi.png

**Comment by jef** [comment]
Fixing the logic to not evaluate any stores that are not in the list.
