### ISSUE TITLE
Sleep back to default values after recent changes

### ISSUE THREAD

**Issue by MGraefe** [jef/nvidia-snatcher#601]
Using the same config, commit 699de573f6579b59ba2c65cc2bf4dd6ccba3c863 works completely fine and as desired.
However, most recent main 3c22a458b298d2478c8f9f4e907b7cbc085cd011 seems to ignore set SLEEP values and used the 5/10 second default.

**Comment by MGraefe** [comment]
@Doridian I think this might be caused by your changes

**Comment by SesioN** [comment]
I confirm that this issue comes from #183 and breaks #576 completely.

https://github.com/jef/nvidia-snatcher/commit/373d1a973865b14b5753517aa70eabf85b136d94#r43577281

**Comment by JakeAi** [comment]
I also am experiencing it too. Insta-banned from Asus website.

**Comment by SesioN** [comment]
btw. I actually got banned because of this issue too, I hope they do unban after a while :/
(But on amazon website)

I recommend reverting to commit a42418f814dcd91354c136288d4c6a24e03a168d until its fixed.
