### ISSUE TITLE
Add the puppeteer stealth extension to help reduce bot detection

### ISSUE THREAD

**Issue by aharris02** [jef/nvidia-snatcher#61]
### Description

Provides extra detection prevention.

### Possible solution

Requires switching Puppeteer library to puppeteer-extra, then adding & loading the puppeteer-extra-plugin-stealth library.
https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra

**Comment by jef** [comment]
This is really cool! Thanks for this. I'll be sure to put this on priority.

**Comment by aharris02** [comment]
Cool! Glad I could help.

I tried to get it working and couldn't quite figure out the import. Shouldn't take an actual dev very long. There's also an adblocking extension that might help with page performance:
https://www.npmjs.com/package/puppeteer-extra-plugin-adblocker

**Comment by jef** [comment]
Closed via #83
