### ISSUE TITLE
3070 Stores

### ISSUE THREAD

**Issue by CronianIce** [jef/nvidia-snatcher#611]
### Description

It looks like this doesn't search for the 3070 in the US market yet which is understandable since it releases on October 29th. Some stores like Best Buy list them as coming soon though. Would it be proper to fork, update the models, and issue a pull request? Or should I wait until October 29th when all the links drop?

### Possible solution

- Update models in /src/store/model/
- Wait for more links to populate on release date

**Comment by jef** [comment]
If the links are ready for 3070, we should definitely bring them in! Feel free to make a PR and we'll go over the links!

**Comment by jef** [comment]
Here's this: https://github.com/jef/nvidia-snatcher/pull/612 FE - Best Buy

If you have anymore, please feel free to add!

**Comment by CronianIce** [comment]
> Here's this: #612 FE - Best Buy
> 
> If you have anymore, please feel free to add!

This was the exact link I was planning to add. I'll keep a look out for more.

**Comment by jef** [comment]
Sorry to steal that from you 😢 Look forward to seeing future PRs!
