### ISSUE TITLE
App reporting cards in stock at Asus store when they are not

### ISSUE THREAD

**Issue by bobbywatson3** [jef/nvidia-snatcher#633]
### Description

App is reporting Asus ROG Strix and TUF 3080 cards in stock, but when I visit the site, they are not in stock. Note there may be other series that also show up as in stock, but I'm only checking for 3080's.

**Comment by bobbywatson3** [comment]
`[5:44:01 PM] info :: 🚀🚨 [asus] [asus (3080)] tuf oc :: IN STOCK 🚨🚀
https://store.asus.com/us/item/202009AM160000001`

**Comment by ethanspitz** [comment]
I'm seeing this too. Note that when I load the page, it says in stock and quickly updates to say not in stock. I think it's another case of the page saying it's in stock by default and then javascript updating the page.

**Comment by jef** [comment]
Probably has something to do with the incognito mode being enabled.

**Comment by ethanspitz** [comment]
I see it and I do not have incognito mode enabled.

**Comment by jef** [comment]
Do you mind posting your `.env` when you get the chance? Thanks!

**Comment by bobbywatson3** [comment]
I removed all of my notification settings, otherwise everything else is the same. I had to increase sleep times for asus because I was getting blocked.
```
# ** All configuration variables are optional **
# Read https://github.com/jef/nvidia-snatcher#customization for help on customizing this file
#############################################################################################

BROWSER_TRUSTED=
COUNTRY=
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=false
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MICROCENTER_LOCATION=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=3080,3070
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=amazon,asus:60000:120000,newegg,pny,zotac
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0"
```

**Comment by jef** [comment]
Yeah, Asus blocks pretty quickly. Okay -- I see what you all are saying. It'll be interesting to solve this problem. I can see if I can add stall times for evaluation for certain stores.

**Comment by jef** [comment]
Newegg is now being searched via API. Hopefully this will alleviate any pain points.

**Comment by jbwilliams1** [comment]
I am taking this ticket

**Comment by jbwilliams1** [comment]
FYI Asus's API exposes their item cost 🤣 

![image](https://user-images.githubusercontent.com/689186/98017581-113e7200-1dc5-11eb-8ef5-bff8da4989a1.png)

**Comment by jef** [comment]
Wow... That's quite the profit, even after shipping.
