### ISSUE TITLE
No longer looking up Asus ROG Strix OC on best buy or Newegg 

### ISSUE THREAD

**Issue by Rokatoro** [jef/nvidia-snatcher#635]
### Description
My snatcher no longer seems to be looking for the Asus Rog Strix cards one either best buy or newegg. Both of these sites return look ups for other cards just not that specific one.
![2020-10-29](https://user-images.githubusercontent.com/73666745/97624502-91e42380-19fd-11eb-9aa7-92ca76e5f41b.png)

**Comment by alrowa7i** [comment]
![image](https://user-images.githubusercontent.com/58651218/97637868-da7afb80-1a54-11eb-8df7-d08406abdcde.png)
same thing for me. I hope there is a fix soon.

**Comment by jef** [comment]
I'll take a look. Thanks!

**Comment by jef** [comment]
Okay, looked into it. Those sites no longer have the OC Edition. If you end up finding a link, let me know and we can add it. I would add `rog strix` to your filter/

Thanks!

**Comment by alrowa7i** [comment]
I found it in newegg:
https://www.newegg.com/asus-geforce-rtx-3090-rog-strix-rtx3090-o24g-gaming/p/N82E16814126456?Description=3090&cm_re=3090-_-14-126-456-_-Product
