### ISSUE TITLE
Use Amazon's API

### ISSUE THREAD

**Issue by jef** [jef/nvidia-snatcher#64]
### Description

We could potentially use Amazon's API and get information that way. https://webservices.amazon.com/paapi5/documentation/use-cases/using-offer-information/determining-availability.html

**Comment by Hari-Nagarajan** [comment]
You can't use this for this purpose, you need access to the affiliate api, requirements are: https://affiliate-program.amazon.com/help/node/topic/G8TW5AE9XL2VX9VM/ref=amb_link_0SCmvU4qQnOltlh4q-t01g_6?pf_rd_p=f6ebaf96-904b-45de-bbf6-06eb866f07fd

**Comment by geman220** [comment]
Looks like 3 "qualified sale" are required for access so it's probably a no-go to access the Amazon API.

**Comment by jef** [comment]
Yeah, going to close this out for now unless we discover more information.

**Comment by lozbinks** [comment]
Hi there guy's, I have access to the Amazon API so would be happy to test this function if it is possible to do so with SM? @jef
