### ISSUE TITLE
Numerous Newegg false positives

### ISSUE THREAD

**Issue by amarshall** [jef/nvidia-snatcher#643]
### Description

Lots of (seemingly) false positives on Newegg for EVGA 3080 FTW3 Ultra this morning (over the past hour so far, and ongoing). Visiting the product page, the “add to cart” link does sometimes appear, but attempting to add to cart yields an error modal “Oops...looks like we have encountered some problem on our end. Please try again in a little while.”; in the Newegg app, this manifests as “added to cart successfully”, but cart is empty—using Apple Pay on the product page instead of “add to cart” yields an error modal “sold out”.

I’m running latest commit 2fc584bdbdb978b5a57bc8660c2a1d3c5be0a81b. Running with headless and low bandwidth enabled.

### Possible solution

Perhaps clicking add to cart when in stock and check for error.

**Comment by NicolasNewman** [comment]
I'm having the same issue as well. I've seen it happening with the ASUS Tuf OC and RoG Strix too.

**Comment by scot-onet** [comment]
Same, tuf, strix, and FTW 3 ultra.  Running in regular bandwidth mode.  updated to latest as of an hour ago.

**Comment by jbwilliams1** [comment]
They aren't false positives, they are being bought this fast.

I actually was able to grab a 3080 today because of the notification.

**Comment by amarshall** [comment]
> They aren't false positives, they are being bought this fast.

Then why have I been intermittently receiving the notification dozens of times for the past three hours? I’ve seen Newegg go from “auto notify” to “add to cart” with no load time issues, only to have “add to cart” give an error immediately dozens of times at this point. I’ve also seen the page load with “add to cart” and change to “auto notify” after loading, and vice-versa.

Maybe there was stock hours ago, but it feels strongly like Newegg is intermittently incorrectly showing “add to cart” due to some caching issue on their end, but actually clicking “add to cart” reflects the actual state.

**Comment by jbwilliams1** [comment]
@amarshall oops! Guess I got lucky on the previous bundle return with them then. Otherwise I'd have a z390 motherboard on ebay right now 😬

Anyway, since I was able to procure a card during the alerts today, I hesitate to suggest there is actually a bug. If perhaps y'all had some concrete proof I would be inclined to believe it, but given that I was actually able to purchase one, it seems the alert did exactly what it was supposed to - and was right

**Comment by amarshall** [comment]
What time, then, did you manage to actually purchase? Again: I’m not doubting there was stock at some point, but I am doubting that stock has been intermittently becoming available every few or so minutes for the past 5 hours. I’ve seen “add to cart” probably 100+ times today.

**Comment by jbwilliams1** [comment]
@amarshall Order was placed at 9:07am CDT today

**Comment by bderbi24** [comment]
@jbwilliams1 Definitely false positives, I've been at work, and received over 350 emails/text via nvidia-snatcher. Asus Tuff/Strix, and Evga FTW 3.

**Comment by jbwilliams1** [comment]
@bderbi24 can you provide screenshots? I have received 6 alerts from NS today in total.

**Comment by scot-onet** [comment]
I had about 50-60 in the two hours I was running it (1230-230pm eastern).  had to stop because it would alert every couple minutes and distract from work.

**Comment by bderbi24** [comment]
@jbwilliams1 Ive Been receiving notifications since 8:10am. Could not cut it off since I was at work. Term the application when I got home. Images posted below:
[image](https://user-images.githubusercontent.com/73716658/97747238-a259d400-1ab9-11eb-82e9-aed28404b03c.png)![image](https://user-images.githubusercontent.com/73716658/97747254-a84fb500-1ab9-11eb-9461-de7dd68bad92.png)![image](https://user-images.githubusercontent.com/73716658/97747278-b43b7700-1ab9-11eb-875f-bbbbc232b027.png)![image](https://user-images.githubusercontent.com/73716658/97747297-bbfb1b80-1ab9-11eb-86c0-033fa7b8751a.png)![image](https://user-images.githubusercontent.com/73716658/97747361-d634f980-1ab9-11eb-95a9-e3b1d881a02b.png)

**Comment by jbwilliams1** [comment]
@bderbi24 Yeah that's concerning. Are you running the most up-to-date version? This might actually be a bug with the gmail notification system. I use the Telegram notification and definitely did not receive this many.

I am going to take a look at the newegg API and see if I can't help smooth this out. I do think there needs to be a second check at the very least for Newegg, as they have the shoddiest page system of them all (I believe they have frequent outages and serve stale when they occur, which might explain the ATC, and might explain why some see it more than others).

When the edge CDN is serving stale when ATC buttons are present, the snatcher will definitely freak out and give false positives :)

**Comment by NarryG** [comment]
Same issue here. Got 50+ individual hits before I shut it up.

**Comment by bderbi24** [comment]
> @bderbi24 Yeah that's concerning. Are you running the most up-to-date version? This might actually be a bug with the gmail notification system. I use the Telegram notification and definitely did not receive this many.
> 
> 
> 
> I am going to take a look at the newegg API and see if I can't help smooth this out. I do think there needs to be a second check at the very least for Newegg, as they have the shoddiest page system of them all (I believe they have frequent outages and serve stale when they occur, which might explain the ATC, and might explain why some see it more than others).
> 
> 
> 
> When the edge CDN is serving stale when ATC buttons are present, the snatcher will definitely freak out and give false positives :) 

Negative, I was using ver 1.5. I will update to 2.0, and report back.

**Comment by jbwilliams1** [comment]
FYI I just did some debugging (Akamai headers) and can confirm they will serve stale on a HIT with an expired page. This means they likely have a stale-while-error condition as well. @jef almost certainly need a secondary check to ensure newegg validity or figure out a way to trick a cache bust. Query parameters won't work, but maybe fuzzing the URL in some way will

**Comment by v1ct0rv** [comment]
I'm getting aboutn 50-60 nitifications per hour, This is very annoying, disabling newegg for now....

**Comment by jbwilliams1** [comment]
@jef - I am working on a branch now, but have limited time available. If you'd like to communicate with me on Discord or something so you know if I'm moving you can add me at BeefWhiskers#3421

**Comment by lngchn** [comment]
> They aren't false positives, they are being bought this fast.
> 
> I actually was able to grab a 3080 today because of the notification.

No, it's false positive. When I go to a product page, on initial load, it shows the add to cart button, but then quickly show out of stock. Refreshing the page does the same thing. Sometime the add to cart button stays there but result in error when clicked.

**Comment by Ghoddy** [comment]
Also running into this issue, I have numerous people clicking the links and checking and not 1 is an actual positive

**Comment by thefl0yd** [comment]
I was convinced this was a bug yesterday too, but people on the nowinstocknet chat swore they were getting cards throughout virtually the entire time period I was convinced these were false positives. For the record: I had the same issues as most of the people above - unable to ApplePay on mobile and the oops error on desktops. I had to keep switching the NE store off and back on throughout the day.

Anyway I see there's a separate request to switch over to the newegg API which is probably more reliable regardless.
