### ISSUE TITLE
Newegg API Support

### ISSUE THREAD

**Issue by TheTabKey** [jef/nvidia-snatcher#646]
Newegg has a public api for each product. Example of 3080 ftw3 ultra:
https://www.newegg.com/product/api/ProductRealtime?ItemNumber=14-487-518

If you search "Instock" , you will find that it is not in stock and the stock amount...which in this case:
![sfLMG8d](https://user-images.githubusercontent.com/26450925/97742080-09b75a00-1aa1-11eb-8c2b-cbe6d54ff374.png)

This is a realtime stock checker and would give more accurate results than the current check for "add to cart" as it tends to bug out. Item numbers can sometimes be found in the urls or if you have developer tools/network open and refresh the page, you can find by searching "ItemNumber":
![nshrnUd](https://user-images.githubusercontent.com/26450925/97742493-96621800-1aa1-11eb-9eeb-3338df4c5106.png)

And will be shown in the first link.

I would be happy to get the newegg-api.ts setup with all the api urls if this is something that sounds like a good idea.
"LocalAvail" is the correct variable for current inventory stock.

**Comment by jef** [comment]
That sounds like an awesome idea. If you think that it's repeatable and we don't have _frequent_ rate limits, I think it's a great solution!

**Comment by TheTabKey** [comment]
I spammed it for a little and loads instantly everytime without rate limits.

**Comment by TheTabKey** [comment]
![fbXP5EO](https://user-images.githubusercontent.com/26450925/97753442-04fba180-1ab3-11eb-93b3-496ce7dc045c.png)
Can actually be found pretty easy by searching "ProductRealtime"

**Comment by TheTabKey** [comment]
Probably best to check that LocalAvail variable is greater than 1

**Comment by TheTabKey** [comment]
Also here is a bestbuy api:
https://www.bestbuy.com/api/tcfb/model.json?paths=%5B%5B%22shop%22%2c%22buttonstate%22%2c%22v5%22%2c%22item%22%2c%22skus%22%2c6429440%2c%22conditions%22%2c%22NONE%22%2c%22destinationZipCode%22%2c92582%2c%22storeId%22%2c%201441%2c%22context%22%2c%22cyp%22%2c%22addAll%22%2c%22false%22%5D%5D&method=get

sku can be replaced.....and between using these two apis, it will reduce bandwidth usage by a great margin, be faster, and reduce issues compared to trying to load product page. Url was cleaned up so it only shows the important information. @jef
