### ISSUE TITLE
MAC running default ENV, not the custom ENV

### ISSUE THREAD

**Issue by Ghoddy** [jef/nvidia-snatcher#655]
Just recently downloaded snatcher on mac and when trying to run it I reveal the file in finder and edit with Sublime but when I save it then run it in terminal its running the default env not the one i saved.
![Screen Shot 2020-10-31 at 10 57 19 AM](https://user-images.githubusercontent.com/72343615/97782489-25396800-1b68-11eb-9cc7-3f3162ea86ef.png)
![Screen Shot 2020-10-31 at 10 56 10 AM](https://user-images.githubusercontent.com/72343615/97782490-266a9500-1b68-11eb-99e3-8f8094badbaa.png)

**Comment by GRINSPANKER13** [comment]
Make sure the one you created is named ".env" and the filetype is ENV File and not TEXT File.

**Comment by Ghoddy** [comment]
I have it set to a .env file and still no luck. Its still running default settings.


![Screen Shot 2020-11-02 at 4 20 09 PM](https://user-images.githubusercontent.com/72343615/97920373-590ebc00-1d27-11eb-9b51-8184598629a2.png)

**Comment by Ghoddy** [comment]
Fixed the issue. I didnt have it saved as ".env" i had it saved to "env"
