### ISSUE TITLE
Suggestion: Move lookup logic 

### ISSUE THREAD

**Issue by vp-cshow** [jef/nvidia-snatcher#67]
### Description

After taking a look at #64, I think it would be a good idea to move the `lookup` logic to the `Store` interface, and force all of the different stores to implement their own `lookup`. This change will probably be necessary if the project is looking at having different approaches for checking stock at different stores (apis, full page scraping, element scraping).

I don't mind implementing this; just looking for feedback/a green light if I choose to do continue so I don't waste anyone's time.

**Comment by jef** [comment]
I'm actually doing this now as we speak! Haha, thanks :)

**Comment by vp-cshow** [comment]
Sounds good!
