### ISSUE TITLE
Having trouble getting "DISCORD_NOTIFY_GROUP" to work 

### ISSUE THREAD

**Issue by Latif-99** [jef/nvidia-snatcher#679]
Hello, I just want to say thank you for this program. I do not know much about coding im currently taking introductory school courses and I find this stuff extremely interesting. 

I'm running into an issue with the discord notify group line within the .env file. My discord web hook works great, however, I cannot manage to get the discord notify group line to work. Im assuming the discord notify group will do "@role" so that I would get notified because ive missed a bunch of the notifications. I've provided an image of what my DISCORD_NOTIFY_GROUP line looks like if anyone is able to figure out what i'm doing wrong, thanks in advance!

![Screenshot 2020-11-03 180725](https://user-images.githubusercontent.com/73757730/98050330-757e2780-1dff-11eb-82f7-372fd52dedf7.png)

**Comment by Latif-99** [comment]
I also for the life of me cannot figure out how to label this post

**Comment by jef** [comment]
You're super close... I need to update the `README`.

Use `<@&number>` instead of `<@number>`.

**Comment by Latif-99** [comment]
Hey, that fixed it for me, maanged to snag a 3080 TUF card today. Thanks for everything Jef!

**Comment by jef** [comment]
> Hey, that fixed it for me, maanged to snag a 3080 TUF card today. Thanks for everything Jef!

AWESOME!!! Congrats! 🎉
