### ISSUE TITLE
Error playing sound

### ISSUE THREAD

**Issue by jimbo1111** [jef/nvidia-snatcher#76]
Can't get sound alerts to work, have tried .wav and .m4a files, both in .resources/sounds/ and .resources/sounds/true/

filenames are alert.wav and alert2.m4a

This is while testing notifications with NOTIFICATION_TEST set to true

Saw no more config information in any readme so asking here

**Comment by jef** [comment]
Okay, I can look into this.

Thanks!

**Comment by jimbo1111** [comment]
This is the error that I get btw:

"[2:07:56 PM] info :: ✔ playing sound
[2:07:56 PM] error :: error playing sound: 1"

**Comment by geman220** [comment]
Potentially solved in #91

**Comment by jef** [comment]
Okay, I see the problem. Yes, #91 fixes this. I need to update the docs to say how to set this variable. Not very specific.
