### ISSUE TITLE
Prompting for Chromium.app to accept incoming network connections.

### ISSUE THREAD

**Issue by goines** [jef/nvidia-snatcher#78]
I don't know if it's a step I'm missing in the setup, but on my mac the chromium being used by puppeteer is throwing firewall prompts all the time.

"Do you want the application 'Chromium.app' to accept incoming network connections".

This keeps prompting even if Allow is selected. Is there a step missing to whitelist the right chromium app in the fireball?

Thanks.

**Comment by vp-cshow** [comment]
See the wiki:

https://github.com/jef/nvidia-snatcher/wiki/Troubleshoot:-macOS:-Chromium.app-security-popup

**Comment by goines** [comment]
Thanks!
