### ISSUE TITLE
Discord Invite Expired

### ISSUE THREAD

**Issue by neurot1cal** [jef/nvidia-snatcher#80]
### Description

Discord Invite in README.md broken ;)

### Possible solution

Create new invite

**Comment by jef** [comment]
Closed: https://github.com/jef/nvidia-snatcher/commit/14b1e4cee6d8468f1847fb327c2b3f15b1439be7

**Comment by SNLabat** [comment]
> Fixed! [14b1e4c](https://github.com/jef/nvidia-snatcher/commit/14b1e4cee6d8468f1847fb327c2b3f15b1439be7)

I tried using this to access the Discord but it says the link is expired?

https://discord.com/invite/14b1e4c correct?
