### ISSUE TITLE
Pushover-notifications doesn't work. 

### ISSUE THREAD

**Issue by Aidan5206** [jef/nvidia-snatcher#99]
### Description

Whenever the program tries to trigger a notification or tries to open the browser, the program error codes. 

Error: application token is invalid
    at Pushover.errors (C:\...\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146:13)
    at IncomingMessage.<anonymous> (C:\...\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:250:12)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nvidia-snatcher@1.4.0 start: `npm run build && node build/index.js "run"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nvidia-snatcher@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jef** [comment]
> application token is invalid

Are you sure the token is correct? I don't have Pushover, so I can't do any confirmation.

**Comment by mr-sour** [comment]
Pushover works fine. I think the docs could be updated though. I think think @Aidan5206 issue is that they put the user token as the pushover token and email for pushover user. PUSHOVER_TOKEN requires you to go to the dashboard and register a new app api token. The PUSHOVER_USER token is the token you see when you launch the app.

**Comment by mr-sour** [comment]
#107  Heres a quick fix

**Comment by Ori-Pixel** [comment]
thanks @mr-sour works for me now

**Comment by Aidan5206** [comment]
Thanks for the quick reply, however, the issue still persists on my end.

**Comment by Ori-Pixel** [comment]
@Aidan5206 got to the site: https://pushover.net/apps/build

```
create an account if you don't have one
go to your profile > scroll down to your newly created
put token in as pushover token
put your pushover client token from your profile into the pushover user
```

it should look like this then:
```
PUSHOVER_TOKEN="aatmh1p4wxu9bkys4b[...]"
PUSHOVER_USER="uacocuge8akixhfmh[...]"
```

**Comment by Aidan5206** [comment]
Okay, so I have the notifications working now. I created an account and inputted my user token into PUSHOVER_USER but I left the PUSHOVER_TOKEN blank. Is leaving the other token blank okay because, correct me if I'm wrong, but isn't the other token generated on your end, the application side.
